// Code generated by azapin; DO NOT EDIT.
package managedidentity

import (
	"regexp"

	nativeschema "github.com/Azure/terraform-provider-azapi/internal/native/schema"
	"github.com/Azure/terraform-provider-azapi/internal/native/services"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/mapplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// AzapiUserAssignedIdentitySchema returns the Terraform resource schema for Microsoft.ManagedIdentity/userAssignedIdentities@2024-11-30.
func AzapiUserAssignedIdentitySchema() schema.Schema {
	return schema.Schema{
		Description: "Manages a Microsoft.ManagedIdentity/userAssignedIdentities resource. [azapin:Microsoft.ManagedIdentity/userAssignedIdentities@2024-11-30]",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				Required:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
				MarkdownDescription: "Specifies the name of the Azure resource.",
			},
			"resource_group_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Validators: []validator.String{
					stringvalidator.RegexMatches(
						regexp.MustCompile(`(?i)^/subscriptions/[^/]+/resourceGroups/[^/]+$`),
						"resource_group_id must be a resource group ID (/subscriptions/{id}/resourceGroups/{name})",
					),
				},
				MarkdownDescription: "The ID of the parent resource that contains this resource.",
			},
			"location": schema.StringAttribute{
				Description: "The geo-location where the resource lives",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					nativeschema.UseStateForEquivalentLocation(),
					stringplanmodifier.RequiresReplace(),
				},
			},
			"properties": schema.SingleNestedAttribute{
				Description: "The properties associated with the identity.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.UseStateForUnknown(),
				},
				Attributes: map[string]schema.Attribute{
					"client_id": schema.StringAttribute{
						Description: "The id of the app associated with the identity. This is a random generated UUID by MSI.",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"isolation_scope": schema.StringAttribute{
						Description: "Enum to configure regional restrictions on identity assignment, as necessary.",
						Required:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"None",
								"Regional",
							),
						},
					},
					"principal_id": schema.StringAttribute{
						Description: "The id of the service principal object associated with the created identity.",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"tenant_id": schema.StringAttribute{
						Description: "The id of the tenant which the identity belongs to.",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
				},
			},
			"system_data": schema.SingleNestedAttribute{
				Description: "Azure Resource Manager metadata containing createdBy and modifiedBy information.",
				Computed:    true,
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.UseStateForUnknown(),
				},
				Attributes: map[string]schema.Attribute{
					"created_at": schema.StringAttribute{
						Description: "The timestamp of resource creation (UTC).",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"created_by": schema.StringAttribute{
						Description: "The identity that created the resource.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"created_by_type": schema.StringAttribute{
						Description: "The type of identity that created the resource.",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"User",
								"Application",
								"ManagedIdentity",
								"Key",
							),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"last_modified_at": schema.StringAttribute{
						Description: "The timestamp of resource last modification (UTC)",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"last_modified_by": schema.StringAttribute{
						Description: "The identity that last modified the resource.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"last_modified_by_type": schema.StringAttribute{
						Description: "The type of identity that last modified the resource.",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"User",
								"Application",
								"ManagedIdentity",
								"Key",
							),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
				},
			},
			"tags": schema.MapAttribute{
				Description: "Resource tags.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.Map{
					mapplanmodifier.UseStateForUnknown(),
				},
				ElementType: types.StringType,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				MarkdownDescription: "The ID of the Azure resource.",
			},
		},
	}
}

// UserAssignedIdentity describes azapi_user_assigned_identity for registration and config builders.
var UserAssignedIdentity = services.Descriptor{
	Name:           "azapi_user_assigned_identity",
	ARMType:        "Microsoft.ManagedIdentity/userAssignedIdentities",
	APIVersion:     "2024-11-30",
	Schema:         AzapiUserAssignedIdentitySchema,
	WritableScopes: 8,
	ParentAttr:     "resource_group_id",
}

func init() { services.Register(UserAssignedIdentity) }
