package generator

import (
	"fmt"
	"go/format"
	"sort"
	"strings"

	"github.com/Azure/terraform-provider-azapi/internal/native/naming"
)

// EmitSchema renders Go source for a generated Terraform resource schema.
func EmitSchema(def *ResourceDefinition) (string, error) {
	if def.Body == nil || def.Body.Kind != KindObject {
		return "", fmt.Errorf("resource %s has no object body", def.Name)
	}

	// Resource type without @version drives package/function names.
	armType := def.Name
	if at := strings.Index(armType, "@"); at >= 0 {
		armType = armType[:at]
	}
	tfName := naming.ResourceName(armType)
	service := naming.ServiceName(armType)
	structName := toExportedGoName(tfName)

	// Body + envelope decide imports. Envelope attrs are strings with plan modifiers;
	// customizers may add validators.
	needs := scanImportNeeds(def.Body)
	needs.planmodifier = true
	needs.pmString = true
	for _, a := range []EnvelopeAttr{def.Envelope.Name, def.Envelope.Parent} {
		for _, v := range a.Validators {
			switch v.Kind {
			case ValidatorArmResourceID, ValidatorRegex:
				needs.regexp = true
				needs.stringValidator = true
			case ValidatorStringOneOf, ValidatorStringLength:
				needs.stringValidator = true
			case ValidatorIntRange:
				needs.int64Validator = true
			case ValidatorCustom:
				needs.custom = true
			case ValidatorShared:
				needs.shared = true
			}
		}
	}

	var b strings.Builder

	// Header.
	b.WriteString("// Code generated by azapin; DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", service))
	b.WriteString("import (\n")
	if needs.regexp {
		b.WriteString("\t\"regexp\"\n\n")
	}
	b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/resource/schema\"\n")
	if needs.int64Validator {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework-validators/int64validator\"\n")
	}
	if needs.stringValidator {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator\"\n")
	}
	if needs.planmodifier {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier\"\n")
	}
	if needs.pmString {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier\"\n")
	}
	if needs.pmBool {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier\"\n")
	}
	if needs.pmInt64 {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier\"\n")
	}
	if needs.pmObject {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier\"\n")
	}
	if needs.pmList {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier\"\n")
	}
	if needs.pmMap {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/resource/schema/mapplanmodifier\"\n")
	}
	if needs.stringValidator || needs.int64Validator || needs.custom || needs.shared {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/schema/validator\"\n")
	}
	if needs.types {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/types\"\n")
	}
	if needs.defaults || needs.shared || needs.nativeSchema {
		b.WriteString("\tnativeschema \"github.com/Azure/terraform-provider-azapi/internal/native/schema\"\n")
	}
	b.WriteString("\t\"github.com/Azure/terraform-provider-azapi/internal/native/services\"\n")
	if needs.custom {
		b.WriteString(fmt.Sprintf("\t\"github.com/Azure/terraform-provider-azapi/internal/native/services/%s/validators\"\n", service))
	}
	b.WriteString(")\n\n")

	// Schema function.
	b.WriteString(fmt.Sprintf("// %sSchema returns the Terraform resource schema for %s.\n", structName, def.Name))
	b.WriteString(fmt.Sprintf("func %sSchema() schema.Schema {\n", structName))
	b.WriteString("\treturn schema.Schema{\n")
	b.WriteString(fmt.Sprintf("\t\tDescription: \"Manages a %s resource. [azapin:%s]\",\n", armType, def.Name))
	b.WriteString("\t\tAttributes: map[string]schema.Attribute{\n")

	// Operational envelope first, common configurable body fields next, then the
	// remaining body, then common metadata/outputs.
	emitEnvelopeStringAttr(&b, def.Envelope.Name, "\t\t\t")
	emitEnvelopeStringAttr(&b, def.Envelope.Parent, "\t\t\t")
	emitAttributes(&b, def.Body, 3, false)
	emitEnvelopeIDAttr(&b, "\t\t\t")

	b.WriteString("\t\t},\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	// Descriptor used by config builders and registry init.
	descName := strings.TrimPrefix(structName, "Azapi")
	b.WriteString(fmt.Sprintf("// %s describes %s for registration and config builders.\n", descName, tfName))
	b.WriteString(fmt.Sprintf("var %s = services.Descriptor{\n", descName))
	b.WriteString(fmt.Sprintf("\tName:       %q,\n", tfName))
	b.WriteString(fmt.Sprintf("\tARMType:    %q,\n", armType))
	b.WriteString(fmt.Sprintf("\tAPIVersion: %q,\n", def.APIVersion))
	b.WriteString(fmt.Sprintf("\tSchema:     %sSchema,\n", structName))
	if def.WritableScopes != 0 {
		b.WriteString(fmt.Sprintf("\tWritableScopes: %d,\n", def.WritableScopes))
	}
	b.WriteString(fmt.Sprintf("\tParentAttr: %q,\n", def.Envelope.Parent.Name))
	if len(def.Relational) > 0 {
		b.WriteString("\tRelational: []services.RelationalConstraint{\n")
		for _, rc := range def.Relational {
			b.WriteString(fmt.Sprintf("\t\t{Kind: services.%s, Paths: [][]string{", rc.Kind))
			for _, segs := range rc.Paths {
				b.WriteString("{")
				for j, s := range segs {
					if j > 0 {
						b.WriteString(", ")
					}
					b.WriteString(fmt.Sprintf("%q", s))
				}
				b.WriteString("}, ")
			}
			b.WriteString("}")
			if rc.Message != "" {
				b.WriteString(fmt.Sprintf(", Message: %q", rc.Message))
			}
			b.WriteString("},\n")
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n\n")
	b.WriteString(fmt.Sprintf("func init() { services.Register(%s) }\n", descName))

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("gofmt emitted schema for %s: %w", def.Name, err)
	}
	return string(formatted), nil
}

// FileName returns <service>/<resource>_gen.go for a generated descriptor.
func FileName(def *ResourceDefinition) string {
	armType := def.Name
	if at := strings.Index(armType, "@"); at >= 0 {
		armType = armType[:at]
	}
	tfName := strings.TrimPrefix(naming.ResourceName(armType), "azapi_")
	return naming.ServiceName(armType) + "/" + tfName + "_gen.go"
}

type importNeeds struct {
	regexp          bool
	int64Validator  bool
	stringValidator bool
	types           bool // for types.StringType in ListAttribute
	defaults        bool // for nativeschema.Static*
	planmodifier    bool // for planmodifier.X plan-modifier slices
	pmString        bool // stringplanmodifier
	pmBool          bool // boolplanmodifier
	pmInt64         bool // int64planmodifier
	pmObject        bool // objectplanmodifier
	pmList          bool // listplanmodifier
	pmMap           bool // mapplanmodifier
	custom          bool // for a service-specific services/<service>/validators reference
	shared          bool // for a generic nativeschema validator reference (SharedValidator)
	nativeSchema    bool // for generic native schema helpers that are not validators/defaults
}

func scanImportNeeds(typ *Type) importNeeds {
	var needs importNeeds
	scanImportNeedsRecurse(typ, &needs)
	return needs
}

func scanImportNeedsRecurse(typ *Type, needs *importNeeds) {
	if typ == nil || typ.Kind != KindObject {
		return
	}
	for _, prop := range typ.Properties {
		if prop.Flags.IsSystemManaged() {
			continue
		}
		if isManagedServiceIdentityProperty(prop) {
			needs.nativeSchema = true
			continue
		}
		computed := effectiveComputed(prop)
		if prop.DefaultValue != "" {
			needs.defaults = true
		}
		if usesLocationPlanModifier(prop, computed) {
			needs.nativeSchema = true
			needs.planmodifier = true
		}
		for _, v := range prop.Validators {
			switch v.Kind {
			case ValidatorArmResourceID, ValidatorRegex:
				needs.regexp = true
				needs.stringValidator = true
			case ValidatorStringOneOf, ValidatorStringLength:
				needs.stringValidator = true
			case ValidatorIntRange:
				needs.int64Validator = true
			case ValidatorCustom:
				needs.custom = true
			case ValidatorShared:
				needs.shared = true
			}
		}
		if prop.Type.IsEnum() && !computed {
			needs.stringValidator = true
		}
		if prop.Type.Kind == KindArray && (prop.Type.ElementType == nil || prop.Type.ElementType.Kind != KindObject) {
			needs.types = true
		}
		if prop.Type.Kind == KindMap && (prop.Type.ElementType == nil || prop.Type.ElementType.Kind != KindObject) {
			needs.types = true
		}
		// State reuse and ForceNew both need type-specific plan modifier imports.
		// SetAttribute has no bundled planmodifier package in this framework version.
		useState := !prop.UseSet && !prop.Flags.IsRequired() && prop.DefaultValue == ""
		forceNew := !prop.UseSet && prop.ForceNew && !computed
		if useState || forceNew {
			if pkg, _ := planModifierFor(prop); pkg != "" {
				needs.planmodifier = true
				switch pkg {
				case "stringplanmodifier":
					needs.pmString = true
				case "boolplanmodifier":
					needs.pmBool = true
				case "int64planmodifier":
					needs.pmInt64 = true
				case "mapplanmodifier":
					needs.pmMap = true
				case "objectplanmodifier":
					needs.pmObject = true
				case "listplanmodifier":
					needs.pmList = true
				}
			}
		}
		if prop.Type.Kind == KindObject {
			scanImportNeedsRecurse(prop.Type, needs)
		}
		if prop.Type.Kind == KindMap && prop.Type.ElementType != nil && prop.Type.ElementType.Kind == KindObject {
			scanImportNeedsRecurse(prop.Type.ElementType, needs)
		}
		if prop.Type.Kind == KindArray && prop.Type.ElementType != nil && prop.Type.ElementType.Kind == KindObject {
			scanImportNeedsRecurse(prop.Type.ElementType, needs)
		}
	}
}

// isFullyComputed reports whether an object is entirely server-populated.
func isFullyComputed(typ *Type) bool {
	if typ.Kind != KindObject || len(typ.Properties) == 0 {
		return false
	}
	for _, prop := range typ.Properties {
		if prop.Flags.IsSystemManaged() || prop.Flags.IsReadOnly() {
			continue
		}
		if prop.Type.Kind == KindObject && isFullyComputed(prop.Type) {
			continue
		}
		return false
	}
	return true
}

// effectiveComputed folds explicit read-only, azwise-computed and fully read-only
// nested shapes into Computed-only schema attrs.
func effectiveComputed(prop *Property) bool {
	if prop.ForceComputed || prop.Flags.IsReadOnly() {
		return true
	}
	if prop.Type.Kind == KindObject && isFullyComputed(prop.Type) {
		return true
	}
	if prop.Type.Kind == KindArray && prop.Type.ElementType != nil &&
		prop.Type.ElementType.Kind == KindObject && isFullyComputed(prop.Type.ElementType) {
		return true
	}
	return false
}

// emitAttributes writes an object's Terraform attributes. Dynamic values inside
// collection elements degrade to strings because the framework rejects nested Dynamic.
func emitAttributes(b *strings.Builder, objType *Type, indent int, inCollection bool) {
	if objType.Kind != KindObject {
		return
	}
	propNames := orderedPropertyNames(objType, indent, inCollection)

	tabs := strings.Repeat("\t", indent)
	for _, armName := range propNames {
		prop := objType.Properties[armName]
		if prop.Flags.IsSystemManaged() {
			continue
		}
		emitAttribute(b, naming.CamelToSnake(armName), prop, tabs, indent, inCollection)
	}
}

func orderedPropertyNames(objType *Type, indent int, inCollection bool) []string {
	propNames := make([]string, 0, len(objType.Properties))
	for name := range objType.Properties {
		propNames = append(propNames, name)
	}
	sort.Strings(propNames)
	if indent != 3 || inCollection {
		return propNames
	}

	front := []string{"location", "sku", "type", "kind"}
	back := []string{"identity", "tags"}
	return orderPropertyNames(propNames, front, back)
}

func orderPropertyNames(sortedNames, front, back []string) []string {
	seen := make(map[string]bool, len(sortedNames))
	available := make(map[string]bool, len(sortedNames))
	for _, name := range sortedNames {
		available[name] = true
	}

	ordered := make([]string, 0, len(sortedNames))
	appendIfPresent := func(name string) {
		if available[name] && !seen[name] {
			ordered = append(ordered, name)
			seen[name] = true
		}
	}
	for _, name := range front {
		appendIfPresent(name)
	}
	for _, name := range sortedNames {
		if !seen[name] && !stringIn(name, back) {
			ordered = append(ordered, name)
			seen[name] = true
		}
	}
	for _, name := range back {
		appendIfPresent(name)
	}
	return ordered
}

func stringIn(needle string, haystack []string) bool {
	for _, item := range haystack {
		if item == needle {
			return true
		}
	}
	return false
}

func emitAttribute(b *strings.Builder, tfName string, prop *Property, tabs string, indent int, inCollection bool) {
	typ := prop.Type
	computed := effectiveComputed(prop)

	if isManagedServiceIdentityProperty(prop) {
		b.WriteString(fmt.Sprintf("%s%q: nativeschema.ManagedServiceIdentity(%t, \"\"),\n", tabs, tfName, identityTypeRequired(prop)))
		return
	}

	switch {
	case typ.Kind == KindString:
		b.WriteString(fmt.Sprintf("%s%q: schema.StringAttribute{\n", tabs, tfName))
		writeAttributeFlags(b, prop, computed, tabs)
		if !computed {
			emitDescriptionStringValidators(b, prop, tabs)
		}
		emitPlanModifiers(b, prop, computed, tabs)
		b.WriteString(fmt.Sprintf("%s},\n", tabs))

	case typ.Kind == KindBool:
		b.WriteString(fmt.Sprintf("%s%q: schema.BoolAttribute{\n", tabs, tfName))
		writeAttributeFlags(b, prop, computed, tabs)
		emitPlanModifiers(b, prop, computed, tabs)
		b.WriteString(fmt.Sprintf("%s},\n", tabs))

	case typ.Kind == KindInt:
		b.WriteString(fmt.Sprintf("%s%q: schema.Int64Attribute{\n", tabs, tfName))
		writeAttributeFlags(b, prop, computed, tabs)
		if !computed {
			emitDescriptionInt64Validators(b, prop, tabs)
		}
		emitPlanModifiers(b, prop, computed, tabs)
		b.WriteString(fmt.Sprintf("%s},\n", tabs))

	case typ.IsEnum():
		b.WriteString(fmt.Sprintf("%s%q: schema.StringAttribute{\n", tabs, tfName))
		writeAttributeFlags(b, prop, computed, tabs)
		// Computed fields are server-owned; skip settable validators.
		if !computed {
			values := typ.EnumValues()
			if len(values) > 0 {
				b.WriteString(fmt.Sprintf("%s\tValidators: []validator.String{\n", tabs))
				b.WriteString(fmt.Sprintf("%s\t\tstringvalidator.OneOf(\n", tabs))
				for _, v := range values {
					b.WriteString(fmt.Sprintf("%s\t\t\t%q,\n", tabs, v))
				}
				b.WriteString(fmt.Sprintf("%s\t\t),\n", tabs))
				b.WriteString(fmt.Sprintf("%s\t},\n", tabs))
			}
		}
		emitPlanModifiers(b, prop, computed, tabs)
		b.WriteString(fmt.Sprintf("%s},\n", tabs))

	case typ.Kind == KindObject:
		b.WriteString(fmt.Sprintf("%s%q: schema.SingleNestedAttribute{\n", tabs, tfName))
		writeAttributeFlags(b, prop, computed, tabs)
		emitPlanModifiers(b, prop, computed, tabs)
		b.WriteString(fmt.Sprintf("%s\tAttributes: map[string]schema.Attribute{\n", tabs))
		emitAttributes(b, typ, indent+2, inCollection)
		b.WriteString(fmt.Sprintf("%s\t},\n", tabs))
		b.WriteString(fmt.Sprintf("%s},\n", tabs))

	case typ.Kind == KindArray:
		if typ.ElementType != nil && typ.ElementType.Kind == KindObject {
			b.WriteString(fmt.Sprintf("%s%q: schema.ListNestedAttribute{\n", tabs, tfName))
			writeAttributeFlags(b, prop, computed, tabs)
			emitPlanModifiers(b, prop, computed, tabs)
			b.WriteString(fmt.Sprintf("%s\tNestedObject: schema.NestedAttributeObject{\n", tabs))
			b.WriteString(fmt.Sprintf("%s\t\tAttributes: map[string]schema.Attribute{\n", tabs))
			emitAttributes(b, typ.ElementType, indent+3, true)
			b.WriteString(fmt.Sprintf("%s\t\t},\n", tabs))
			b.WriteString(fmt.Sprintf("%s\t},\n", tabs))
			b.WriteString(fmt.Sprintf("%s},\n", tabs))
		} else {
			attrType := "ListAttribute"
			if prop.UseSet {
				attrType = "SetAttribute"
			}
			b.WriteString(fmt.Sprintf("%s%q: schema.%s{\n", tabs, tfName, attrType))
			writeAttributeFlags(b, prop, computed, tabs)
			if !prop.UseSet {
				emitPlanModifiers(b, prop, computed, tabs)
			}
			b.WriteString(fmt.Sprintf("%s\tElementType: %s,\n", tabs, listElementType(typ.ElementType)))
			b.WriteString(fmt.Sprintf("%s},\n", tabs))
		}

	case typ.Kind == KindMap:
		if typ.ElementType != nil && typ.ElementType.Kind == KindObject {
			b.WriteString(fmt.Sprintf("%s%q: schema.MapNestedAttribute{\n", tabs, tfName))
			writeAttributeFlags(b, prop, computed, tabs)
			emitPlanModifiers(b, prop, computed, tabs)
			b.WriteString(fmt.Sprintf("%s\tNestedObject: schema.NestedAttributeObject{\n", tabs))
			b.WriteString(fmt.Sprintf("%s\t\tAttributes: map[string]schema.Attribute{\n", tabs))
			emitAttributes(b, typ.ElementType, indent+3, true)
			b.WriteString(fmt.Sprintf("%s\t\t},\n", tabs))
			b.WriteString(fmt.Sprintf("%s\t},\n", tabs))
			b.WriteString(fmt.Sprintf("%s},\n", tabs))
		} else {
			b.WriteString(fmt.Sprintf("%s%q: schema.MapAttribute{\n", tabs, tfName))
			writeAttributeFlags(b, prop, computed, tabs)
			emitPlanModifiers(b, prop, computed, tabs)
			b.WriteString(fmt.Sprintf("%s\tElementType: %s,\n", tabs, listElementType(typ.ElementType)))
			b.WriteString(fmt.Sprintf("%s},\n", tabs))
		}

	case typ.Kind == KindUnion:
		// Non-enum union: accept it as a string for now.
		b.WriteString(fmt.Sprintf("%s%q: schema.StringAttribute{\n", tabs, tfName))
		writeAttributeFlags(b, prop, computed, tabs)
		emitPlanModifiers(b, prop, computed, tabs)
		b.WriteString(fmt.Sprintf("%s},\n", tabs))

	default:
		// Dynamic values cannot live inside collection elements, so fall back to a
		// string there; use DynamicAttribute elsewhere.
		if inCollection {
			b.WriteString(fmt.Sprintf("%s%q: schema.StringAttribute{\n", tabs, tfName))
			writeAttributeFlags(b, prop, computed, tabs)
			b.WriteString(fmt.Sprintf("%s},\n", tabs))
		} else {
			b.WriteString(fmt.Sprintf("%s%q: schema.DynamicAttribute{\n", tabs, tfName))
			writeAttributeFlags(b, prop, computed, tabs)
			b.WriteString(fmt.Sprintf("%s},\n", tabs))
		}
	}
}

// emitPlanModifiers writes state-reuse and replacement plan modifiers.
func emitPlanModifiers(b *strings.Builder, prop *Property, computed bool, tabs string) {
	// State reuse keeps Optional+Computed/read-only values stable; customizers can
	// make null prior state unknown for Azure-populated values.
	useState := !prop.Flags.IsRequired() && prop.DefaultValue == ""
	forceNew := prop.ForceNew && !computed
	location := usesLocationPlanModifier(prop, computed)
	if !useState && !forceNew && !location {
		return
	}
	pkg, typ := planModifierFor(prop)
	if pkg == "" {
		return // type has no plan-modifier package (e.g. dynamic)
	}
	b.WriteString(fmt.Sprintf("%s\tPlanModifiers: []planmodifier.%s{\n", tabs, typ))
	if location {
		b.WriteString(fmt.Sprintf("%s\t\tnativeschema.UseStateForEquivalentLocation(),\n", tabs))
	}
	if useState {
		stateMod := "UseStateForUnknown"
		if prop.NonNullStateForUnknown {
			stateMod = "UseNonNullStateForUnknown"
		}
		b.WriteString(fmt.Sprintf("%s\t\t%s.%s(),\n", tabs, pkg, stateMod))
	}
	if forceNew {
		b.WriteString(fmt.Sprintf("%s\t\t%s.RequiresReplace(),\n", tabs, pkg))
	}
	b.WriteString(fmt.Sprintf("%s\t},\n", tabs))
}

func usesLocationPlanModifier(prop *Property, computed bool) bool {
	return !computed && prop.Name == "location" && prop.Type != nil && prop.Type.Kind == KindString
}

// planModifierFor returns the type-specific plan-modifier package and framework type.
func planModifierFor(prop *Property) (pkg, typ string) {
	switch {
	case prop.Type.Kind == KindString, prop.Type.IsEnum(), prop.Type.Kind == KindUnion:
		return "stringplanmodifier", "String"
	case prop.Type.Kind == KindBool:
		return "boolplanmodifier", "Bool"
	case prop.Type.Kind == KindInt:
		return "int64planmodifier", "Int64"
	case prop.Type.Kind == KindObject:
		return "objectplanmodifier", "Object"
	case prop.Type.Kind == KindArray:
		return "listplanmodifier", "List"
	case prop.Type.Kind == KindMap:
		return "mapplanmodifier", "Map"
	}
	return "", ""
}

func isManagedServiceIdentityProperty(prop *Property) bool {
	if prop == nil || prop.Name != "identity" || prop.Type == nil || prop.Type.Kind != KindObject {
		return false
	}
	props := prop.Type.Properties
	if props == nil {
		return false
	}
	for _, name := range []string{"principalId", "tenantId", "type", "userAssignedIdentities"} {
		if _, ok := props[name]; !ok {
			return false
		}
	}
	return true
}

func identityTypeRequired(prop *Property) bool {
	if !isManagedServiceIdentityProperty(prop) {
		return false
	}
	return prop.Type.Properties["type"].Flags.IsRequired()
}

// writeAttributeFlags writes Description, Required/Optional/Computed, defaults and sensitivity.
func writeAttributeFlags(b *strings.Builder, prop *Property, computed bool, tabs string) {
	if prop.Description != "" {
		desc := strings.ReplaceAll(prop.Description, `"`, `\"`)
		if len(desc) > 200 {
			desc = desc[:200] + "..."
		}
		b.WriteString(fmt.Sprintf("%s\tDescription: %q,\n", tabs, desc))
	}
	if prop.Flags.IsRequired() {
		b.WriteString(fmt.Sprintf("%s\tRequired: true,\n", tabs))
	} else if computed {
		b.WriteString(fmt.Sprintf("%s\tComputed: true,\n", tabs))
	} else if prop.DefaultValue != "" {
		// Framework defaults must be Optional+Computed.
		b.WriteString(fmt.Sprintf("%s\tOptional: true,\n", tabs))
		b.WriteString(fmt.Sprintf("%s\tComputed: true,\n", tabs))
		emitDefault(b, prop, tabs)
	} else {
		b.WriteString(fmt.Sprintf("%s\tOptional: true,\n", tabs))
		b.WriteString(fmt.Sprintf("%s\tComputed: true,\n", tabs))
	}
	if prop.Sensitive {
		b.WriteString(fmt.Sprintf("%s\tSensitive: true,\n", tabs))
	}
}

// listElementType returns the Terraform element type for primitive arrays.
func listElementType(elem *Type) string {
	if elem != nil {
		switch elem.Kind {
		case KindBool:
			return "types.BoolType"
		case KindInt:
			return "types.Int64Type"
		}
	}
	return "types.StringType"
}

// emitDefault writes the generated default for supported scalar types.
func emitDefault(b *strings.Builder, prop *Property, tabs string) {
	switch prop.Type.Kind {
	case KindBool:
		b.WriteString(fmt.Sprintf("%s\tDefault: nativeschema.StaticBool(%s),\n", tabs, prop.DefaultValue))
	case KindString:
		b.WriteString(fmt.Sprintf("%s\tDefault: nativeschema.StaticString(%q),\n", tabs, prop.DefaultValue))
	case KindInt:
		b.WriteString(fmt.Sprintf("%s\tDefault: nativeschema.StaticInt64(%s),\n", tabs, prop.DefaultValue))
	default:
		if prop.Type.IsEnum() {
			b.WriteString(fmt.Sprintf("%s\tDefault: nativeschema.StaticString(%q),\n", tabs, prop.DefaultValue))
		} else {
			// Unsupported default type: leave it computed.
			b.WriteString(fmt.Sprintf("%s\tComputed: true,\n", tabs))
		}
	}
}

// emitDescriptionStringValidators writes string validators from descriptions/azwise.
func emitDescriptionStringValidators(b *strings.Builder, prop *Property, tabs string) {
	emitStringValidators(b, prop.Validators, tabs)
}

// emitStringValidators writes a String validator block.
func emitStringValidators(b *strings.Builder, validators []DescriptionValidator, tabs string) {
	if len(validators) == 0 {
		return
	}

	var items []string
	for _, v := range validators {
		switch v.Kind {
		case ValidatorArmResourceID:
			items = append(items, fmt.Sprintf(
				"%s\t\tstringvalidator.RegexMatches(\n%s\t\t\tregexp.MustCompile(`^/subscriptions/[^/]+/resourceGroups/[^/]+/providers/`),\n%s\t\t\t%q,\n%s\t\t)",
				tabs, tabs, tabs, v.Message, tabs))
		case ValidatorRegex:
			if v.Pattern != "" {
				items = append(items, fmt.Sprintf(
					"%s\t\tstringvalidator.RegexMatches(\n%s\t\t\tregexp.MustCompile(`%s`),\n%s\t\t\t%q,\n%s\t\t)",
					tabs, tabs, v.Pattern, tabs, v.Message, tabs))
			}
		case ValidatorStringOneOf:
			if len(v.Allowed) > 0 {
				var sb strings.Builder
				sb.WriteString(fmt.Sprintf("%s\t\tstringvalidator.OneOf(\n", tabs))
				for _, av := range v.Allowed {
					sb.WriteString(fmt.Sprintf("%s\t\t\t%q,\n", tabs, av))
				}
				sb.WriteString(fmt.Sprintf("%s\t\t)", tabs))
				items = append(items, sb.String())
			}
		case ValidatorStringLength:
			switch {
			case v.Min != nil && v.Max != nil:
				items = append(items, fmt.Sprintf("%s\t\tstringvalidator.LengthBetween(%d, %d)", tabs, *v.Min, *v.Max))
			case v.Min != nil:
				items = append(items, fmt.Sprintf("%s\t\tstringvalidator.LengthAtLeast(%d)", tabs, *v.Min))
			case v.Max != nil:
				items = append(items, fmt.Sprintf("%s\t\tstringvalidator.LengthAtMost(%d)", tabs, *v.Max))
			}
		case ValidatorCustom:
			if v.Call != "" {
				items = append(items, fmt.Sprintf("%s\t\tvalidators.%s", tabs, v.Call))
			}
		case ValidatorShared:
			if v.Call != "" {
				items = append(items, fmt.Sprintf("%s\t\tnativeschema.%s", tabs, v.Call))
			}
		}
	}

	if len(items) > 0 {
		b.WriteString(fmt.Sprintf("%s\tValidators: []validator.String{\n", tabs))
		for _, item := range items {
			b.WriteString(item + ",\n")
		}
		b.WriteString(fmt.Sprintf("%s\t},\n", tabs))
	}
}

// emitEnvelope writes synthetic name/parent/id attrs outside the bicep body.
func emitEnvelope(b *strings.Builder, env Envelope, tabs string) {
	emitEnvelopeStringAttr(b, env.Name, tabs)
	emitEnvelopeStringAttr(b, env.Parent, tabs)
	emitEnvelopeIDAttr(b, tabs)
}

func emitEnvelopeIDAttr(b *strings.Builder, tabs string) {
	// id is uniform and server-assigned; reuse it across plans.
	b.WriteString(fmt.Sprintf("%s%q: schema.StringAttribute{\n", tabs, "id"))
	b.WriteString(fmt.Sprintf("%s\tComputed: true,\n", tabs))
	b.WriteString(fmt.Sprintf("%s\tPlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},\n", tabs))
	b.WriteString(fmt.Sprintf("%s\tMarkdownDescription: %q,\n", tabs, "The ID of the Azure resource."))
	b.WriteString(fmt.Sprintf("%s},\n", tabs))
}

// emitEnvelopeStringAttr writes a required, replacing envelope string attr.
func emitEnvelopeStringAttr(b *strings.Builder, a EnvelopeAttr, tabs string) {
	b.WriteString(fmt.Sprintf("%s%q: schema.StringAttribute{\n", tabs, a.Name))
	b.WriteString(fmt.Sprintf("%s\tRequired: true,\n", tabs))
	b.WriteString(fmt.Sprintf("%s\tPlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},\n", tabs))
	emitStringValidators(b, a.Validators, tabs)
	b.WriteString(fmt.Sprintf("%s\tMarkdownDescription: %q,\n", tabs, a.Description))
	b.WriteString(fmt.Sprintf("%s},\n", tabs))
}

// emitDescriptionInt64Validators writes int64 range validators.
func emitDescriptionInt64Validators(b *strings.Builder, prop *Property, tabs string) {
	if len(prop.Validators) == 0 {
		return
	}

	var items []string
	for _, v := range prop.Validators {
		if v.Kind != ValidatorIntRange {
			continue
		}
		if v.Min != nil && v.Max != nil {
			items = append(items, fmt.Sprintf(
				"%s\t\tint64validator.Between(%d, %d)", tabs, *v.Min, *v.Max))
		} else if v.Min != nil {
			items = append(items, fmt.Sprintf(
				"%s\t\tint64validator.AtLeast(%d)", tabs, *v.Min))
		} else if v.Max != nil {
			items = append(items, fmt.Sprintf(
				"%s\t\tint64validator.AtMost(%d)", tabs, *v.Max))
		}
	}

	if len(items) > 0 {
		b.WriteString(fmt.Sprintf("%s\tValidators: []validator.Int64{\n", tabs))
		for _, item := range items {
			b.WriteString(item + ",\n")
		}
		b.WriteString(fmt.Sprintf("%s\t},\n", tabs))
	}
}

// toExportedGoName converts azapi_storage_account to AzapiStorageAccount.
func toExportedGoName(tfName string) string {
	parts := strings.Split(tfName, "_")
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return b.String()
}
