package generator

import (
	"fmt"
	"go/format"
	"path"
	"reflect"
	"runtime"
	"sort"
	"strings"
	"time"

	"github.com/Azure/terraform-provider-azapi/internal/native/naming"
	"github.com/Azure/terraform-provider-azapi/internal/native/typegraph"
)

// EmitSchema renders Go source for a generated Terraform resource schema.
func EmitSchema(def *typegraph.ResourceDefinition) (string, error) {
	if def.Body == nil || (def.Body.Kind != typegraph.KindObject && def.Body.Kind != typegraph.KindDiscriminated) {
		return "", fmt.Errorf("resource %s has no object or discriminated body", def.Name)
	}

	// Resource type without @version drives package/function names.
	armType := def.Name
	if at := strings.Index(armType, "@"); at >= 0 {
		armType = armType[:at]
	}
	tfName := naming.ResourceName(armType)
	service := naming.ServiceName(armType)
	structName := toExportedGoName(tfName)

	// Body + envelope decide imports. Envelope attrs are strings with plan modifiers;
	// customizers may add validators.
	needs := scanImportNeeds(def.Body)
	needs.planmodifier = true
	needs.pmString = true
	for _, a := range []typegraph.EnvelopeAttr{def.Envelope.Name, def.Envelope.Parent} {
		for _, v := range a.Validators {
			switch v.Kind {
			case typegraph.ValidatorArmResourceID, typegraph.ValidatorRegex:
				needs.regexp = true
				needs.stringValidator = true
			case typegraph.ValidatorStringOneOf, typegraph.ValidatorStringLength:
				needs.stringValidator = true
			case typegraph.ValidatorIntRange:
				needs.int64Validator = true
			case typegraph.ValidatorFunc:
				needs.validatorFunc = true
				needs.validatorPkgs[validatorImportPath(v.Func)] = true
			}
		}
	}

	hasTimeouts := def.Timeouts != (typegraph.Timeouts{})

	var b strings.Builder

	// Header.
	b.WriteString("// Code generated by azapin; DO NOT EDIT.\n")
	b.WriteString(fmt.Sprintf("package %s\n\n", service))
	b.WriteString("import (\n")
	if hasTimeouts {
		b.WriteString("\t\"time\"\n\n")
	}
	if needs.regexp {
		b.WriteString("\t\"regexp\"\n\n")
	}
	b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/resource/schema\"\n")
	if needs.int64Validator {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework-validators/int64validator\"\n")
	}
	if needs.stringValidator {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator\"\n")
	}
	if needs.listValidator {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator\"\n")
	}
	if needs.planmodifier {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier\"\n")
	}
	if needs.pmString {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier\"\n")
	}
	if needs.pmBool {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier\"\n")
	}
	if needs.pmInt64 {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier\"\n")
	}
	if needs.pmObject {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier\"\n")
	}
	if needs.pmList {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier\"\n")
	}
	if needs.pmMap {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/resource/schema/mapplanmodifier\"\n")
	}
	if needs.defBool {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault\"\n")
	}
	if needs.defInt64 {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default\"\n")
	}
	if needs.defString {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault\"\n")
	}
	if needs.defList {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault\"\n")
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/attr\"\n")
	}
	if needs.stringValidator || needs.int64Validator || needs.validatorFunc || needs.listValidator {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/schema/validator\"\n")
	}
	if needs.types {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/types\"\n")
	}
	if needs.nativeSchema {
		b.WriteString("\tnativeschema \"github.com/Azure/terraform-provider-azapi/internal/native/schema\"\n")
	}
	b.WriteString("\t\"github.com/Azure/terraform-provider-azapi/internal/native/services\"\n")
	for _, importPath := range sortedImportPaths(needs.validatorPkgs) {
		// Every validators package shares the base name "validators": the shared
		// generic package imports bare, while a service-local package imports under
		// its derived alias (e.g. networkvalidators) so the two never collide in one
		// file. Emit an explicit alias only when it differs from the base name.
		if q := validatorQualifier(importPath); q != path.Base(importPath) {
			b.WriteString(fmt.Sprintf("\t%s %q\n", q, importPath))
		} else {
			b.WriteString(fmt.Sprintf("\t%q\n", importPath))
		}
	}
	b.WriteString(")\n\n")

	// Schema function.
	b.WriteString(fmt.Sprintf("// %sSchema returns the Terraform resource schema for %s.\n", structName, def.Name))
	b.WriteString(fmt.Sprintf("func %sSchema() schema.Schema {\n", structName))
	b.WriteString("\treturn schema.Schema{\n")
	b.WriteString(fmt.Sprintf("\t\tDescription: \"Manages a %s resource. [azapin:%s]\",\n", armType, def.Name))
	b.WriteString("\t\tAttributes: map[string]schema.Attribute{\n")

	// Operational envelope first, common configurable body fields next, then the
	// remaining body, then common metadata/outputs.
	emitEnvelopeStringAttr(&b, def.Envelope.Name, "\t\t\t")
	emitEnvelopeStringAttr(&b, def.Envelope.Parent, "\t\t\t")
	if def.Body.Kind == typegraph.KindDiscriminated {
		// A discriminated root body emits its shared base props plus one variant
		// block per discriminator value directly at the top level (envelope-wrapped).
		emitDiscriminatedAttributes(&b, def.Body, 3, false)
	} else {
		emitAttributes(&b, def.Body, 3, false)
	}
	emitEnvelopeIDAttr(&b, "\t\t\t")
	for _, m := range def.Envelope.Meta {
		emitMetaAttr(&b, m, "\t\t\t")
	}

	b.WriteString("\t\t},\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	// Descriptor used by config builders and registry init.
	descName := strings.TrimPrefix(structName, "Azapi")
	b.WriteString(fmt.Sprintf("// %s describes %s for registration and config builders.\n", descName, tfName))
	b.WriteString(fmt.Sprintf("var %s = services.Descriptor{\n", descName))
	b.WriteString(fmt.Sprintf("\tName:       %q,\n", tfName))
	b.WriteString(fmt.Sprintf("\tARMType:    %q,\n", armType))
	b.WriteString(fmt.Sprintf("\tAPIVersion: %q,\n", def.APIVersion))
	b.WriteString(fmt.Sprintf("\tSchema:     %sSchema,\n", structName))
	if def.WritableScopes != 0 {
		b.WriteString(fmt.Sprintf("\tWritableScopes: %d,\n", def.WritableScopes))
	}
	b.WriteString(fmt.Sprintf("\tParentAttr: %q,\n", def.Envelope.Parent.Name))
	if hasTimeouts {
		b.WriteString("\tTimeouts: services.Timeouts{\n")
		if d := def.Timeouts.Create; d > 0 {
			b.WriteString(fmt.Sprintf("\t\tCreate: %s,\n", renderDuration(d)))
		}
		if d := def.Timeouts.Read; d > 0 {
			b.WriteString(fmt.Sprintf("\t\tRead: %s,\n", renderDuration(d)))
		}
		if d := def.Timeouts.Update; d > 0 {
			b.WriteString(fmt.Sprintf("\t\tUpdate: %s,\n", renderDuration(d)))
		}
		if d := def.Timeouts.Delete; d > 0 {
			b.WriteString(fmt.Sprintf("\t\tDelete: %s,\n", renderDuration(d)))
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n\n")
	b.WriteString(fmt.Sprintf("func init() { services.Register(%s) }\n", descName))

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		return "", fmt.Errorf("gofmt emitted schema for %s: %w", def.Name, err)
	}
	return string(formatted), nil
}

// FileName returns <service>/<resource>_gen.go for a generated descriptor.
func FileName(def *typegraph.ResourceDefinition) string {
	armType := def.Name
	if at := strings.Index(armType, "@"); at >= 0 {
		armType = armType[:at]
	}
	tfName := strings.TrimPrefix(naming.ResourceName(armType), "azapi_")
	return naming.ServiceName(armType) + "/" + tfName + "_gen.go"
}

type importNeeds struct {
	regexp          bool
	int64Validator  bool
	stringValidator bool
	listValidator   bool            // for listvalidator.ValueStringsAre on primitive-list element enums
	types           bool            // for types.StringType in ListAttribute
	defBool         bool            // for booldefault.StaticBool
	defString       bool            // for stringdefault.StaticString (string + enum defaults)
	defInt64        bool            // for int64default.StaticInt64
	defList         bool            // for listdefault.StaticValue empty-list defaults (+ attr for the element type literal)
	planmodifier    bool            // for planmodifier.X plan-modifier slices
	pmString        bool            // stringplanmodifier
	pmBool          bool            // boolplanmodifier
	pmInt64         bool            // int64planmodifier
	pmObject        bool            // objectplanmodifier
	pmList          bool            // listplanmodifier
	pmMap           bool            // mapplanmodifier
	validatorFunc   bool            // any func-referenced validator present (triggers the validator import)
	validatorPkgs   map[string]bool // import paths of the packages defining func-referenced validators
	nativeSchema    bool            // for generic native schema helpers that are not validators/defaults
}

func scanImportNeeds(typ *typegraph.Type) importNeeds {
	needs := importNeeds{validatorPkgs: map[string]bool{}}
	scanImportNeedsRecurse(typ, &needs)
	return needs
}

// reflectValidatorFunc recovers, from a validator constructor func value (e.g.
// validators.UUID passed as any), the defining package's import path and the
// function name. typegraph stores the func as any so the generator never imports
// the validators package; reflection reads the func's symbol name at generation
// time. Panics on a nil or non-func value — a customizer bug that must fail
// generation rather than emit garbage.
func reflectValidatorFunc(fn any) (importPath, funcName string) {
	rv := reflect.ValueOf(fn)
	if !rv.IsValid() || rv.Kind() != reflect.Func {
		panic(fmt.Sprintf("native: typegraph.Validator requires a validator constructor func value, got %T", fn))
	}
	// full is "<import path>.<Func>"; the import path itself contains slashes, e.g.
	// ".../schema/validators.UUID". Split on the final slash first so the dot that
	// separates the package name from the func name is unambiguous.
	full := runtime.FuncForPC(rv.Pointer()).Name()
	slash := strings.LastIndex(full, "/")
	pkgAndFunc := full[slash+1:]
	dot := strings.Index(pkgAndFunc, ".")
	if dot < 0 {
		panic("native: cannot parse validator func symbol " + full)
	}
	pkgName := pkgAndFunc[:dot]
	funcName = pkgAndFunc[dot+1:]
	importPath = full[:slash+1] + pkgName
	return importPath, funcName
}

// validatorQualifier derives the package qualifier used to reference a validator
// in generated code from its import path. Every validators package shares the base
// name "validators", so the shared generic package (.../schema/validators) keeps
// the bare "validators" qualifier while a service-local package
// (.../services/<svc>/validators) is qualified — and imported under the alias —
// "<svc>validators", so two packages with the same base name never collide in one
// generated file.
func validatorQualifier(importPath string) string {
	const svcPrefix = "internal/native/services/"
	if i := strings.Index(importPath, svcPrefix); i >= 0 {
		if svc, tail, ok := strings.Cut(importPath[i+len(svcPrefix):], "/"); ok && tail == "validators" {
			return svc + "validators"
		}
	}
	return "validators"
}

// validatorCall renders the emitted call expression for a func-referenced
// validator, qualified by its (possibly aliased) package name, e.g.
// "validators.UUID()" or "networkvalidators.VirtualNetworkBgpCommunity()".
func validatorCall(fn any) string {
	importPath, funcName := reflectValidatorFunc(fn)
	return validatorQualifier(importPath) + "." + funcName + "()"
}

// validatorImportPath returns the import path of the package defining a
// func-referenced validator.
func validatorImportPath(fn any) string {
	importPath, _ := reflectValidatorFunc(fn)
	return importPath
}

// sortedImportPaths returns the map keys sorted, for deterministic import output.
func sortedImportPaths(m map[string]bool) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func scanImportNeedsRecurse(typ *typegraph.Type, needs *importNeeds) {
	if typ == nil || (typ.Kind != typegraph.KindObject && typ.Kind != typegraph.KindDiscriminated) {
		return
	}
	for _, prop := range typ.Properties {
		if prop.Flags.IsSystemManaged() {
			continue
		}
		if isManagedServiceIdentityProperty(prop) {
			needs.nativeSchema = true
			continue
		}
		computed := typegraph.EffectiveComputed(prop)
		if prop.DefaultValue != "" {
			switch prop.Type.Kind {
			case typegraph.KindBool:
				needs.defBool = true
			case typegraph.KindString:
				needs.defString = true
			case typegraph.KindInt:
				needs.defInt64 = true
			default:
				if prop.Type.IsEnum() {
					needs.defString = true
				}
			}
		}
		if prop.DefaultEmptyList && prop.Type.Kind == typegraph.KindArray {
			needs.defList = true
			needs.types = true
		}
		if usesLocationPlanModifier(prop, computed) {
			needs.nativeSchema = true
			needs.planmodifier = true
		}
		for _, v := range prop.Validators {
			switch v.Kind {
			case typegraph.ValidatorArmResourceID, typegraph.ValidatorRegex:
				needs.regexp = true
				needs.stringValidator = true
			case typegraph.ValidatorStringOneOf, typegraph.ValidatorStringLength, typegraph.ValidatorStringOneOfCaseInsensitive:
				needs.stringValidator = true
			case typegraph.ValidatorIntRange:
				needs.int64Validator = true
			case typegraph.ValidatorFunc:
				needs.validatorFunc = true
				needs.validatorPkgs[validatorImportPath(v.Func)] = true
			case typegraph.ValidatorListSizeAtLeast, typegraph.ValidatorListSizeAtMost:
				needs.listValidator = true
			}
		}
		// A primitive array/set carrying validators emits them as list-element
		// validators (listvalidator.ValueStringsAre wrapping the string validators).
		if prop.Type.Kind == typegraph.KindArray && !prop.UseSet &&
			(prop.Type.ElementType == nil || prop.Type.ElementType.Kind != typegraph.KindObject) &&
			len(prop.Validators) > 0 {
			needs.listValidator = true
			needs.stringValidator = true
		}
		if (prop.Type.IsEnum() || prop.Type.Kind == typegraph.KindStringLiteral) && !computed {
			needs.stringValidator = true
		}
		if prop.Type.Kind == typegraph.KindArray && (prop.Type.ElementType == nil || prop.Type.ElementType.Kind != typegraph.KindObject) {
			needs.types = true
		}
		if prop.Type.Kind == typegraph.KindMap && (prop.Type.ElementType == nil || prop.Type.ElementType.Kind != typegraph.KindObject) {
			needs.types = true
		}
		// State reuse and ForceNew both need type-specific plan modifier imports.
		// SetAttribute has no bundled planmodifier package in this framework version.
		useState := !prop.UseSet && !prop.Flags.IsRequired() && prop.DefaultValue == "" && !prop.DefaultEmptyList
		forceNew := !prop.UseSet && prop.ForceNew && !computed
		if useState || forceNew {
			if pkg, _ := planModifierFor(prop); pkg != "" {
				needs.planmodifier = true
				switch pkg {
				case "stringplanmodifier":
					needs.pmString = true
				case "boolplanmodifier":
					needs.pmBool = true
				case "int64planmodifier":
					needs.pmInt64 = true
				case "mapplanmodifier":
					needs.pmMap = true
				case "objectplanmodifier":
					needs.pmObject = true
				case "listplanmodifier":
					needs.pmList = true
				}
			}
		}
		if prop.Type.Kind == typegraph.KindObject {
			scanImportNeedsRecurse(prop.Type, needs)
		}
		if prop.Type.Kind == typegraph.KindMap && prop.Type.ElementType != nil && prop.Type.ElementType.Kind == typegraph.KindObject {
			scanImportNeedsRecurse(prop.Type.ElementType, needs)
		}
		if prop.Type.Kind == typegraph.KindArray && prop.Type.ElementType != nil && prop.Type.ElementType.Kind == typegraph.KindObject {
			scanImportNeedsRecurse(prop.Type.ElementType, needs)
		}
		if prop.Type.Kind == typegraph.KindDiscriminated {
			scanImportNeedsRecurse(prop.Type, needs)
		}
	}
	// A discriminated type's variants are emitted as nested object blocks, each
	// carrying the nativeschema.DiscriminatedVariant plan modifier; scan each so
	// their inner attributes contribute their framework imports.
	if len(typ.Variants) > 0 {
		needs.nativeSchema = true
		needs.planmodifier = true
	}
	for _, variant := range typ.Variants {
		scanImportNeedsRecurse(variant, needs)
	}
}

// emitAttributes writes an object's Terraform attributes. Dynamic values inside
// collection elements degrade to strings because the framework rejects nested Dynamic.
func emitAttributes(b *strings.Builder, objType *typegraph.Type, indent int, inCollection bool) {
	if objType.Kind != typegraph.KindObject {
		return
	}
	propNames := orderedPropertyNames(objType, indent, inCollection)

	tabs := strings.Repeat("\t", indent)
	for _, armName := range propNames {
		prop := objType.Properties[armName]
		if prop.Flags.IsSystemManaged() {
			continue
		}
		emitAttribute(b, naming.CamelToSnake(armName), prop, tabs, indent, inCollection)
	}
}

// emitDiscriminatedAttributes writes a discriminated block's attributes: the
// shared base properties, then one Optional SingleNestedAttribute per variant
// (keyed by the snake_cased discriminator value). Variant blocks are mutually
// exclusive; each carries the DiscriminatedVariant plan modifier (reuse prior
// state for an unselected variant, clear it on a switch) with its sibling variant
// names, so an omitted variant stops planning as "(known after apply)".
func emitDiscriminatedAttributes(b *strings.Builder, discType *typegraph.Type, indent int, inCollection bool) {
	tabs := strings.Repeat("\t", indent)

	baseNames := make([]string, 0, len(discType.Properties))
	for name := range discType.Properties {
		baseNames = append(baseNames, name)
	}
	sort.Strings(baseNames)
	for _, armName := range baseNames {
		prop := discType.Properties[armName]
		if prop.Flags.IsSystemManaged() {
			continue
		}
		emitAttribute(b, naming.CamelToSnake(armName), prop, tabs, indent, inCollection)
	}

	values := sortedVariantValues(discType)
	snake := make([]string, len(values))
	for i, value := range values {
		snake[i] = naming.CamelToSnake(value)
	}
	for i, value := range values {
		siblings := make([]string, 0, len(snake)-1)
		for j, name := range snake {
			if j != i {
				siblings = append(siblings, name)
			}
		}
		emitAttribute(b, snake[i], variantProperty(value, discType.Variants[value], siblings), tabs, indent, inCollection)
	}
}

// variantProperty wraps a discriminated variant object as an Optional+Computed
// block property. It is the mutually-exclusive selector for one discriminator
// value: it carries its sibling variant names so the emitter renders the
// DiscriminatedVariant plan modifier (reuse-state-unless-switching), fixing the
// "(known after apply)" drift a plain SuppressStateReuse leaves on an unselected
// variant while still clearing on a variant switch.
func variantProperty(value string, variant *typegraph.Type, siblings []string) *typegraph.Property {
	return &typegraph.Property{
		Name:            value,
		Type:            variant,
		Description:     fmt.Sprintf("Variant %q of the discriminated type.", value),
		VariantSiblings: siblings,
	}
}

// sortedVariantValues returns a discriminated type's variant values in a stable
// order so emission is reproducible.
func sortedVariantValues(discType *typegraph.Type) []string {
	values := make([]string, 0, len(discType.Variants))
	for value := range discType.Variants {
		values = append(values, value)
	}
	sort.Strings(values)
	return values
}

func orderedPropertyNames(objType *typegraph.Type, indent int, inCollection bool) []string {
	propNames := make([]string, 0, len(objType.Properties))
	for name := range objType.Properties {
		propNames = append(propNames, name)
	}
	sort.Strings(propNames)
	if indent != 3 || inCollection {
		return propNames
	}

	front := []string{"location", "sku", "type", "kind"}
	back := []string{"identity", "tags"}
	return orderPropertyNames(propNames, front, back)
}

func orderPropertyNames(sortedNames, front, back []string) []string {
	seen := make(map[string]bool, len(sortedNames))
	available := make(map[string]bool, len(sortedNames))
	for _, name := range sortedNames {
		available[name] = true
	}

	ordered := make([]string, 0, len(sortedNames))
	appendIfPresent := func(name string) {
		if available[name] && !seen[name] {
			ordered = append(ordered, name)
			seen[name] = true
		}
	}
	for _, name := range front {
		appendIfPresent(name)
	}
	for _, name := range sortedNames {
		if !seen[name] && !stringIn(name, back) {
			ordered = append(ordered, name)
			seen[name] = true
		}
	}
	for _, name := range back {
		appendIfPresent(name)
	}
	return ordered
}

func stringIn(needle string, haystack []string) bool {
	for _, item := range haystack {
		if item == needle {
			return true
		}
	}
	return false
}

func emitAttribute(b *strings.Builder, tfName string, prop *typegraph.Property, tabs string, indent int, inCollection bool) {
	typ := prop.Type
	computed := typegraph.EffectiveComputed(prop)

	if isManagedServiceIdentityProperty(prop) {
		b.WriteString(fmt.Sprintf("%s%q: nativeschema.ManagedServiceIdentity(%t, \"\"),\n", tabs, tfName, identityTypeRequired(prop)))
		return
	}

	switch {
	case typ.Kind == typegraph.KindString:
		b.WriteString(fmt.Sprintf("%s%q: schema.StringAttribute{\n", tabs, tfName))
		writeAttributeFlags(b, prop, computed, tabs)
		if !computed {
			emitDescriptionStringValidators(b, prop, tabs)
		}
		emitPlanModifiers(b, prop, computed, tabs)
		b.WriteString(fmt.Sprintf("%s},\n", tabs))

	case typ.Kind == typegraph.KindStringLiteral:
		// A fixed string constant (bicep StringLiteralType) is a string whose only
		// valid value is the literal. Emit a StringAttribute with a OneOf validator,
		// consistent with how the mapper treats it (a plain string, never a Dynamic).
		// Falling through to the default DynamicAttribute would make expand drop it:
		// expandValue routes KindStringLiteral to types.String, which a Dynamic state
		// value fails, silently omitting a required constant from the ARM payload.
		b.WriteString(fmt.Sprintf("%s%q: schema.StringAttribute{\n", tabs, tfName))
		writeAttributeFlags(b, prop, computed, tabs)
		if !computed && typ.Name != "" {
			b.WriteString(fmt.Sprintf("%s\tValidators: []validator.String{\n", tabs))
			b.WriteString(fmt.Sprintf("%s\t\tstringvalidator.OneOf(\n", tabs))
			b.WriteString(fmt.Sprintf("%s\t\t\t%q,\n", tabs, typ.Name))
			b.WriteString(fmt.Sprintf("%s\t\t),\n", tabs))
			b.WriteString(fmt.Sprintf("%s\t},\n", tabs))
		}
		emitPlanModifiers(b, prop, computed, tabs)
		b.WriteString(fmt.Sprintf("%s},\n", tabs))

	case typ.Kind == typegraph.KindBool:
		b.WriteString(fmt.Sprintf("%s%q: schema.BoolAttribute{\n", tabs, tfName))
		writeAttributeFlags(b, prop, computed, tabs)
		emitPlanModifiers(b, prop, computed, tabs)
		b.WriteString(fmt.Sprintf("%s},\n", tabs))

	case typ.Kind == typegraph.KindInt:
		b.WriteString(fmt.Sprintf("%s%q: schema.Int64Attribute{\n", tabs, tfName))
		writeAttributeFlags(b, prop, computed, tabs)
		if !computed {
			emitDescriptionInt64Validators(b, prop, tabs)
		}
		emitPlanModifiers(b, prop, computed, tabs)
		b.WriteString(fmt.Sprintf("%s},\n", tabs))

	case typ.IsEnum():
		b.WriteString(fmt.Sprintf("%s%q: schema.StringAttribute{\n", tabs, tfName))
		writeAttributeFlags(b, prop, computed, tabs)
		// Computed fields are server-owned; skip settable validators.
		if !computed {
			values := typ.EnumValues()
			if len(values) > 0 {
				b.WriteString(fmt.Sprintf("%s\tValidators: []validator.String{\n", tabs))
				b.WriteString(fmt.Sprintf("%s\t\tstringvalidator.OneOf(\n", tabs))
				for _, v := range values {
					b.WriteString(fmt.Sprintf("%s\t\t\t%q,\n", tabs, v))
				}
				b.WriteString(fmt.Sprintf("%s\t\t),\n", tabs))
				b.WriteString(fmt.Sprintf("%s\t},\n", tabs))
			}
		}
		emitPlanModifiers(b, prop, computed, tabs)
		b.WriteString(fmt.Sprintf("%s},\n", tabs))

	case typ.Kind == typegraph.KindObject:
		b.WriteString(fmt.Sprintf("%s%q: schema.SingleNestedAttribute{\n", tabs, tfName))
		writeAttributeFlags(b, prop, computed, tabs)
		emitPlanModifiers(b, prop, computed, tabs)
		b.WriteString(fmt.Sprintf("%s\tAttributes: map[string]schema.Attribute{\n", tabs))
		emitAttributes(b, typ, indent+2, inCollection)
		b.WriteString(fmt.Sprintf("%s\t},\n", tabs))
		b.WriteString(fmt.Sprintf("%s},\n", tabs))

	case typ.Kind == typegraph.KindArray:
		if typ.ElementType != nil && typ.ElementType.Kind == typegraph.KindObject {
			b.WriteString(fmt.Sprintf("%s%q: schema.ListNestedAttribute{\n", tabs, tfName))
			writeAttributeFlags(b, prop, computed, tabs)
			emitPlanModifiers(b, prop, computed, tabs)
			if prop.DefaultEmptyList {
				b.WriteString(fmt.Sprintf("%s\tDefault: listdefault.StaticValue(types.ListValueMust(%s, nil)),\n", tabs, attrTypeLiteral(typ.ElementType)))
			}
			if !computed {
				emitListValidators(b, prop, tabs, false)
			}
			b.WriteString(fmt.Sprintf("%s\tNestedObject: schema.NestedAttributeObject{\n", tabs))
			b.WriteString(fmt.Sprintf("%s\t\tAttributes: map[string]schema.Attribute{\n", tabs))
			emitAttributes(b, typ.ElementType, indent+3, true)
			b.WriteString(fmt.Sprintf("%s\t\t},\n", tabs))
			b.WriteString(fmt.Sprintf("%s\t},\n", tabs))
			b.WriteString(fmt.Sprintf("%s},\n", tabs))
		} else {
			attrType := "ListAttribute"
			if prop.UseSet {
				attrType = "SetAttribute"
			}
			b.WriteString(fmt.Sprintf("%s%q: schema.%s{\n", tabs, tfName, attrType))
			writeAttributeFlags(b, prop, computed, tabs)
			if !prop.UseSet {
				emitPlanModifiers(b, prop, computed, tabs)
			}
			// listvalidator only applies to ListAttribute; a settable primitive list
			// with element validators (e.g. case-insensitive permission enums) gets
			// them via listvalidator.ValueStringsAre.
			if !prop.UseSet && !computed {
				emitListValidators(b, prop, tabs, true)
			}
			b.WriteString(fmt.Sprintf("%s\tElementType: %s,\n", tabs, listElementType(typ.ElementType)))
			b.WriteString(fmt.Sprintf("%s},\n", tabs))
		}

	case typ.Kind == typegraph.KindMap:
		if typ.ElementType != nil && typ.ElementType.Kind == typegraph.KindObject {
			b.WriteString(fmt.Sprintf("%s%q: schema.MapNestedAttribute{\n", tabs, tfName))
			writeAttributeFlags(b, prop, computed, tabs)
			emitPlanModifiers(b, prop, computed, tabs)
			b.WriteString(fmt.Sprintf("%s\tNestedObject: schema.NestedAttributeObject{\n", tabs))
			b.WriteString(fmt.Sprintf("%s\t\tAttributes: map[string]schema.Attribute{\n", tabs))
			emitAttributes(b, typ.ElementType, indent+3, true)
			b.WriteString(fmt.Sprintf("%s\t\t},\n", tabs))
			b.WriteString(fmt.Sprintf("%s\t},\n", tabs))
			b.WriteString(fmt.Sprintf("%s},\n", tabs))
		} else {
			b.WriteString(fmt.Sprintf("%s%q: schema.MapAttribute{\n", tabs, tfName))
			writeAttributeFlags(b, prop, computed, tabs)
			emitPlanModifiers(b, prop, computed, tabs)
			b.WriteString(fmt.Sprintf("%s\tElementType: %s,\n", tabs, listElementType(typ.ElementType)))
			b.WriteString(fmt.Sprintf("%s},\n", tabs))
		}

	case typ.Kind == typegraph.KindUnion:
		// Non-enum union: accept it as a string for now.
		b.WriteString(fmt.Sprintf("%s%q: schema.StringAttribute{\n", tabs, tfName))
		writeAttributeFlags(b, prop, computed, tabs)
		emitPlanModifiers(b, prop, computed, tabs)
		b.WriteString(fmt.Sprintf("%s},\n", tabs))

	case typ.Kind == typegraph.KindDiscriminated:
		// A polymorphic body: emit one SingleNestedAttribute holding the shared base
		// properties plus one Optional SingleNestedAttribute per variant. The active
		// variant selects the ARM discriminator value (synthesized by the mapper);
		// exactly-one-of exclusivity is enforced by a generated resource-level
		// ConfigValidator (see synthesizeDiscriminatorConstraints).
		b.WriteString(fmt.Sprintf("%s%q: schema.SingleNestedAttribute{\n", tabs, tfName))
		writeAttributeFlags(b, prop, computed, tabs)
		emitPlanModifiers(b, prop, computed, tabs)
		b.WriteString(fmt.Sprintf("%s\tAttributes: map[string]schema.Attribute{\n", tabs))
		emitDiscriminatedAttributes(b, typ, indent+2, inCollection)
		b.WriteString(fmt.Sprintf("%s\t},\n", tabs))
		b.WriteString(fmt.Sprintf("%s},\n", tabs))

	default:
		// Dynamic values cannot live inside collection elements, so fall back to a
		// string there; use DynamicAttribute elsewhere.
		if inCollection {
			b.WriteString(fmt.Sprintf("%s%q: schema.StringAttribute{\n", tabs, tfName))
			writeAttributeFlags(b, prop, computed, tabs)
			b.WriteString(fmt.Sprintf("%s},\n", tabs))
		} else {
			b.WriteString(fmt.Sprintf("%s%q: schema.DynamicAttribute{\n", tabs, tfName))
			writeAttributeFlags(b, prop, computed, tabs)
			b.WriteString(fmt.Sprintf("%s},\n", tabs))
		}
	}
}

// emitPlanModifiers writes state-reuse and replacement plan modifiers.
func emitPlanModifiers(b *strings.Builder, prop *typegraph.Property, computed bool, tabs string) {
	// State reuse keeps Optional+Computed/read-only values stable; customizers can
	// make null prior state unknown for Azure-populated values. Members of a
	// mutual-exclusion / choice constraint opt out (SuppressStateReuse) so an omitted
	// side plans as unknown and the server re-owns it, instead of pinning stale state.
	if len(prop.VariantSiblings) > 0 {
		// A discriminated variant block: an unselected variant reuses prior state
		// but clears when a sibling variant is selected (see nativeschema
		// .DiscriminatedVariant). This replaces the plain UseStateForUnknown, whose
		// omission (SuppressStateReuse) left the unselected variant perpetually
		// planning as "(known after apply)".
		b.WriteString(fmt.Sprintf("%s\tPlanModifiers: []planmodifier.Object{\n", tabs))
		b.WriteString(fmt.Sprintf("%s\t\tnativeschema.DiscriminatedVariant(", tabs))
		for i, sib := range prop.VariantSiblings {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(fmt.Sprintf("%q", sib))
		}
		b.WriteString("),\n")
		b.WriteString(fmt.Sprintf("%s\t},\n", tabs))
		return
	}
	useState := !prop.Flags.IsRequired() && prop.DefaultValue == "" && !prop.DefaultEmptyList && !prop.SuppressStateReuse
	forceNew := prop.ForceNew && !computed
	location := usesLocationPlanModifier(prop, computed)
	if !useState && !forceNew && !location {
		return
	}
	pkg, typ := planModifierFor(prop)
	if pkg == "" {
		return // type has no plan-modifier package (e.g. dynamic)
	}
	b.WriteString(fmt.Sprintf("%s\tPlanModifiers: []planmodifier.%s{\n", tabs, typ))
	if location {
		b.WriteString(fmt.Sprintf("%s\t\tnativeschema.UseStateForEquivalentLocation(),\n", tabs))
	}
	if useState {
		stateMod := "UseStateForUnknown"
		if prop.NonNullStateForUnknown {
			stateMod = "UseNonNullStateForUnknown"
		}
		b.WriteString(fmt.Sprintf("%s\t\t%s.%s(),\n", tabs, pkg, stateMod))
	}
	if forceNew {
		b.WriteString(fmt.Sprintf("%s\t\t%s.RequiresReplace(),\n", tabs, pkg))
	}
	b.WriteString(fmt.Sprintf("%s\t},\n", tabs))
}

func usesLocationPlanModifier(prop *typegraph.Property, computed bool) bool {
	return !computed && prop.Type != nil && prop.Type.Kind == typegraph.KindString && isLocationFieldName(prop.Name)
}

// isLocationFieldName reports whether an ARM property carries an Azure region name
// (case/space-insensitive, e.g. "eastus2" vs "East US 2"). Both the top-level
// "location" and the nested "locationName" (Cosmos geo-replication, and similar
// geo structs) are regions Azure echoes in a normalized display form, so both need
// equivalent-location semantics to avoid perpetual post-apply drift.
func isLocationFieldName(name string) bool {
	return name == "location" || name == "locationName"
}

// planModifierFor returns the type-specific plan-modifier package and framework type.
func planModifierFor(prop *typegraph.Property) (pkg, typ string) {
	switch {
	case prop.Type.Kind == typegraph.KindString, prop.Type.IsEnum(), prop.Type.Kind == typegraph.KindUnion:
		return "stringplanmodifier", "String"
	case prop.Type.Kind == typegraph.KindBool:
		return "boolplanmodifier", "Bool"
	case prop.Type.Kind == typegraph.KindInt:
		return "int64planmodifier", "Int64"
	case prop.Type.Kind == typegraph.KindObject, prop.Type.Kind == typegraph.KindDiscriminated:
		return "objectplanmodifier", "Object"
	case prop.Type.Kind == typegraph.KindArray:
		return "listplanmodifier", "List"
	case prop.Type.Kind == typegraph.KindMap:
		return "mapplanmodifier", "Map"
	}
	return "", ""
}

func isManagedServiceIdentityProperty(prop *typegraph.Property) bool {
	if prop == nil || prop.Name != "identity" || prop.Type == nil || prop.Type.Kind != typegraph.KindObject {
		return false
	}
	props := prop.Type.Properties
	if props == nil {
		return false
	}
	for _, name := range []string{"principalId", "tenantId", "type", "userAssignedIdentities"} {
		if _, ok := props[name]; !ok {
			return false
		}
	}
	return true
}

func identityTypeRequired(prop *typegraph.Property) bool {
	if !isManagedServiceIdentityProperty(prop) {
		return false
	}
	return prop.Type.Properties["type"].Flags.IsRequired()
}

// writeAttributeFlags writes Description, Required/Optional/Computed, defaults and sensitivity.
func writeAttributeFlags(b *strings.Builder, prop *typegraph.Property, computed bool, tabs string) {
	if prop.Description != "" {
		desc := strings.ReplaceAll(prop.Description, `"`, `\"`)
		if len(desc) > 200 {
			desc = desc[:200] + "..."
		}
		b.WriteString(fmt.Sprintf("%s\tDescription: %q,\n", tabs, desc))
	}
	if prop.Flags.IsRequired() {
		b.WriteString(fmt.Sprintf("%s\tRequired: true,\n", tabs))
	} else if computed {
		b.WriteString(fmt.Sprintf("%s\tComputed: true,\n", tabs))
	} else if prop.DefaultValue != "" {
		// Framework defaults must be Optional+Computed.
		b.WriteString(fmt.Sprintf("%s\tOptional: true,\n", tabs))
		b.WriteString(fmt.Sprintf("%s\tComputed: true,\n", tabs))
		emitDefault(b, prop, tabs)
	} else {
		b.WriteString(fmt.Sprintf("%s\tOptional: true,\n", tabs))
		b.WriteString(fmt.Sprintf("%s\tComputed: true,\n", tabs))
	}
	if prop.Sensitive {
		b.WriteString(fmt.Sprintf("%s\tSensitive: true,\n", tabs))
	}
}

// listElementType returns the Terraform element type for primitive arrays.
func listElementType(elem *typegraph.Type) string {
	if elem != nil {
		switch elem.Kind {
		case typegraph.KindBool:
			return "types.BoolType"
		case typegraph.KindInt:
			return "types.Int64Type"
		}
	}
	return "types.StringType"
}

// attrTypeLiteral renders the Go attr.Type literal for a typegraph type, used to
// type an empty-list schema Default so its element type matches the emitted
// NestedObject/ElementType exactly. It mirrors emitAttribute's per-kind schema-type
// choices for attributes nested inside a collection (dynamic degrades to string).
func attrTypeLiteral(typ *typegraph.Type) string {
	if typ == nil {
		return "types.StringType"
	}
	switch {
	case typ.Kind == typegraph.KindString, typ.IsEnum(), typ.Kind == typegraph.KindUnion:
		return "types.StringType"
	case typ.Kind == typegraph.KindBool:
		return "types.BoolType"
	case typ.Kind == typegraph.KindInt:
		return "types.Int64Type"
	case typ.Kind == typegraph.KindObject:
		names := make([]string, 0, len(typ.Properties))
		for armName, prop := range typ.Properties {
			if prop.Flags.IsSystemManaged() {
				continue
			}
			names = append(names, armName)
		}
		sort.Strings(names)
		var b strings.Builder
		b.WriteString("types.ObjectType{AttrTypes: map[string]attr.Type{")
		for i, armName := range names {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(fmt.Sprintf("%q: %s", naming.CamelToSnake(armName), propAttrTypeLiteral(typ.Properties[armName])))
		}
		b.WriteString("}}")
		return b.String()
	case typ.Kind == typegraph.KindDiscriminated:
		// Object shape: base properties plus one nested object per variant, matching
		// the emitted SingleNestedAttribute layout.
		var b strings.Builder
		b.WriteString("types.ObjectType{AttrTypes: map[string]attr.Type{")
		first := true
		writeEntry := func(snake, lit string) {
			if !first {
				b.WriteString(", ")
			}
			first = false
			b.WriteString(fmt.Sprintf("%q: %s", snake, lit))
		}
		baseNames := make([]string, 0, len(typ.Properties))
		for armName, prop := range typ.Properties {
			if prop.Flags.IsSystemManaged() {
				continue
			}
			baseNames = append(baseNames, armName)
		}
		sort.Strings(baseNames)
		for _, armName := range baseNames {
			writeEntry(naming.CamelToSnake(armName), propAttrTypeLiteral(typ.Properties[armName]))
		}
		for _, value := range sortedVariantValues(typ) {
			writeEntry(naming.CamelToSnake(value), attrTypeLiteral(typ.Variants[value]))
		}
		b.WriteString("}}")
		return b.String()
	case typ.Kind == typegraph.KindArray:
		return fmt.Sprintf("types.ListType{ElemType: %s}", attrTypeLiteral(typ.ElementType))
	case typ.Kind == typegraph.KindMap:
		return fmt.Sprintf("types.MapType{ElemType: %s}", attrTypeLiteral(typ.ElementType))
	}
	return "types.StringType"
}

// propAttrTypeLiteral renders the attr.Type for a property, honouring UseSet (a
// primitive array emitted as a SetAttribute has a SetType, not a ListType).
func propAttrTypeLiteral(prop *typegraph.Property) string {
	if prop.UseSet && prop.Type != nil && prop.Type.Kind == typegraph.KindArray &&
		(prop.Type.ElementType == nil || prop.Type.ElementType.Kind != typegraph.KindObject) {
		return fmt.Sprintf("types.SetType{ElemType: %s}", attrTypeLiteral(prop.Type.ElementType))
	}
	return attrTypeLiteral(prop.Type)
}

// emitDefault writes the generated default for supported scalar types.
func emitDefault(b *strings.Builder, prop *typegraph.Property, tabs string) {
	switch prop.Type.Kind {
	case typegraph.KindBool:
		b.WriteString(fmt.Sprintf("%s\tDefault: booldefault.StaticBool(%s),\n", tabs, prop.DefaultValue))
	case typegraph.KindString:
		b.WriteString(fmt.Sprintf("%s\tDefault: stringdefault.StaticString(%q),\n", tabs, prop.DefaultValue))
	case typegraph.KindInt:
		b.WriteString(fmt.Sprintf("%s\tDefault: int64default.StaticInt64(%s),\n", tabs, prop.DefaultValue))
	default:
		if prop.Type.IsEnum() {
			b.WriteString(fmt.Sprintf("%s\tDefault: stringdefault.StaticString(%q),\n", tabs, prop.DefaultValue))
		} else {
			// Unsupported default type: leave it computed.
			b.WriteString(fmt.Sprintf("%s\tComputed: true,\n", tabs))
		}
	}
}

// emitDescriptionStringValidators writes string validators from descriptions/azwise.
func emitDescriptionStringValidators(b *strings.Builder, prop *typegraph.Property, tabs string) {
	emitStringValidators(b, prop.Validators, tabs)
}

// stringValidatorItems builds the individual validator.String expressions for a
// property's validators. It is shared by emitStringValidators (which wraps them in
// a []validator.String block) and emitListElementStringValidators (which wraps them
// in listvalidator.ValueStringsAre for a primitive string list). Indentation is
// approximate; the emitted file is gofmt-normalized before it is written.
func stringValidatorItems(validators []typegraph.DescriptionValidator, tabs string) []string {
	var items []string
	for _, v := range validators {
		switch v.Kind {
		case typegraph.ValidatorArmResourceID:
			items = append(items, fmt.Sprintf(
				"%s\t\tstringvalidator.RegexMatches(\n%s\t\t\tregexp.MustCompile(`^/subscriptions/[^/]+/resourceGroups/[^/]+/providers/`),\n%s\t\t\t%q,\n%s\t\t)",
				tabs, tabs, tabs, v.Message, tabs))
		case typegraph.ValidatorRegex:
			if v.Pattern != "" {
				items = append(items, fmt.Sprintf(
					"%s\t\tstringvalidator.RegexMatches(\n%s\t\t\tregexp.MustCompile(`%s`),\n%s\t\t\t%q,\n%s\t\t)",
					tabs, tabs, v.Pattern, tabs, v.Message, tabs))
			}
		case typegraph.ValidatorStringOneOf:
			if len(v.Allowed) > 0 {
				items = append(items, oneOfItem("OneOf", v.Allowed, tabs))
			}
		case typegraph.ValidatorStringOneOfCaseInsensitive:
			if len(v.Allowed) > 0 {
				items = append(items, oneOfItem("OneOfCaseInsensitive", v.Allowed, tabs))
			}
		case typegraph.ValidatorStringLength:
			switch {
			case v.Min != nil && v.Max != nil:
				items = append(items, fmt.Sprintf("%s\t\tstringvalidator.LengthBetween(%d, %d)", tabs, *v.Min, *v.Max))
			case v.Min != nil:
				items = append(items, fmt.Sprintf("%s\t\tstringvalidator.LengthAtLeast(%d)", tabs, *v.Min))
			case v.Max != nil:
				items = append(items, fmt.Sprintf("%s\t\tstringvalidator.LengthAtMost(%d)", tabs, *v.Max))
			}
		case typegraph.ValidatorFunc:
			if v.Func != nil {
				items = append(items, fmt.Sprintf("%s\t\t%s", tabs, validatorCall(v.Func)))
			}
		}
	}
	return items
}

// oneOfItem renders a stringvalidator.OneOf / OneOfCaseInsensitive expression.
func oneOfItem(ctor string, allowed []string, tabs string) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("%s\t\tstringvalidator.%s(\n", tabs, ctor))
	for _, av := range allowed {
		sb.WriteString(fmt.Sprintf("%s\t\t\t%q,\n", tabs, av))
	}
	sb.WriteString(fmt.Sprintf("%s\t\t)", tabs))
	return sb.String()
}

// emitStringValidators writes a String validator block.
func emitStringValidators(b *strings.Builder, validators []typegraph.DescriptionValidator, tabs string) {
	items := stringValidatorItems(validators, tabs)
	if len(items) == 0 {
		return
	}
	b.WriteString(fmt.Sprintf("%s\tValidators: []validator.String{\n", tabs))
	for _, item := range items {
		b.WriteString(item + ",\n")
	}
	b.WriteString(fmt.Sprintf("%s\t},\n", tabs))
}

// emitListValidators writes a single Validators: []validator.List{} block for a
// list attribute. It emits list-size validators (listvalidator.SizeBetween when both
// bounds are set, else SizeAtLeast / SizeAtMost — e.g. SizeAtLeast(1) rejects an
// empty list, SizeBetween(1, 2) also caps length) and, when elementValidators is true (a
// settable primitive string list), the property's string validators applied to
// every element via listvalidator.ValueStringsAre (e.g. case-insensitive key-vault
// permission enums). Emits nothing when neither applies.
func emitListValidators(b *strings.Builder, prop *typegraph.Property, tabs string, elementValidators bool) {
	sizeItems := listSizeValidatorItems(prop.Validators)
	var elemItems []string
	if elementValidators {
		elemItems = stringValidatorItems(prop.Validators, tabs)
	}
	if len(sizeItems) == 0 && len(elemItems) == 0 {
		return
	}
	b.WriteString(fmt.Sprintf("%s\tValidators: []validator.List{\n", tabs))
	for _, item := range sizeItems {
		b.WriteString(fmt.Sprintf("%s\t\t%s,\n", tabs, item))
	}
	if len(elemItems) > 0 {
		b.WriteString(fmt.Sprintf("%s\t\tlistvalidator.ValueStringsAre(\n", tabs))
		for _, item := range elemItems {
			b.WriteString(item + ",\n")
		}
		b.WriteString(fmt.Sprintf("%s\t\t),\n", tabs))
	}
	b.WriteString(fmt.Sprintf("%s\t},\n", tabs))
}

// listSizeValidatorItems renders a property's list-length validators: a combined
// listvalidator.SizeBetween(min, max) when both bounds are present, otherwise the
// single-sided listvalidator.SizeAtLeast(min) / SizeAtMost(max).
func listSizeValidatorItems(validators []typegraph.DescriptionValidator) []string {
	var lo, hi *int64
	for _, v := range validators {
		switch {
		case v.Kind == typegraph.ValidatorListSizeAtLeast && v.Min != nil:
			lo = v.Min
		case v.Kind == typegraph.ValidatorListSizeAtMost && v.Max != nil:
			hi = v.Max
		}
	}
	switch {
	case lo != nil && hi != nil:
		return []string{fmt.Sprintf("listvalidator.SizeBetween(%d, %d)", *lo, *hi)}
	case lo != nil:
		return []string{fmt.Sprintf("listvalidator.SizeAtLeast(%d)", *lo)}
	case hi != nil:
		return []string{fmt.Sprintf("listvalidator.SizeAtMost(%d)", *hi)}
	}
	return nil
}

// emitEnvelope writes synthetic name/parent/id attrs outside the bicep body.
func emitEnvelope(b *strings.Builder, env typegraph.Envelope, tabs string) {
	emitEnvelopeStringAttr(b, env.Name, tabs)
	emitEnvelopeStringAttr(b, env.Parent, tabs)
	emitEnvelopeIDAttr(b, tabs)
}

func emitEnvelopeIDAttr(b *strings.Builder, tabs string) {
	// id is uniform and server-assigned; reuse it across plans.
	b.WriteString(fmt.Sprintf("%s%q: schema.StringAttribute{\n", tabs, "id"))
	b.WriteString(fmt.Sprintf("%s\tComputed: true,\n", tabs))
	b.WriteString(fmt.Sprintf("%s\tPlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},\n", tabs))
	b.WriteString(fmt.Sprintf("%s\tMarkdownDescription: %q,\n", tabs, "The ID of the Azure resource."))
	b.WriteString(fmt.Sprintf("%s},\n", tabs))
}

// emitEnvelopeStringAttr writes a required, replacing envelope string attr.
func emitEnvelopeStringAttr(b *strings.Builder, a typegraph.EnvelopeAttr, tabs string) {
	b.WriteString(fmt.Sprintf("%s%q: schema.StringAttribute{\n", tabs, a.Name))
	b.WriteString(fmt.Sprintf("%s\tRequired: true,\n", tabs))
	b.WriteString(fmt.Sprintf("%s\tPlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},\n", tabs))
	emitStringValidators(b, a.Validators, tabs)
	b.WriteString(fmt.Sprintf("%s\tMarkdownDescription: %q,\n", tabs, a.Description))
	b.WriteString(fmt.Sprintf("%s},\n", tabs))
}

// emitMetaAttr writes a synthetic behavior-only Optional bool attribute (e.g.
// purge_on_destroy). It is not part of the bicep body, carries no default and is
// Optional-only so it stays null when unset and never drifts on read/import; a
// runtime hook reads it from state to drive provider-side behavior.
func emitMetaAttr(b *strings.Builder, m typegraph.MetaAttr, tabs string) {
	b.WriteString(fmt.Sprintf("%s%q: schema.BoolAttribute{\n", tabs, m.Name))
	b.WriteString(fmt.Sprintf("%s\tOptional: true,\n", tabs))
	b.WriteString(fmt.Sprintf("%s\tMarkdownDescription: %q,\n", tabs, m.Description))
	b.WriteString(fmt.Sprintf("%s},\n", tabs))
}

// emitDescriptionInt64Validators writes int64 range validators.
func emitDescriptionInt64Validators(b *strings.Builder, prop *typegraph.Property, tabs string) {
	if len(prop.Validators) == 0 {
		return
	}

	var items []string
	for _, v := range prop.Validators {
		if v.Kind != typegraph.ValidatorIntRange {
			continue
		}
		if v.Min != nil && v.Max != nil {
			items = append(items, fmt.Sprintf(
				"%s\t\tint64validator.Between(%d, %d)", tabs, *v.Min, *v.Max))
		} else if v.Min != nil {
			items = append(items, fmt.Sprintf(
				"%s\t\tint64validator.AtLeast(%d)", tabs, *v.Min))
		} else if v.Max != nil {
			items = append(items, fmt.Sprintf(
				"%s\t\tint64validator.AtMost(%d)", tabs, *v.Max))
		}
	}

	if len(items) > 0 {
		b.WriteString(fmt.Sprintf("%s\tValidators: []validator.Int64{\n", tabs))
		for _, item := range items {
			b.WriteString(item + ",\n")
		}
		b.WriteString(fmt.Sprintf("%s\t},\n", tabs))
	}
}

// toExportedGoName converts azapi_storage_account to AzapiStorageAccount.
func toExportedGoName(tfName string) string {
	parts := strings.Split(tfName, "_")
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return b.String()
}

// renderDuration renders a time.Duration as a Go literal for the generated
// descriptor. Timeout values are whole minutes in practice; seconds and a raw
// nanosecond fallback keep the output valid for any value.
func renderDuration(d time.Duration) string {
	switch {
	case d%time.Minute == 0:
		return fmt.Sprintf("%d * time.Minute", d/time.Minute)
	case d%time.Second == 0:
		return fmt.Sprintf("%d * time.Second", d/time.Second)
	default:
		return fmt.Sprintf("%d", int64(d))
	}
}
