// Code generated by azapin; DO NOT EDIT.
package authorization

import (
	"time"

	nativeschema "github.com/Azure/terraform-provider-azapi/internal/native/schema"
	"github.com/Azure/terraform-provider-azapi/internal/native/services"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
)

// AzapiRoleAssignmentSchema returns the Terraform resource schema for Microsoft.Authorization/roleAssignments@2022-04-01.
func AzapiRoleAssignmentSchema() schema.Schema {
	return schema.Schema{
		Description: "Manages a Microsoft.Authorization/roleAssignments resource. [azapin:Microsoft.Authorization/roleAssignments@2022-04-01]",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Validators: []validator.String{
					nativeschema.UUID(),
				},
				MarkdownDescription: "Specifies the name of the Azure resource.",
			},
			"scope_id": schema.StringAttribute{
				Required:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
				MarkdownDescription: "The scope ID where this role assignment applies.",
			},
			"properties": schema.SingleNestedAttribute{
				Description: "Role assignment properties.",
				Required:    true,
				Attributes: map[string]schema.Attribute{
					"condition": schema.StringAttribute{
						Description: "The conditions on the role assignment. This limits the resources it can be assigned to. e.g.: @Resource[Microsoft.Storage/storageAccounts/blobServices/containers:ContainerName] StringEqualsIgnoreCase ...",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{
							stringvalidator.LengthAtLeast(1),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
							stringplanmodifier.RequiresReplace(),
						},
					},
					"condition_version": schema.StringAttribute{
						Description: "Version of the condition. Currently the only accepted value is '2.0'",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"1.0",
								"2.0",
							),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
							stringplanmodifier.RequiresReplace(),
						},
					},
					"created_by": schema.StringAttribute{
						Description: "Id of the user who created the assignment",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"created_on": schema.StringAttribute{
						Description: "Time it was created",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"delegated_managed_identity_resource_id": schema.StringAttribute{
						Description: "Id of the delegated managed identity resource",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{
							nativeschema.AzureResourceID(),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
							stringplanmodifier.RequiresReplace(),
						},
					},
					"description": schema.StringAttribute{
						Description: "Description of role assignment",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{
							stringvalidator.LengthAtLeast(1),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
							stringplanmodifier.RequiresReplace(),
						},
					},
					"principal_id": schema.StringAttribute{
						Description: "The principal ID.",
						Required:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplace(),
						},
					},
					"principal_type": schema.StringAttribute{
						Description: "The principal type of the assigned principal ID.",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"User",
								"Group",
								"ServicePrincipal",
								"ForeignGroup",
								"Device",
							),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
							stringplanmodifier.RequiresReplace(),
						},
					},
					"role_definition_id": schema.StringAttribute{
						Description: "The role definition ID.",
						Required:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplace(),
						},
					},
					"scope": schema.StringAttribute{
						Description: "The role assignment scope.",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"updated_by": schema.StringAttribute{
						Description: "Id of the user who updated the assignment",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"updated_on": schema.StringAttribute{
						Description: "Time it was updated",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
				},
			},
			"id": schema.StringAttribute{
				Computed:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				MarkdownDescription: "The ID of the Azure resource.",
			},
		},
	}
}

// RoleAssignment describes azapi_role_assignment for registration and config builders.
var RoleAssignment = services.Descriptor{
	Name:           "azapi_role_assignment",
	ARMType:        "Microsoft.Authorization/roleAssignments",
	APIVersion:     "2022-04-01",
	Schema:         AzapiRoleAssignmentSchema,
	WritableScopes: 31,
	ParentAttr:     "scope_id",
	Timeouts: services.Timeouts{
		Create: 30 * time.Minute,
		Read:   5 * time.Minute,
		Delete: 30 * time.Minute,
	},
}

func init() { services.Register(RoleAssignment) }
