// Code generated by azapin; DO NOT EDIT.
package authorization

import (
	"time"

	nativeschema "github.com/Azure/terraform-provider-azapi/internal/native/schema"
	"github.com/Azure/terraform-provider-azapi/internal/native/services"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// AzapiRoleDefinitionSchemaSchema returns the Terraform resource schema for Microsoft.Authorization/roleDefinitions@2022-04-01.
func AzapiRoleDefinitionSchemaSchema() schema.Schema {
	return schema.Schema{
		Description: "Manages a Microsoft.Authorization/roleDefinitions resource. [azapin:Microsoft.Authorization/roleDefinitions@2022-04-01]",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Validators: []validator.String{
					nativeschema.UUID(),
				},
				MarkdownDescription: "Specifies the name of the Azure resource.",
			},
			"parent_id": schema.StringAttribute{
				Required:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
				MarkdownDescription: "The ID of the parent resource that contains this resource.",
			},
			"properties": schema.SingleNestedAttribute{
				Description: "Role definition properties.",
				Required:    true,
				Attributes: map[string]schema.Attribute{
					"assignable_scopes": schema.ListAttribute{
						Description: "Role definition assignable scopes.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.List{
							listplanmodifier.UseStateForUnknown(),
						},
						ElementType: types.StringType,
					},
					"created_by": schema.StringAttribute{
						Description: "Id of the user who created the assignment",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"created_on": schema.StringAttribute{
						Description: "Time it was created",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"description": schema.StringAttribute{
						Description: "The role definition description.",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{
							stringvalidator.LengthAtLeast(1),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"permissions": schema.ListNestedAttribute{
						Description: "Role definition permissions.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.List{
							listplanmodifier.UseStateForUnknown(),
						},
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"actions": schema.ListAttribute{
									Description: "Allowed actions.",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.List{
										listplanmodifier.UseStateForUnknown(),
									},
									ElementType: types.StringType,
								},
								"data_actions": schema.ListAttribute{
									Description: "Allowed Data actions.",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.List{
										listplanmodifier.UseStateForUnknown(),
									},
									ElementType: types.StringType,
								},
								"not_actions": schema.ListAttribute{
									Description: "Denied actions.",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.List{
										listplanmodifier.UseStateForUnknown(),
									},
									ElementType: types.StringType,
								},
								"not_data_actions": schema.ListAttribute{
									Description: "Denied Data actions.",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.List{
										listplanmodifier.UseStateForUnknown(),
									},
									ElementType: types.StringType,
								},
							},
						},
					},
					"role_name": schema.StringAttribute{
						Description: "The role name.",
						Required:    true,
						Validators: []validator.String{
							stringvalidator.LengthAtLeast(1),
						},
					},
					"type": schema.StringAttribute{
						Description: "The role type.",
						Optional:    true,
						Computed:    true,
						Default:     stringdefault.StaticString("CustomRole"),
					},
					"updated_by": schema.StringAttribute{
						Description: "Id of the user who updated the assignment",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"updated_on": schema.StringAttribute{
						Description: "Time it was updated",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
				},
			},
			"id": schema.StringAttribute{
				Computed:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				MarkdownDescription: "The ID of the Azure resource.",
			},
		},
	}
}

// AuthorizationRoleDefinition describes azapi_role_definition for registration and config builders.
var AuthorizationRoleDefinition = services.Descriptor{
	Name:           "azapi_role_definition",
	ARMType:        "Microsoft.Authorization/roleDefinitions",
	APIVersion:     "2022-04-01",
	Schema:         AzapiRoleDefinitionSchemaSchema,
	WritableScopes: 31,
	ParentAttr:     "parent_id",
	Timeouts: services.Timeouts{
		Create: 30 * time.Minute,
		Read:   5 * time.Minute,
		Update: 60 * time.Minute,
		Delete: 30 * time.Minute,
	},
}

func init() { services.Register(AuthorizationRoleDefinition) }
