// Code generated by azapin; DO NOT EDIT.
package documentdb

import (
	"time"

	"regexp"

	nativeschema "github.com/Azure/terraform-provider-azapi/internal/native/schema"
	"github.com/Azure/terraform-provider-azapi/internal/native/services"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/mapplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// AzapiCosmosdbAccountSchema returns the Terraform resource schema for Microsoft.DocumentDB/databaseAccounts@2026-03-15.
func AzapiCosmosdbAccountSchema() schema.Schema {
	return schema.Schema{
		Description: "Manages a Microsoft.DocumentDB/databaseAccounts resource. [azapin:Microsoft.DocumentDB/databaseAccounts@2026-03-15]",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Validators: []validator.String{
					stringvalidator.LengthBetween(3, 50),
					stringvalidator.RegexMatches(
						regexp.MustCompile(`^[-a-z0-9]{3,50}$`),
						"Cosmos DB account name must be 3-50 characters of lowercase letters, numbers, and hyphens",
					),
				},
				MarkdownDescription: "Specifies the name of the Azure resource.",
			},
			"resource_group_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Validators: []validator.String{
					stringvalidator.RegexMatches(
						regexp.MustCompile(`(?i)^/subscriptions/[^/]+/resourceGroups/[^/]+$`),
						"resource_group_id must be a resource group ID (/subscriptions/{id}/resourceGroups/{name})",
					),
				},
				MarkdownDescription: "The ID of the parent resource that contains this resource.",
			},
			"location": schema.StringAttribute{
				Description: "The location of the resource group to which the resource belongs.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					nativeschema.UseStateForEquivalentLocation(),
					stringplanmodifier.UseStateForUnknown(),
					stringplanmodifier.RequiresReplace(),
				},
			},
			"kind": schema.StringAttribute{
				Description: "Indicates the type of database account. This can only be set at database account creation.",
				Optional:    true,
				Computed:    true,
				Default:     stringdefault.StaticString("GlobalDocumentDB"),
				Validators: []validator.String{
					stringvalidator.OneOf(
						"GlobalDocumentDB",
						"MongoDB",
						"Parse",
					),
				},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"properties": schema.SingleNestedAttribute{
				Description: "Properties to create and update Azure Cosmos DB database accounts.",
				Required:    true,
				Attributes: map[string]schema.Attribute{
					"analytical_storage_configuration": schema.SingleNestedAttribute{
						Description: "Analytical storage specific properties.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
						Attributes: map[string]schema.Attribute{
							"schema_type": schema.StringAttribute{
								Description: "Describes the types of schema for analytical storage.",
								Required:    true,
								Validators: []validator.String{
									stringvalidator.OneOf(
										"WellDefined",
										"FullFidelity",
									),
								},
							},
						},
					},
					"api_properties": schema.SingleNestedAttribute{
						Description: "API specific properties. Currently, supported only for MongoDB API.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
						Attributes: map[string]schema.Attribute{
							"server_version": schema.StringAttribute{
								Description: "Describes the version of the MongoDB account.",
								Required:    true,
								Validators: []validator.String{
									stringvalidator.OneOf(
										"3.2",
										"3.6",
										"4.0",
										"4.2",
										"5.0",
										"6.0",
										"7.0",
									),
								},
							},
						},
					},
					"backup_policy": schema.SingleNestedAttribute{
						Description: "The object representing the policy for taking backups on an account.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
						Attributes: map[string]schema.Attribute{
							"migration_state": schema.SingleNestedAttribute{
								Description: "The object representing the state of the migration between the backup policies.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.Object{
									objectplanmodifier.UseStateForUnknown(),
								},
								Attributes: map[string]schema.Attribute{
									"start_time": schema.StringAttribute{
										Description: "Time at which the backup policy migration started (ISO-8601 format).",
										Optional:    true,
										Computed:    true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
										},
									},
									"status": schema.StringAttribute{
										Description: "Describes the status of migration between backup policy types.",
										Optional:    true,
										Computed:    true,
										Validators: []validator.String{
											stringvalidator.OneOf(
												"Invalid",
												"InProgress",
												"Completed",
												"Failed",
											),
										},
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
										},
									},
									"target_type": schema.StringAttribute{
										Description: "Describes the target backup policy type of the backup policy migration.",
										Optional:    true,
										Computed:    true,
										Validators: []validator.String{
											stringvalidator.OneOf(
												"Periodic",
												"Continuous",
											),
										},
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
										},
									},
								},
							},
							"continuous": schema.SingleNestedAttribute{
								Description: "Variant \\\"Continuous\\\" of the discriminated type.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.Object{
									nativeschema.DiscriminatedVariant("periodic"),
								},
								Attributes: map[string]schema.Attribute{
									"continuous_mode_properties": schema.SingleNestedAttribute{
										Description: "Configuration values for continuous mode backup",
										Required:    true,
										Attributes: map[string]schema.Attribute{
											"tier": schema.StringAttribute{
												Description: "Enum to indicate type of Continuos backup mode",
												Required:    true,
												Validators: []validator.String{
													stringvalidator.OneOf(
														"Continuous7Days",
														"Continuous30Days",
													),
												},
											},
										},
									},
								},
							},
							"periodic": schema.SingleNestedAttribute{
								Description: "Variant \\\"Periodic\\\" of the discriminated type.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.Object{
									nativeschema.DiscriminatedVariant("continuous"),
								},
								Attributes: map[string]schema.Attribute{
									"periodic_mode_properties": schema.SingleNestedAttribute{
										Description: "Configuration values for periodic mode backup",
										Required:    true,
										Attributes: map[string]schema.Attribute{
											"backup_interval_in_minutes": schema.Int64Attribute{
												Description: "An integer representing the interval in minutes between two backups",
												Optional:    true,
												Computed:    true,
												PlanModifiers: []planmodifier.Int64{
													int64planmodifier.UseStateForUnknown(),
												},
											},
											"backup_retention_interval_in_hours": schema.Int64Attribute{
												Description: "An integer representing the time (in hours) that each backup is retained",
												Optional:    true,
												Computed:    true,
												PlanModifiers: []planmodifier.Int64{
													int64planmodifier.UseStateForUnknown(),
												},
											},
											"backup_storage_redundancy": schema.StringAttribute{
												Description: "Enum to indicate type of backup residency",
												Optional:    true,
												Computed:    true,
												Validators: []validator.String{
													stringvalidator.OneOf(
														"Geo",
														"Local",
														"Zone",
													),
												},
												PlanModifiers: []planmodifier.String{
													stringplanmodifier.UseStateForUnknown(),
												},
											},
										},
									},
								},
							},
						},
					},
					"capabilities": schema.ListNestedAttribute{
						Description: "List of Cosmos DB capabilities for the account",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.List{
							listplanmodifier.UseStateForUnknown(),
						},
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"name": schema.StringAttribute{
									Description: "Name of the Cosmos DB capability. For example, \\\"name\\\": \\\"EnableCassandra\\\". Current values also include \\\"EnableTable\\\" and \\\"EnableGremlin\\\".",
									Required:    true,
								},
							},
						},
					},
					"capacity": schema.SingleNestedAttribute{
						Description: "The object that represents all properties related to capacity enforcement on an account.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
						Attributes: map[string]schema.Attribute{
							"total_throughput_limit": schema.Int64Attribute{
								Description: "The total throughput limit imposed on the account. A totalThroughputLimit of 2000 imposes a strict limit of max throughput that can be provisioned on that account to be 2000. A totalThroughputLimit of...",
								Required:    true,
								Validators: []validator.Int64{
									int64validator.AtLeast(-1),
								},
							},
						},
					},
					"connector_offer": schema.StringAttribute{
						Description: "The cassandra connector offer type for the Cosmos DB database C* account.",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"Small",
							),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"consistency_policy": schema.SingleNestedAttribute{
						Description: "The consistency policy for the Cosmos DB account.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
						Attributes: map[string]schema.Attribute{
							"default_consistency_level": schema.StringAttribute{
								Description: "The default consistency level and configuration settings of the Cosmos DB account.",
								Required:    true,
								Validators: []validator.String{
									stringvalidator.OneOf(
										"Eventual",
										"Session",
										"BoundedStaleness",
										"Strong",
										"ConsistentPrefix",
									),
								},
							},
							"max_interval_in_seconds": schema.Int64Attribute{
								Description: "When used with the Bounded Staleness consistency level, this value represents the time amount of staleness (in seconds) tolerated. Accepted range for this value is 5 - 86400. Required when defaultCons...",
								Optional:    true,
								Computed:    true,
								Default:     int64default.StaticInt64(5),
								Validators: []validator.Int64{
									int64validator.Between(5, 86400),
								},
							},
							"max_staleness_prefix": schema.Int64Attribute{
								Description: "When used with the Bounded Staleness consistency level, this value represents the number of stale requests tolerated. Accepted range for this value is 1 – 2,147,483,647. Required when defaultConsist...",
								Optional:    true,
								Computed:    true,
								Default:     int64default.StaticInt64(100),
								Validators: []validator.Int64{
									int64validator.Between(10, 2147483647),
								},
							},
						},
					},
					"cors": schema.ListNestedAttribute{
						Description: "The CORS policy for the Cosmos DB database account.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.List{
							listplanmodifier.UseStateForUnknown(),
						},
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"allowed_headers": schema.StringAttribute{
									Description: "The request headers that the origin domain may specify on the CORS request.",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"allowed_methods": schema.StringAttribute{
									Description: "The methods (HTTP request verbs) that the origin domain may use for a CORS request.",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"allowed_origins": schema.StringAttribute{
									Description: "The origin domains that are permitted to make a request against the service via CORS.",
									Required:    true,
								},
								"exposed_headers": schema.StringAttribute{
									Description: "The response headers that may be sent in the response to the CORS request and exposed by the browser to the request issuer.",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"max_age_in_seconds": schema.Int64Attribute{
									Description: "The maximum amount time that a browser should cache the preflight OPTIONS request.",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.Int64{
										int64planmodifier.UseStateForUnknown(),
									},
								},
							},
						},
					},
					"create_mode": schema.StringAttribute{
						Description: "Enum to indicate the mode of account creation.",
						Optional:    true,
						Computed:    true,
						Default:     stringdefault.StaticString("Default"),
						Validators: []validator.String{
							stringvalidator.OneOf(
								"Default",
								"Restore",
							),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplace(),
						},
					},
					"customer_managed_key_status": schema.StringAttribute{
						Description: "Indicates the status of the Customer Managed Key feature on the account. In case there are errors, the property provides troubleshooting guidance.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"database_account_offer_type": schema.StringAttribute{
						Description: "The offer type for the Cosmos DB database account.",
						Required:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"Standard",
							),
						},
					},
					"default_identity": schema.StringAttribute{
						Description: "The default identity for accessing key vault used in features like customer managed keys. The default identity needs to be explicitly set by the users. It can be \\\"FirstPartyIdentity\\\", \\\"SystemAssign...",
						Optional:    true,
						Computed:    true,
						Default:     stringdefault.StaticString("FirstPartyIdentity"),
					},
					"default_priority_level": schema.StringAttribute{
						Description: "Enum to indicate default Priority Level of request for Priority Based Execution.",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"High",
								"Low",
							),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"disable_key_based_metadata_write_access": schema.BoolAttribute{
						Description: "Disable write operations on metadata resources (databases, containers, throughput) via account keys",
						Optional:    true,
						Computed:    true,
						Default:     booldefault.StaticBool(false),
					},
					"disable_local_auth": schema.BoolAttribute{
						Description: "Opt-out of local authentication and ensure only MSI and AAD can be used exclusively for authentication.",
						Optional:    true,
						Computed:    true,
						Default:     booldefault.StaticBool(false),
					},
					"document_endpoint": schema.StringAttribute{
						Description: "The connection endpoint for the Cosmos DB database account.",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"enable_analytical_storage": schema.BoolAttribute{
						Description: "Flag to indicate whether to enable storage analytics.",
						Optional:    true,
						Computed:    true,
						Default:     booldefault.StaticBool(false),
					},
					"enable_automatic_failover": schema.BoolAttribute{
						Description: "Enables automatic failover of the write region in the rare event that the region is unavailable due to an outage. Automatic failover will result in a new write region for the account and is chosen bas...",
						Optional:    true,
						Computed:    true,
						Default:     booldefault.StaticBool(false),
					},
					"enable_burst_capacity": schema.BoolAttribute{
						Description: "Flag to indicate enabling/disabling of Burst Capacity Preview feature on the account",
						Optional:    true,
						Computed:    true,
						Default:     booldefault.StaticBool(false),
					},
					"enable_cassandra_connector": schema.BoolAttribute{
						Description: "Enables the cassandra connector on the Cosmos DB C* account",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Bool{
							boolplanmodifier.UseStateForUnknown(),
						},
					},
					"enable_free_tier": schema.BoolAttribute{
						Description: "Flag to indicate whether Free Tier is enabled.",
						Optional:    true,
						Computed:    true,
						Default:     booldefault.StaticBool(false),
						PlanModifiers: []planmodifier.Bool{
							boolplanmodifier.RequiresReplace(),
						},
					},
					"enable_multiple_write_locations": schema.BoolAttribute{
						Description: "Enables the account to write in multiple locations",
						Optional:    true,
						Computed:    true,
						Default:     booldefault.StaticBool(false),
					},
					"enable_partition_merge": schema.BoolAttribute{
						Description: "Flag to indicate enabling/disabling of Partition Merge feature on the account",
						Optional:    true,
						Computed:    true,
						Default:     booldefault.StaticBool(false),
					},
					"enable_per_region_per_partition_autoscale": schema.BoolAttribute{
						Description: "Flag to indicate enabling/disabling of Per-Region Per-partition autoscale Preview feature on the account",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Bool{
							boolplanmodifier.UseStateForUnknown(),
						},
					},
					"enable_priority_based_execution": schema.BoolAttribute{
						Description: "Flag to indicate enabling/disabling of Priority Based Execution Preview feature on the account",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Bool{
							boolplanmodifier.UseStateForUnknown(),
						},
					},
					"enforce_hierarchical_partition_key_id_last_level": schema.BoolAttribute{
						Description: "Flag to indicate enabling/disabling of hierarchical partition key ID last level enforcement on the account.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Bool{
							boolplanmodifier.UseStateForUnknown(),
						},
					},
					"failover_policies": schema.ListNestedAttribute{
						Description: "An array that contains the regions ordered by their failover priorities.",
						Computed:    true,
						PlanModifiers: []planmodifier.List{
							listplanmodifier.UseStateForUnknown(),
						},
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"failover_priority": schema.Int64Attribute{
									Description: "The failover priority of the region. A failover priority of 0 indicates a write region. The maximum value for a failover priority = (total number of regions - 1). Failover priority values must be uniq...",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.Int64{
										int64planmodifier.UseStateForUnknown(),
									},
								},
								"id": schema.StringAttribute{
									Description: "The unique identifier of the region in which the database account replicates to. Example: &lt;accountName&gt;-&lt;locationName&gt;.",
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"location_name": schema.StringAttribute{
									Description: "The name of the region in which the database account exists.",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										nativeschema.UseStateForEquivalentLocation(),
										stringplanmodifier.UseStateForUnknown(),
									},
								},
							},
						},
					},
					"instance_id": schema.StringAttribute{
						Description: "A unique identifier assigned to the database account",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"ip_rules": schema.ListNestedAttribute{
						Description: "List of IpRules.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.List{
							listplanmodifier.UseStateForUnknown(),
						},
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"ip_address_or_range": schema.StringAttribute{
									Description: "A single IPv4 address or a single IPv4 address range in CIDR format. Provided IPs must be well-formatted and cannot be contained in one of the following ranges: 10.0.0.0/8, 100.64.0.0/10, 172.16.0.0/1...",
									Required:    true,
								},
							},
						},
					},
					"is_virtual_network_filter_enabled": schema.BoolAttribute{
						Description: "Flag to indicate whether to enable/disable Virtual Network ACL rules.",
						Optional:    true,
						Computed:    true,
						Default:     booldefault.StaticBool(false),
					},
					"key_vault_key_uri": schema.StringAttribute{
						Description: "The URI of the key vault",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
							stringplanmodifier.RequiresReplace(),
						},
					},
					"key_vault_key_uri_version": schema.StringAttribute{
						Description: "The version of the Customer Managed Key currently being used by the account",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"keys_metadata": schema.SingleNestedAttribute{
						Description: "This property is ignored during the update/create operation, as the metadata is read-only. The object represents the metadata for the Account Keys of the Cosmos DB account.",
						Computed:    true,
						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
						Attributes: map[string]schema.Attribute{
							"primary_master_key": schema.SingleNestedAttribute{
								Description: "The metadata related to the Primary Read-Write Key for the given Cosmos DB database account.",
								Computed:    true,
								PlanModifiers: []planmodifier.Object{
									objectplanmodifier.UseStateForUnknown(),
								},
								Attributes: map[string]schema.Attribute{
									"generation_time": schema.StringAttribute{
										Description: "Generation time in UTC of the key in ISO-8601 format. If the value is missing from the object, it means that the last key regeneration was triggered before 2022-06-18.",
										Computed:    true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
										},
									},
								},
							},
							"primary_readonly_master_key": schema.SingleNestedAttribute{
								Description: "The metadata related to the Primary Read-Only Key for the given Cosmos DB database account.",
								Computed:    true,
								PlanModifiers: []planmodifier.Object{
									objectplanmodifier.UseStateForUnknown(),
								},
								Attributes: map[string]schema.Attribute{
									"generation_time": schema.StringAttribute{
										Description: "Generation time in UTC of the key in ISO-8601 format. If the value is missing from the object, it means that the last key regeneration was triggered before 2022-06-18.",
										Computed:    true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
										},
									},
								},
							},
							"secondary_master_key": schema.SingleNestedAttribute{
								Description: "The metadata related to the Secondary Read-Write Key for the given Cosmos DB database account.",
								Computed:    true,
								PlanModifiers: []planmodifier.Object{
									objectplanmodifier.UseStateForUnknown(),
								},
								Attributes: map[string]schema.Attribute{
									"generation_time": schema.StringAttribute{
										Description: "Generation time in UTC of the key in ISO-8601 format. If the value is missing from the object, it means that the last key regeneration was triggered before 2022-06-18.",
										Computed:    true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
										},
									},
								},
							},
							"secondary_readonly_master_key": schema.SingleNestedAttribute{
								Description: "The metadata related to the Secondary Read-Only Key for the given Cosmos DB database account.",
								Computed:    true,
								PlanModifiers: []planmodifier.Object{
									objectplanmodifier.UseStateForUnknown(),
								},
								Attributes: map[string]schema.Attribute{
									"generation_time": schema.StringAttribute{
										Description: "Generation time in UTC of the key in ISO-8601 format. If the value is missing from the object, it means that the last key regeneration was triggered before 2022-06-18.",
										Computed:    true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
										},
									},
								},
							},
						},
					},
					"locations": schema.ListNestedAttribute{
						Description: "An array that contains the georeplication locations enabled for the Cosmos DB account.",
						Required:    true,
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"document_endpoint": schema.StringAttribute{
									Description: "The connection endpoint for the specific region. Example: https://&lt;accountName&gt;-&lt;locationName&gt;.documents.azure.com:443/",
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"failover_priority": schema.Int64Attribute{
									Description: "The failover priority of the region. A failover priority of 0 indicates a write region. The maximum value for a failover priority = (total number of regions - 1). Failover priority values must be uniq...",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.Int64{
										int64planmodifier.UseStateForUnknown(),
									},
								},
								"id": schema.StringAttribute{
									Description: "The unique identifier of the region within the database account. Example: &lt;accountName&gt;-&lt;locationName&gt;.",
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"is_zone_redundant": schema.BoolAttribute{
									Description: "Flag to indicate whether or not this region is an AvailabilityZone region",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.Bool{
										boolplanmodifier.UseStateForUnknown(),
									},
								},
								"location_name": schema.StringAttribute{
									Description: "The name of the region.",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										nativeschema.UseStateForEquivalentLocation(),
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"provisioning_state": schema.StringAttribute{
									Description: "The provisioning state of the resource.",
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
							},
						},
					},
					"minimal_tls_version": schema.StringAttribute{
						Description: "Indicates the minimum allowed Tls version. The default is Tls 1.0, except for Cassandra and Mongo API's, which only work with Tls 1.2.",
						Optional:    true,
						Computed:    true,
						Default:     stringdefault.StaticString("Tls12"),
						Validators: []validator.String{
							stringvalidator.OneOf(
								"Tls",
								"Tls11",
								"Tls12",
							),
						},
					},
					"network_acl_bypass": schema.StringAttribute{
						Description: "Indicates what services are allowed to bypass firewall checks.",
						Optional:    true,
						Computed:    true,
						Default:     stringdefault.StaticString("None"),
						Validators: []validator.String{
							stringvalidator.OneOf(
								"None",
								"AzureServices",
							),
						},
					},
					"network_acl_bypass_resource_ids": schema.ListAttribute{
						Description: "An array that contains the Resource Ids for Network Acl Bypass for the Cosmos DB account.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.List{
							listplanmodifier.UseStateForUnknown(),
						},
						ElementType: types.StringType,
					},
					"private_endpoint_connections": schema.ListNestedAttribute{
						Description: "List of Private Endpoint Connections configured for the Cosmos DB account.",
						Computed:    true,
						PlanModifiers: []planmodifier.List{
							listplanmodifier.UseStateForUnknown(),
						},
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"id": schema.StringAttribute{
									Description: "Fully qualified resource ID for the resource. E.g. \\\"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}\\\"",
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"name": schema.StringAttribute{
									Description: "The name of the resource",
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"properties": schema.SingleNestedAttribute{
									Description: "Resource properties.",
									Required:    true,
									Attributes: map[string]schema.Attribute{
										"group_id": schema.StringAttribute{
											Description: "Group id of the private endpoint.",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
										},
										"private_endpoint": schema.SingleNestedAttribute{
											Description: "Private endpoint which the connection belongs to.",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.Object{
												objectplanmodifier.UseStateForUnknown(),
											},
											Attributes: map[string]schema.Attribute{
												"id": schema.StringAttribute{
													Description: "Resource id of the private endpoint.",
													Required:    true,
												},
											},
										},
										"private_link_service_connection_state": schema.SingleNestedAttribute{
											Description: "Connection State of the Private Endpoint Connection.",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.Object{
												objectplanmodifier.UseStateForUnknown(),
											},
											Attributes: map[string]schema.Attribute{
												"actions_required": schema.StringAttribute{
													Description: "Any action that is required beyond basic workflow (approve/ reject/ disconnect)",
													Computed:    true,
													PlanModifiers: []planmodifier.String{
														stringplanmodifier.UseStateForUnknown(),
													},
												},
												"description": schema.StringAttribute{
													Description: "The private link service connection description.",
													Optional:    true,
													Computed:    true,
													PlanModifiers: []planmodifier.String{
														stringplanmodifier.UseStateForUnknown(),
													},
												},
												"status": schema.StringAttribute{
													Description: "The private link service connection status.",
													Optional:    true,
													Computed:    true,
													PlanModifiers: []planmodifier.String{
														stringplanmodifier.UseStateForUnknown(),
													},
												},
											},
										},
										"provisioning_state": schema.StringAttribute{
											Description: "Provisioning state of the private endpoint.",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
										},
									},
								},
								"system_data": schema.SingleNestedAttribute{
									Description: "Azure Resource Manager metadata containing createdBy and modifiedBy information.",
									Computed:    true,
									PlanModifiers: []planmodifier.Object{
										objectplanmodifier.UseStateForUnknown(),
									},
									Attributes: map[string]schema.Attribute{
										"created_at": schema.StringAttribute{
											Description: "The timestamp of resource creation (UTC).",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
										},
										"created_by": schema.StringAttribute{
											Description: "The identity that created the resource.",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
										},
										"created_by_type": schema.StringAttribute{
											Description: "The type of identity that created the resource.",
											Optional:    true,
											Computed:    true,
											Validators: []validator.String{
												stringvalidator.OneOf(
													"User",
													"Application",
													"ManagedIdentity",
													"Key",
												),
											},
											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
										},
										"last_modified_at": schema.StringAttribute{
											Description: "The timestamp of resource last modification (UTC)",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
										},
										"last_modified_by": schema.StringAttribute{
											Description: "The identity that last modified the resource.",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
										},
										"last_modified_by_type": schema.StringAttribute{
											Description: "The type of identity that last modified the resource.",
											Optional:    true,
											Computed:    true,
											Validators: []validator.String{
												stringvalidator.OneOf(
													"User",
													"Application",
													"ManagedIdentity",
													"Key",
												),
											},
											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
										},
									},
								},
								"type": schema.StringAttribute{
									Description: "The type of the resource. E.g. \\\"Microsoft.Compute/virtualMachines\\\" or \\\"Microsoft.Storage/storageAccounts\\\"",
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
							},
						},
					},
					"provisioning_state": schema.StringAttribute{
						Description: "The provisioning state of the resource.",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"public_network_access": schema.StringAttribute{
						Description: "Whether requests from Public Network are allowed",
						Optional:    true,
						Computed:    true,
						Default:     stringdefault.StaticString("Enabled"),
						Validators: []validator.String{
							stringvalidator.OneOf(
								"Enabled",
								"Disabled",
								"SecuredByPerimeter",
							),
						},
					},
					"read_locations": schema.ListNestedAttribute{
						Description: "An array that contains of the read locations enabled for the Cosmos DB account.",
						Computed:    true,
						PlanModifiers: []planmodifier.List{
							listplanmodifier.UseStateForUnknown(),
						},
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"document_endpoint": schema.StringAttribute{
									Description: "The connection endpoint for the specific region. Example: https://&lt;accountName&gt;-&lt;locationName&gt;.documents.azure.com:443/",
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"failover_priority": schema.Int64Attribute{
									Description: "The failover priority of the region. A failover priority of 0 indicates a write region. The maximum value for a failover priority = (total number of regions - 1). Failover priority values must be uniq...",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.Int64{
										int64planmodifier.UseStateForUnknown(),
									},
								},
								"id": schema.StringAttribute{
									Description: "The unique identifier of the region within the database account. Example: &lt;accountName&gt;-&lt;locationName&gt;.",
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"is_zone_redundant": schema.BoolAttribute{
									Description: "Flag to indicate whether or not this region is an AvailabilityZone region",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.Bool{
										boolplanmodifier.UseStateForUnknown(),
									},
								},
								"location_name": schema.StringAttribute{
									Description: "The name of the region.",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										nativeschema.UseStateForEquivalentLocation(),
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"provisioning_state": schema.StringAttribute{
									Description: "The provisioning state of the resource.",
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
							},
						},
					},
					"restore_parameters": schema.SingleNestedAttribute{
						Description: "Parameters to indicate the information about the restore.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
							objectplanmodifier.RequiresReplace(),
						},
						Attributes: map[string]schema.Attribute{
							"databases_to_restore": schema.ListNestedAttribute{
								Description: "List of specific databases available for restore.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.List{
									listplanmodifier.UseStateForUnknown(),
								},
								NestedObject: schema.NestedAttributeObject{
									Attributes: map[string]schema.Attribute{
										"collection_names": schema.ListAttribute{
											Description: "The names of the collections available for restore.",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.List{
												listplanmodifier.UseStateForUnknown(),
											},
											ElementType: types.StringType,
										},
										"database_name": schema.StringAttribute{
											Description: "The name of the database available for restore.",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
										},
									},
								},
							},
							"gremlin_databases_to_restore": schema.ListNestedAttribute{
								Description: "List of specific gremlin databases available for restore.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.List{
									listplanmodifier.UseStateForUnknown(),
								},
								NestedObject: schema.NestedAttributeObject{
									Attributes: map[string]schema.Attribute{
										"database_name": schema.StringAttribute{
											Description: "The name of the gremlin database available for restore.",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
										},
										"graph_names": schema.ListAttribute{
											Description: "The names of the graphs available for restore.",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.List{
												listplanmodifier.UseStateForUnknown(),
											},
											ElementType: types.StringType,
										},
									},
								},
							},
							"restore_mode": schema.StringAttribute{
								Description: "Describes the mode of the restore.",
								Optional:    true,
								Computed:    true,
								Validators: []validator.String{
									stringvalidator.OneOf(
										"PointInTime",
									),
								},
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"restore_source": schema.StringAttribute{
								Description: "The id of the restorable database account from which the restore has to be initiated. For example: /subscriptions/{subscriptionId}/providers/Microsoft.DocumentDB/locations/{location}/restorableDatabas...",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"restore_timestamp_in_utc": schema.StringAttribute{
								Description: "Time to which the account has to be restored (ISO-8601 format).",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"restore_with_ttl_disabled": schema.BoolAttribute{
								Description: "Specifies whether the restored account will have Time-To-Live disabled upon the successful restore.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.Bool{
									boolplanmodifier.UseStateForUnknown(),
								},
							},
							"source_backup_location": schema.StringAttribute{
								Description: "The source backup location for restore.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"tables_to_restore": schema.ListAttribute{
								Description: "List of specific tables available for restore.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.List{
									listplanmodifier.UseStateForUnknown(),
								},
								ElementType: types.StringType,
							},
						},
					},
					"virtual_network_rules": schema.ListNestedAttribute{
						Description: "List of Virtual Network ACL rules configured for the Cosmos DB account.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.List{
							listplanmodifier.UseStateForUnknown(),
						},
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"id": schema.StringAttribute{
									Description: "Resource ID of a subnet, for example: /subscriptions/{subscriptionId}/resourceGroups/{groupName}/providers/Microsoft.Network/virtualNetworks/{virtualNetworkName}/subnets/{subnetName}.",
									Optional:    true,
									Computed:    true,
									Validators: []validator.String{
										stringvalidator.RegexMatches(
											regexp.MustCompile(`^/subscriptions/[^/]+/resourceGroups/[^/]+/providers/`),
											"must be a valid ARM resource ID",
										),
									},
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"ignore_missing_v_net_service_endpoint": schema.BoolAttribute{
									Description: "Create firewall rule before the virtual network has vnet service endpoint enabled.",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.Bool{
										boolplanmodifier.UseStateForUnknown(),
									},
								},
							},
						},
					},
					"write_locations": schema.ListNestedAttribute{
						Description: "An array that contains the write location for the Cosmos DB account.",
						Computed:    true,
						PlanModifiers: []planmodifier.List{
							listplanmodifier.UseStateForUnknown(),
						},
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"document_endpoint": schema.StringAttribute{
									Description: "The connection endpoint for the specific region. Example: https://&lt;accountName&gt;-&lt;locationName&gt;.documents.azure.com:443/",
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"failover_priority": schema.Int64Attribute{
									Description: "The failover priority of the region. A failover priority of 0 indicates a write region. The maximum value for a failover priority = (total number of regions - 1). Failover priority values must be uniq...",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.Int64{
										int64planmodifier.UseStateForUnknown(),
									},
								},
								"id": schema.StringAttribute{
									Description: "The unique identifier of the region within the database account. Example: &lt;accountName&gt;-&lt;locationName&gt;.",
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"is_zone_redundant": schema.BoolAttribute{
									Description: "Flag to indicate whether or not this region is an AvailabilityZone region",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.Bool{
										boolplanmodifier.UseStateForUnknown(),
									},
								},
								"location_name": schema.StringAttribute{
									Description: "The name of the region.",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										nativeschema.UseStateForEquivalentLocation(),
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"provisioning_state": schema.StringAttribute{
									Description: "The provisioning state of the resource.",
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
							},
						},
					},
				},
			},
			"system_data": schema.SingleNestedAttribute{
				Description: "Azure Resource Manager metadata containing createdBy and modifiedBy information.",
				Computed:    true,
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.UseStateForUnknown(),
				},
				Attributes: map[string]schema.Attribute{
					"created_at": schema.StringAttribute{
						Description: "The timestamp of resource creation (UTC).",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"created_by": schema.StringAttribute{
						Description: "The identity that created the resource.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"created_by_type": schema.StringAttribute{
						Description: "The type of identity that created the resource.",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"User",
								"Application",
								"ManagedIdentity",
								"Key",
							),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"last_modified_at": schema.StringAttribute{
						Description: "The timestamp of resource last modification (UTC)",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"last_modified_by": schema.StringAttribute{
						Description: "The identity that last modified the resource.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"last_modified_by_type": schema.StringAttribute{
						Description: "The type of identity that last modified the resource.",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"User",
								"Application",
								"ManagedIdentity",
								"Key",
							),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
				},
			},
			"identity": nativeschema.ManagedServiceIdentity(false, ""),
			"tags": schema.MapAttribute{
				Description: "Tags are a list of key-value pairs that describe the resource. These tags can be used in viewing and grouping this resource (across resource groups). A maximum of 15 tags can be provided for a resourc...",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.Map{
					mapplanmodifier.UseStateForUnknown(),
				},
				ElementType: types.StringType,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				MarkdownDescription: "The ID of the Azure resource.",
			},
		},
	}
}

// CosmosdbAccount describes azapi_cosmosdb_account for registration and config builders.
var CosmosdbAccount = services.Descriptor{
	Name:           "azapi_cosmosdb_account",
	ARMType:        "Microsoft.DocumentDB/databaseAccounts",
	APIVersion:     "2026-03-15",
	Schema:         AzapiCosmosdbAccountSchema,
	WritableScopes: 8,
	ParentAttr:     "resource_group_id",
	Relational: []services.RelationalConstraint{
		{Kind: services.AtMostOneOf, Paths: [][]string{{"properties", "backup_policy", "continuous"}, {"properties", "backup_policy", "periodic"}}, Message: "at most one variant of the discriminated block may be set"},
	},
	Timeouts: services.Timeouts{
		Create: 180 * time.Minute,
		Read:   5 * time.Minute,
		Update: 180 * time.Minute,
		Delete: 300 * time.Minute,
	},
}

func init() { services.Register(CosmosdbAccount) }
