// Code generated by azapin; DO NOT EDIT.
package kusto

import (
	"time"

	"regexp"

	nativeschema "github.com/Azure/terraform-provider-azapi/internal/native/schema"
	"github.com/Azure/terraform-provider-azapi/internal/native/schema/planmodifiers"
	"github.com/Azure/terraform-provider-azapi/internal/native/services"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/mapplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// AzapiKustoClusterSchema returns the Terraform resource schema for Microsoft.Kusto/clusters@2025-02-14.
func AzapiKustoClusterSchema() schema.Schema {
	return schema.Schema{
		Description: "Manages a Microsoft.Kusto/clusters resource. [azapin:Microsoft.Kusto/clusters@2025-02-14]",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Validators: []validator.String{
					stringvalidator.LengthBetween(4, 22),
					stringvalidator.RegexMatches(
						regexp.MustCompile(`^[a-z][a-z0-9-]+$`),
						"Kusto cluster name must be 4-22 characters, start with a lowercase letter, and contain only lowercase letters, numbers, and hyphens",
					),
				},
				MarkdownDescription: "Specifies the name of the Azure resource.",
			},
			"resource_group_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Validators: []validator.String{
					stringvalidator.RegexMatches(
						regexp.MustCompile(`(?i)^/subscriptions/[^/]+/resourceGroups/[^/]+$`),
						"resource_group_id must be a resource group ID (/subscriptions/{id}/resourceGroups/{name})",
					),
				},
				MarkdownDescription: "The ID of the parent resource that contains this resource.",
			},
			"location": schema.StringAttribute{
				Description: "The geo-location where the resource lives",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					planmodifiers.UseStateForEquivalentLocation(),
					stringplanmodifier.RequiresReplace(),
				},
			},
			"sku": schema.SingleNestedAttribute{
				Description: "The SKU of the cluster.",
				Required:    true,
				Attributes: map[string]schema.Attribute{
					"capacity": schema.Int64Attribute{
						Description: "The number of instances of the cluster.",
						Optional:    true,
						Computed:    true,
						Validators: []validator.Int64{
							int64validator.Between(1, 1000),
						},
						PlanModifiers: []planmodifier.Int64{
							int64planmodifier.UseStateForUnknown(),
						},
					},
					"name": schema.StringAttribute{
						Description: "SKU name.",
						Required:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"Dev(No SLA)_Standard_D11_v2",
								"Dev(No SLA)_Standard_E2a_v4",
								"Standard_D11_v2",
								"Standard_D12_v2",
								"Standard_D13_v2",
								"Standard_D14_v2",
								"Standard_D32d_v4",
								"Standard_D16d_v5",
								"Standard_D32d_v5",
								"Standard_DS13_v2+1TB_PS",
								"Standard_DS13_v2+2TB_PS",
								"Standard_DS14_v2+3TB_PS",
								"Standard_DS14_v2+4TB_PS",
								"Standard_L4s",
								"Standard_L8s",
								"Standard_L16s",
								"Standard_L8s_v2",
								"Standard_L16s_v2",
								"Standard_L8s_v3",
								"Standard_L16s_v3",
								"Standard_L32s_v3",
								"Standard_L8as_v3",
								"Standard_L16as_v3",
								"Standard_L32as_v3",
								"Standard_E64i_v3",
								"Standard_E80ids_v4",
								"Standard_E2a_v4",
								"Standard_E4a_v4",
								"Standard_E8a_v4",
								"Standard_E16a_v4",
								"Standard_E8as_v4+1TB_PS",
								"Standard_E8as_v4+2TB_PS",
								"Standard_E16as_v4+3TB_PS",
								"Standard_E16as_v4+4TB_PS",
								"Standard_E8as_v5+1TB_PS",
								"Standard_E8as_v5+2TB_PS",
								"Standard_E16as_v5+3TB_PS",
								"Standard_E16as_v5+4TB_PS",
								"Standard_E2ads_v5",
								"Standard_E4ads_v5",
								"Standard_E8ads_v5",
								"Standard_E16ads_v5",
								"Standard_EC8as_v5+1TB_PS",
								"Standard_EC8as_v5+2TB_PS",
								"Standard_EC16as_v5+3TB_PS",
								"Standard_EC16as_v5+4TB_PS",
								"Standard_EC8ads_v5",
								"Standard_EC16ads_v5",
								"Standard_E8s_v4+1TB_PS",
								"Standard_E8s_v4+2TB_PS",
								"Standard_E16s_v4+3TB_PS",
								"Standard_E16s_v4+4TB_PS",
								"Standard_E8s_v5+1TB_PS",
								"Standard_E8s_v5+2TB_PS",
								"Standard_E16s_v5+3TB_PS",
								"Standard_E16s_v5+4TB_PS",
								"Standard_E2d_v4",
								"Standard_E4d_v4",
								"Standard_E8d_v4",
								"Standard_E16d_v4",
								"Standard_E2d_v5",
								"Standard_E4d_v5",
								"Standard_E8d_v5",
								"Standard_E16d_v5",
							),
						},
					},
					"tier": schema.StringAttribute{
						Description: "SKU tier.",
						Required:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"Basic",
								"Standard",
							),
						},
					},
				},
			},
			"etag": schema.StringAttribute{
				Description: "\\\"If etag is provided in the response body, it may also be provided as a header per the normal etag convention.  Entity tags are used for comparing two or more entities from the same requested resourc...",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"properties": schema.SingleNestedAttribute{
				Description: "The cluster properties.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.UseStateForUnknown(),
				},
				Attributes: map[string]schema.Attribute{
					"accepted_audiences": schema.ListNestedAttribute{
						Description: "The cluster's accepted audiences.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.List{
							listplanmodifier.UseStateForUnknown(),
						},
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"value": schema.StringAttribute{
									Description: "GUID or valid URL representing an accepted audience.",
									Required:    true,
								},
							},
						},
					},
					"allowed_fqdn_list": schema.ListAttribute{
						Description: "List of allowed FQDNs(Fully Qualified Domain Name) for egress from Cluster.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.List{
							listplanmodifier.UseStateForUnknown(),
						},
						ElementType: types.StringType,
					},
					"allowed_ip_range_list": schema.ListAttribute{
						Description: "The list of ips in the format of CIDR allowed to connect to the cluster.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.List{
							listplanmodifier.UseStateForUnknown(),
						},
						ElementType: types.StringType,
					},
					"callout_policies": schema.ListNestedAttribute{
						Description: "List of callout policies for egress from Cluster.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.List{
							listplanmodifier.UseStateForUnknown(),
						},
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"callout_id": schema.StringAttribute{
									Description: "Unique identifier for the callout configuration.",
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"callout_type": schema.StringAttribute{
									Description: "Type of the callout service, specifying the kind of external resource or service being accessed.",
									Optional:    true,
									Computed:    true,
									Validators: []validator.String{
										stringvalidator.OneOf(
											"kusto",
											"sql",
											"cosmosdb",
											"external_data",
											"azure_digital_twins",
											"sandbox_artifacts",
											"webapi",
											"mysql",
											"postgresql",
											"genevametrics",
											"azure_openai",
										),
									},
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"callout_uri_regex": schema.StringAttribute{
									Description: "Regular expression or FQDN pattern for the callout URI.",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"outbound_access": schema.StringAttribute{
									Description: "Indicates whether outbound access is permitted for the specified URI pattern.",
									Optional:    true,
									Computed:    true,
									Validators: []validator.String{
										stringvalidator.OneOf(
											"Allow",
											"Deny",
										),
									},
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
							},
						},
					},
					"data_ingestion_uri": schema.StringAttribute{
						Description: "The cluster data ingestion URI.",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"enable_auto_stop": schema.BoolAttribute{
						Description: "A boolean value that indicates if the cluster could be automatically stopped (due to lack of data or no activity for many days).",
						Optional:    true,
						Computed:    true,
						Default:     booldefault.StaticBool(true),
					},
					"enable_disk_encryption": schema.BoolAttribute{
						Description: "A boolean value that indicates if the cluster's disks are encrypted.",
						Optional:    true,
						Computed:    true,
						Default:     booldefault.StaticBool(false),
					},
					"enable_double_encryption": schema.BoolAttribute{
						Description: "A boolean value that indicates if double encryption is enabled.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Bool{
							boolplanmodifier.UseStateForUnknown(),
							boolplanmodifier.RequiresReplace(),
						},
					},
					"enable_purge": schema.BoolAttribute{
						Description: "A boolean value that indicates if the purge operations are enabled.",
						Optional:    true,
						Computed:    true,
						Default:     booldefault.StaticBool(false),
					},
					"enable_streaming_ingest": schema.BoolAttribute{
						Description: "A boolean value that indicates if the streaming ingest is enabled.",
						Optional:    true,
						Computed:    true,
						Default:     booldefault.StaticBool(false),
					},
					"engine_type": schema.StringAttribute{
						Description: "The engine type",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"V2",
								"V3",
							),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"key_vault_properties": schema.SingleNestedAttribute{
						Description: "KeyVault properties for the cluster encryption.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
						Attributes: map[string]schema.Attribute{
							"federated_identity_client_id": schema.StringAttribute{
								Description: "The application (client) ID of the multi-tenant Microsoft Entra application. Used for cross-tenant customer-managed key scenarios where the encryption key is stored in a different tenant than the clus...",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"key_name": schema.StringAttribute{
								Description: "The name of the key vault key.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"key_vault_uri": schema.StringAttribute{
								Description: "The Uri of the key vault.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"key_version": schema.StringAttribute{
								Description: "The version of the key vault key.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"user_identity": schema.StringAttribute{
								Description: "The user assigned identity (ARM resource id) that has access to the key. The identity must have 'Get', 'Wrap Key', and 'Unwrap Key' permissions on the Key Vault key, or be assigned the 'Key Vault Cryp...",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
						},
					},
					"language_extensions": schema.SingleNestedAttribute{
						Description: "List of the cluster's language extensions.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
						Attributes: map[string]schema.Attribute{
							"next_link": schema.StringAttribute{
								Description: "The link to the next page of resources.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"value": schema.ListNestedAttribute{
								Description: "The list of language extensions.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.List{
									listplanmodifier.UseStateForUnknown(),
								},
								NestedObject: schema.NestedAttributeObject{
									Attributes: map[string]schema.Attribute{
										"language_extension_custom_image_name": schema.StringAttribute{
											Description: "The sandbox custom image name that should be enabled as the active language extension. Sandbox custom image is a cluster sub resource. When this property is set, LanguageExtensionImageName should be s...",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
										},
										"language_extension_image_name": schema.StringAttribute{
											Description: "The language extension image name.",
											Optional:    true,
											Computed:    true,
											Validators: []validator.String{
												stringvalidator.OneOf(
													"R",
													"Python3_6_5",
													"Python3_10_8",
													"Python3_10_8_DL",
													"PythonCustomImage",
													"Python3_11_7",
													"Python3_11_7_DL",
												),
											},
											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
										},
										"language_extension_name": schema.StringAttribute{
											Description: "The language extension name.",
											Optional:    true,
											Computed:    true,
											Validators: []validator.String{
												stringvalidator.OneOf(
													"PYTHON",
													"R",
												),
											},
											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
										},
									},
								},
							},
						},
					},
					"migration_cluster": schema.SingleNestedAttribute{
						Description: "Properties of the peer cluster involved in a migration to/from this cluster.",
						Computed:    true,
						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
						Attributes: map[string]schema.Attribute{
							"data_ingestion_uri": schema.StringAttribute{
								Description: "The public data ingestion URL of the cluster.",
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"id": schema.StringAttribute{
								Description: "The resource ID of the cluster.",
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"role": schema.StringAttribute{
								Description: "The role of the cluster in the migration process.",
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"uri": schema.StringAttribute{
								Description: "The public URL of the cluster.",
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
						},
					},
					"optimized_autoscale": schema.SingleNestedAttribute{
						Description: "Optimized auto scale definition.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
						Attributes: map[string]schema.Attribute{
							"is_enabled": schema.BoolAttribute{
								Description: "A boolean value that indicate if the optimized autoscale feature is enabled or not.",
								Required:    true,
							},
							"maximum": schema.Int64Attribute{
								Description: "Maximum allowed instances count.",
								Required:    true,
								Validators: []validator.Int64{
									int64validator.Between(0, 1000),
								},
							},
							"minimum": schema.Int64Attribute{
								Description: "Minimum allowed instances count.",
								Required:    true,
								Validators: []validator.Int64{
									int64validator.Between(0, 1000),
								},
							},
							"version": schema.Int64Attribute{
								Description: "The version of the template defined, for instance 1.",
								Required:    true,
							},
						},
					},
					"private_endpoint_connections": schema.ListNestedAttribute{
						Description: "A list of private endpoint connections.",
						Computed:    true,
						PlanModifiers: []planmodifier.List{
							listplanmodifier.UseStateForUnknown(),
						},
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"id": schema.StringAttribute{
									Description: "Fully qualified resource ID for the resource. Ex - /subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/{resourceProviderNamespace}/{resourceType}/{resourceName}",
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"name": schema.StringAttribute{
									Description: "The name of the resource",
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"properties": schema.SingleNestedAttribute{
									Description: "Resource properties.",
									Required:    true,
									Attributes: map[string]schema.Attribute{
										"group_id": schema.StringAttribute{
											Description: "Group id of the private endpoint.",
											Computed:    true,
											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
										},
										"private_endpoint": schema.SingleNestedAttribute{
											Description: "Private endpoint which the connection belongs to.",
											Computed:    true,
											PlanModifiers: []planmodifier.Object{
												objectplanmodifier.UseStateForUnknown(),
											},
											Attributes: map[string]schema.Attribute{
												"id": schema.StringAttribute{
													Description: "Resource id of the private endpoint.",
													Computed:    true,
													PlanModifiers: []planmodifier.String{
														stringplanmodifier.UseStateForUnknown(),
													},
												},
											},
										},
										"private_link_service_connection_state": schema.SingleNestedAttribute{
											Description: "Connection State of the Private Endpoint Connection.",
											Required:    true,
											Attributes: map[string]schema.Attribute{
												"actions_required": schema.StringAttribute{
													Description: "Any action that is required beyond basic workflow (approve/ reject/ disconnect)",
													Computed:    true,
													PlanModifiers: []planmodifier.String{
														stringplanmodifier.UseStateForUnknown(),
													},
												},
												"description": schema.StringAttribute{
													Description: "The private link service connection description.",
													Optional:    true,
													Computed:    true,
													PlanModifiers: []planmodifier.String{
														stringplanmodifier.UseStateForUnknown(),
													},
												},
												"status": schema.StringAttribute{
													Description: "The private link service connection status.",
													Optional:    true,
													Computed:    true,
													PlanModifiers: []planmodifier.String{
														stringplanmodifier.UseStateForUnknown(),
													},
												},
											},
										},
										"provisioning_state": schema.StringAttribute{
											Description: "Provisioning state of the private endpoint.",
											Computed:    true,
											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
										},
									},
								},
								"system_data": schema.SingleNestedAttribute{
									Description: "Azure Resource Manager metadata containing createdBy and modifiedBy information.",
									Computed:    true,
									PlanModifiers: []planmodifier.Object{
										objectplanmodifier.UseStateForUnknown(),
									},
									Attributes: map[string]schema.Attribute{
										"created_at": schema.StringAttribute{
											Description: "The timestamp of resource creation (UTC).",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
										},
										"created_by": schema.StringAttribute{
											Description: "The identity that created the resource.",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
										},
										"created_by_type": schema.StringAttribute{
											Description: "The type of identity that created the resource.",
											Optional:    true,
											Computed:    true,
											Validators: []validator.String{
												stringvalidator.OneOf(
													"User",
													"Application",
													"ManagedIdentity",
													"Key",
												),
											},
											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
										},
										"last_modified_at": schema.StringAttribute{
											Description: "The timestamp of resource last modification (UTC)",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
										},
										"last_modified_by": schema.StringAttribute{
											Description: "The identity that last modified the resource.",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
										},
										"last_modified_by_type": schema.StringAttribute{
											Description: "The type of identity that last modified the resource.",
											Optional:    true,
											Computed:    true,
											Validators: []validator.String{
												stringvalidator.OneOf(
													"User",
													"Application",
													"ManagedIdentity",
													"Key",
												),
											},
											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
										},
									},
								},
								"type": schema.StringAttribute{
									Description: "The type of the resource. E.g. \\\"Microsoft.Compute/virtualMachines\\\" or \\\"Microsoft.Storage/storageAccounts\\\"",
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
							},
						},
					},
					"provisioning_state": schema.StringAttribute{
						Description: "The provisioned state of the resource.",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"public_ip_type": schema.StringAttribute{
						Description: "Indicates what public IP type to create - IPv4 (default), or DualStack (both IPv4 and IPv6)",
						Optional:    true,
						Computed:    true,
						Default:     stringdefault.StaticString("IPv4"),
						Validators: []validator.String{
							stringvalidator.OneOf(
								"IPv4",
								"DualStack",
							),
						},
					},
					"public_network_access": schema.StringAttribute{
						Description: "Public network access to the cluster is enabled by default. When disabled, only private endpoint connection to the cluster is allowed",
						Optional:    true,
						Computed:    true,
						Default:     stringdefault.StaticString("Enabled"),
						Validators: []validator.String{
							stringvalidator.OneOf(
								"Enabled",
								"Disabled",
								"SecuredByPerimeter",
							),
						},
					},
					"restrict_outbound_network_access": schema.StringAttribute{
						Description: "Whether or not to restrict outbound network access.  Value is optional but if passed in, must be 'Enabled' or 'Disabled'",
						Optional:    true,
						Computed:    true,
						Default:     stringdefault.StaticString("Disabled"),
						Validators: []validator.String{
							stringvalidator.OneOf(
								"Enabled",
								"Disabled",
							),
						},
					},
					"state": schema.StringAttribute{
						Description: "The state of the resource.",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"state_reason": schema.StringAttribute{
						Description: "The reason for the cluster's current state.",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"trusted_external_tenants": schema.ListNestedAttribute{
						Description: "The cluster's external tenants.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.List{
							listplanmodifier.UseStateForUnknown(),
						},
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"value": schema.StringAttribute{
									Description: "GUID representing an external tenant.",
									Required:    true,
								},
							},
						},
					},
					"uri": schema.StringAttribute{
						Description: "The cluster URI.",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"virtual_cluster_graduation_properties": schema.StringAttribute{
						Description: "Virtual Cluster graduation properties",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"virtual_network_configuration": schema.SingleNestedAttribute{
						Description: "Virtual network definition.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
						Attributes: map[string]schema.Attribute{
							"data_management_public_ip_id": schema.StringAttribute{
								Description: "Data management's service public IP address resource id.",
								Required:    true,
							},
							"engine_public_ip_id": schema.StringAttribute{
								Description: "Engine service's public IP address resource id.",
								Required:    true,
							},
							"state": schema.StringAttribute{
								Description: "When enabled, the cluster is deployed into the configured subnet, when disabled it will be removed from the subnet.",
								Optional:    true,
								Computed:    true,
								Validators: []validator.String{
									stringvalidator.OneOf(
										"Enabled",
										"Disabled",
									),
								},
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"subnet_id": schema.StringAttribute{
								Description: "The subnet resource id.",
								Required:    true,
							},
						},
					},
					"zone_status": schema.StringAttribute{
						Description: "Indicates whether the cluster is zonal or non-zonal.",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
				},
			},
			"system_data": schema.SingleNestedAttribute{
				Description: "Azure Resource Manager metadata containing createdBy and modifiedBy information.",
				Computed:    true,
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.UseStateForUnknown(),
				},
				Attributes: map[string]schema.Attribute{
					"created_at": schema.StringAttribute{
						Description: "The timestamp of resource creation (UTC).",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"created_by": schema.StringAttribute{
						Description: "The identity that created the resource.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"created_by_type": schema.StringAttribute{
						Description: "The type of identity that created the resource.",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"User",
								"Application",
								"ManagedIdentity",
								"Key",
							),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"last_modified_at": schema.StringAttribute{
						Description: "The timestamp of resource last modification (UTC)",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"last_modified_by": schema.StringAttribute{
						Description: "The identity that last modified the resource.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"last_modified_by_type": schema.StringAttribute{
						Description: "The type of identity that last modified the resource.",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"User",
								"Application",
								"ManagedIdentity",
								"Key",
							),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
				},
			},
			"zones": schema.ListAttribute{
				Description: "The availability zones.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.List{
					listplanmodifier.UseStateForUnknown(),
					listplanmodifier.RequiresReplace(),
				},
				ElementType: types.StringType,
			},
			"identity": nativeschema.ManagedServiceIdentity(true, ""),
			"tags": schema.MapAttribute{
				Description: "Resource tags.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.Map{
					mapplanmodifier.UseStateForUnknown(),
				},
				ElementType: types.StringType,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				MarkdownDescription: "The ID of the Azure resource.",
			},
		},
	}
}

// KustoCluster describes azapi_kusto_cluster for registration and config builders.
var KustoCluster = services.Descriptor{
	Name:           "azapi_kusto_cluster",
	ARMType:        "Microsoft.Kusto/clusters",
	APIVersion:     "2025-02-14",
	Schema:         AzapiKustoClusterSchema,
	WritableScopes: 8,
	ParentAttr:     "resource_group_id",
	Timeouts: services.Timeouts{
		Create: 60 * time.Minute,
		Read:   5 * time.Minute,
		Update: 60 * time.Minute,
		Delete: 60 * time.Minute,
	},
}

func init() { services.Register(KustoCluster) }
