// Code generated by azapin; DO NOT EDIT.
package kusto

import (
	"regexp"

	nativeschema "github.com/Azure/terraform-provider-azapi/internal/native/schema"
	"github.com/Azure/terraform-provider-azapi/internal/native/services"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// AzapiKustoDatabaseSchema returns the Terraform resource schema for Microsoft.Kusto/clusters/databases@2025-02-14.
func AzapiKustoDatabaseSchema() schema.Schema {
	return schema.Schema{
		Description: "Manages a Microsoft.Kusto/clusters/databases resource. [azapin:Microsoft.Kusto/clusters/databases@2025-02-14]",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				Required:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.RequiresReplace()},
				MarkdownDescription: "Specifies the name of the Azure resource.",
			},
			"cluster_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Validators: []validator.String{
					stringvalidator.RegexMatches(
						regexp.MustCompile(`(?i)/providers/Microsoft\.Kusto/clusters/[^/]+$`),
						"cluster_id must be the ID of a Microsoft.Kusto/clusters resource",
					),
				},
				MarkdownDescription: "The ID of the parent resource that contains this resource.",
			},
			"location": schema.StringAttribute{
				Description: "Resource location.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					nativeschema.UseStateForEquivalentLocation(),
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"system_data": schema.SingleNestedAttribute{
				Description: "Azure Resource Manager metadata containing createdBy and modifiedBy information.",
				Computed:    true,
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.UseStateForUnknown(),
				},
				Attributes: map[string]schema.Attribute{
					"created_at": schema.StringAttribute{
						Description: "The timestamp of resource creation (UTC).",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"created_by": schema.StringAttribute{
						Description: "The identity that created the resource.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"created_by_type": schema.StringAttribute{
						Description: "The type of identity that created the resource.",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"User",
								"Application",
								"ManagedIdentity",
								"Key",
							),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"last_modified_at": schema.StringAttribute{
						Description: "The timestamp of resource last modification (UTC)",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"last_modified_by": schema.StringAttribute{
						Description: "The identity that last modified the resource.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"last_modified_by_type": schema.StringAttribute{
						Description: "The type of identity that last modified the resource.",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"User",
								"Application",
								"ManagedIdentity",
								"Key",
							),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
				},
			},
			"read_only_following": schema.SingleNestedAttribute{
				Description: "Variant \\\"ReadOnlyFollowing\\\" of the discriminated type.",
				Optional:    true,
				Computed:    true,
				Attributes: map[string]schema.Attribute{
					"properties": schema.SingleNestedAttribute{
						Description: "The database properties.",
						Required:    true,
						Attributes: map[string]schema.Attribute{
							"attached_database_configuration_name": schema.StringAttribute{
								Description: "The name of the attached database configuration cluster",
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"database_share_origin": schema.StringAttribute{
								Description: "The origin of the following setup.",
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"hot_cache_period": schema.StringAttribute{
								Description: "The time the data should be kept in cache for fast queries in TimeSpan.",
								Required:    true,
							},
							"leader_cluster_resource_id": schema.StringAttribute{
								Description: "The name of the leader cluster",
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"original_database_name": schema.StringAttribute{
								Description: "The original database name, before databaseNameOverride or databaseNamePrefix where applied.",
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"principals_modification_kind": schema.StringAttribute{
								Description: "The principals modification kind of the database",
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"provisioning_state": schema.StringAttribute{
								Description: "The provisioned state of the resource.",
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"soft_delete_period": schema.StringAttribute{
								Description: "The time the data should be kept before it stops being accessible to queries in TimeSpan.",
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"statistics": schema.SingleNestedAttribute{
								Description: "The statistics of the database.",
								Computed:    true,
								PlanModifiers: []planmodifier.Object{
									objectplanmodifier.UseStateForUnknown(),
								},
								Attributes: map[string]schema.Attribute{
									"size": schema.Int64Attribute{
										Description: "The database size - the total size of compressed data and index in bytes.",
										Required:    true,
									},
								},
							},
							"suspension_details": schema.SingleNestedAttribute{
								Description: "The database suspension details. If the database is suspended, this object contains information related to the database's suspension state.",
								Computed:    true,
								PlanModifiers: []planmodifier.Object{
									objectplanmodifier.UseStateForUnknown(),
								},
								Attributes: map[string]schema.Attribute{
									"suspension_start_date": schema.StringAttribute{
										Description: "The starting date and time of the suspension state.",
										Required:    true,
									},
								},
							},
							"table_level_sharing_properties": schema.SingleNestedAttribute{
								Description: "Table level sharing specifications",
								Computed:    true,
								PlanModifiers: []planmodifier.Object{
									objectplanmodifier.UseStateForUnknown(),
								},
								Attributes: map[string]schema.Attribute{
									"external_tables_to_exclude": schema.ListAttribute{
										Description: "List of external tables to exclude from the follower database",
										Optional:    true,
										Computed:    true,
										PlanModifiers: []planmodifier.List{
											listplanmodifier.UseStateForUnknown(),
										},
										ElementType: types.StringType,
									},
									"external_tables_to_include": schema.ListAttribute{
										Description: "List of external tables to include in the follower database",
										Optional:    true,
										Computed:    true,
										PlanModifiers: []planmodifier.List{
											listplanmodifier.UseStateForUnknown(),
										},
										ElementType: types.StringType,
									},
									"functions_to_exclude": schema.ListAttribute{
										Description: "List of functions to exclude from the follower database",
										Optional:    true,
										Computed:    true,
										PlanModifiers: []planmodifier.List{
											listplanmodifier.UseStateForUnknown(),
										},
										ElementType: types.StringType,
									},
									"functions_to_include": schema.ListAttribute{
										Description: "List of functions to include in the follower database",
										Optional:    true,
										Computed:    true,
										PlanModifiers: []planmodifier.List{
											listplanmodifier.UseStateForUnknown(),
										},
										ElementType: types.StringType,
									},
									"materialized_views_to_exclude": schema.ListAttribute{
										Description: "List of materialized views to exclude from the follower database",
										Optional:    true,
										Computed:    true,
										PlanModifiers: []planmodifier.List{
											listplanmodifier.UseStateForUnknown(),
										},
										ElementType: types.StringType,
									},
									"materialized_views_to_include": schema.ListAttribute{
										Description: "List of materialized views to include in the follower database",
										Optional:    true,
										Computed:    true,
										PlanModifiers: []planmodifier.List{
											listplanmodifier.UseStateForUnknown(),
										},
										ElementType: types.StringType,
									},
									"tables_to_exclude": schema.ListAttribute{
										Description: "List of tables to exclude from the follower database",
										Optional:    true,
										Computed:    true,
										PlanModifiers: []planmodifier.List{
											listplanmodifier.UseStateForUnknown(),
										},
										ElementType: types.StringType,
									},
									"tables_to_include": schema.ListAttribute{
										Description: "List of tables to include in the follower database",
										Optional:    true,
										Computed:    true,
										PlanModifiers: []planmodifier.List{
											listplanmodifier.UseStateForUnknown(),
										},
										ElementType: types.StringType,
									},
								},
							},
						},
					},
				},
			},
			"read_write": schema.SingleNestedAttribute{
				Description: "Variant \\\"ReadWrite\\\" of the discriminated type.",
				Optional:    true,
				Computed:    true,
				Attributes: map[string]schema.Attribute{
					"properties": schema.SingleNestedAttribute{
						Description: "The database properties.",
						Required:    true,
						Attributes: map[string]schema.Attribute{
							"hot_cache_period": schema.StringAttribute{
								Description: "The time the data should be kept in cache for fast queries in TimeSpan.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"is_followed": schema.BoolAttribute{
								Description: "Indicates whether the database is followed.",
								Computed:    true,
								PlanModifiers: []planmodifier.Bool{
									boolplanmodifier.UseStateForUnknown(),
								},
							},
							"key_vault_properties": schema.SingleNestedAttribute{
								Description: "KeyVault properties for the database encryption.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.Object{
									objectplanmodifier.UseStateForUnknown(),
								},
								Attributes: map[string]schema.Attribute{
									"federated_identity_client_id": schema.StringAttribute{
										Description: "The application (client) ID of the multi-tenant Microsoft Entra application. Used for cross-tenant customer-managed key scenarios where the encryption key is stored in a different tenant than the clus...",
										Optional:    true,
										Computed:    true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
										},
									},
									"key_name": schema.StringAttribute{
										Description: "The name of the key vault key.",
										Optional:    true,
										Computed:    true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
										},
									},
									"key_vault_uri": schema.StringAttribute{
										Description: "The Uri of the key vault.",
										Optional:    true,
										Computed:    true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
										},
									},
									"key_version": schema.StringAttribute{
										Description: "The version of the key vault key.",
										Optional:    true,
										Computed:    true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
										},
									},
									"user_identity": schema.StringAttribute{
										Description: "The user assigned identity (ARM resource id) that has access to the key. The identity must have 'Get', 'Wrap Key', and 'Unwrap Key' permissions on the Key Vault key, or be assigned the 'Key Vault Cryp...",
										Optional:    true,
										Computed:    true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
										},
									},
								},
							},
							"provisioning_state": schema.StringAttribute{
								Description: "The provisioned state of the resource.",
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"soft_delete_period": schema.StringAttribute{
								Description: "The time the data should be kept before it stops being accessible to queries in TimeSpan.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"statistics": schema.SingleNestedAttribute{
								Description: "The statistics of the database.",
								Computed:    true,
								PlanModifiers: []planmodifier.Object{
									objectplanmodifier.UseStateForUnknown(),
								},
								Attributes: map[string]schema.Attribute{
									"size": schema.Int64Attribute{
										Description: "The database size - the total size of compressed data and index in bytes.",
										Required:    true,
									},
								},
							},
							"suspension_details": schema.SingleNestedAttribute{
								Description: "The database suspension details. If the database is suspended, this object contains information related to the database's suspension state.",
								Computed:    true,
								PlanModifiers: []planmodifier.Object{
									objectplanmodifier.UseStateForUnknown(),
								},
								Attributes: map[string]schema.Attribute{
									"suspension_start_date": schema.StringAttribute{
										Description: "The starting date and time of the suspension state.",
										Required:    true,
									},
								},
							},
						},
					},
				},
			},
			"id": schema.StringAttribute{
				Computed:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				MarkdownDescription: "The ID of the Azure resource.",
			},
		},
	}
}

// KustoDatabase describes azapi_kusto_database for registration and config builders.
var KustoDatabase = services.Descriptor{
	Name:           "azapi_kusto_database",
	ARMType:        "Microsoft.Kusto/clusters/databases",
	APIVersion:     "2025-02-14",
	Schema:         AzapiKustoDatabaseSchema,
	WritableScopes: 8,
	ParentAttr:     "cluster_id",
	Relational: []services.RelationalConstraint{
		{Kind: services.ExactlyOneOf, Paths: [][]string{{"read_only_following"}, {"read_write"}}, Message: "exactly one variant of the discriminated block must be set"},
	},
}

func init() { services.Register(KustoDatabase) }
