// Code generated by azapin; DO NOT EDIT.
package datafactory

import (
	"time"

	"regexp"

	nativeschema "github.com/Azure/terraform-provider-azapi/internal/native/schema"
	"github.com/Azure/terraform-provider-azapi/internal/native/services"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/mapplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// AzapiDataFactorySchema returns the Terraform resource schema for Microsoft.DataFactory/factories@2018-06-01.
func AzapiDataFactorySchema() schema.Schema {
	return schema.Schema{
		Description: "Manages a Microsoft.DataFactory/factories resource. [azapin:Microsoft.DataFactory/factories@2018-06-01]",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Validators: []validator.String{
					stringvalidator.LengthBetween(3, 63),
					stringvalidator.RegexMatches(
						regexp.MustCompile(`^[A-Za-z0-9]+(?:-[A-Za-z0-9]+)*$`),
						"Data Factory name must be 3-63 characters of alphanumerics and single hyphens, starting and ending with an alphanumeric character",
					),
				},
				MarkdownDescription: "Specifies the name of the Azure resource.",
			},
			"resource_group_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Validators: []validator.String{
					stringvalidator.RegexMatches(
						regexp.MustCompile(`(?i)^/subscriptions/[^/]+/resourceGroups/[^/]+$`),
						"resource_group_id must be a resource group ID (/subscriptions/{id}/resourceGroups/{name})",
					),
				},
				MarkdownDescription: "The ID of the parent resource that contains this resource.",
			},
			"location": schema.StringAttribute{
				Description: "The resource location.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					nativeschema.UseStateForEquivalentLocation(),
					stringplanmodifier.UseStateForUnknown(),
					stringplanmodifier.RequiresReplace(),
				},
			},
			"e_tag": schema.StringAttribute{
				Description: "If eTag is provided in the response body, it may also be provided as a header per the normal etag convention.  Entity tags are used for comparing two or more entities from the same requested resource....",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"properties": schema.SingleNestedAttribute{
				Description: "Properties of the factory.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.UseStateForUnknown(),
				},
				Attributes: map[string]schema.Attribute{
					"create_time": schema.StringAttribute{
						Description: "Time the factory was created in ISO8601 format.",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"encryption": schema.SingleNestedAttribute{
						Description: "Properties to enable Customer Managed Key for the factory.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
						Attributes: map[string]schema.Attribute{
							"identity": schema.SingleNestedAttribute{
								Description: "User assigned identity to use to authenticate to customer's key vault. If not provided Managed Service Identity will be used.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.Object{
									objectplanmodifier.UseStateForUnknown(),
								},
								Attributes: map[string]schema.Attribute{
									"user_assigned_identity": schema.StringAttribute{
										Description: "The resource id of the user assigned identity to authenticate to customer's key vault.",
										Required:    true,
										Validators: []validator.String{
											stringvalidator.RegexMatches(
												regexp.MustCompile(`(?i)^/subscriptions/[^/]+/resourceGroups/[^/]+/providers/Microsoft\.ManagedIdentity/userAssignedIdentities/[^/]+$`),
												"must be a Microsoft.ManagedIdentity user-assigned identity resource ID",
											),
										},
									},
								},
							},
							"key_name": schema.StringAttribute{
								Description: "The name of the key in Azure Key Vault to use as Customer Managed Key.",
								Required:    true,
							},
							"key_version": schema.StringAttribute{
								Description: "The version of the key used for CMK. If not provided, latest version will be used.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"vault_base_url": schema.StringAttribute{
								Description: "The url of the Azure Key Vault used for CMK.",
								Required:    true,
							},
						},
					},
					"global_parameters": schema.MapNestedAttribute{
						Description: "List of parameters for factory.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Map{
							mapplanmodifier.UseStateForUnknown(),
						},
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"type": schema.StringAttribute{
									Description: "Global Parameter type.",
									Required:    true,
									Validators: []validator.String{
										stringvalidator.OneOf(
											"Object",
											"String",
											"Int",
											"Float",
											"Bool",
											"Array",
										),
									},
								},
								"value": schema.StringAttribute{
									Description: "Value of parameter.",
									Required:    true,
								},
							},
						},
					},
					"provisioning_state": schema.StringAttribute{
						Description: "Factory provisioning state, example Succeeded.",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"public_network_access": schema.StringAttribute{
						Description: "Whether or not public network access is allowed for the data factory.",
						Optional:    true,
						Computed:    true,
						Default:     stringdefault.StaticString("Enabled"),
						Validators: []validator.String{
							stringvalidator.OneOf(
								"Enabled",
								"Disabled",
							),
						},
					},
					"purview_configuration": schema.SingleNestedAttribute{
						Description: "Purview information of the factory.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
						Attributes: map[string]schema.Attribute{
							"purview_resource_id": schema.StringAttribute{
								Description: "Purview resource id.",
								Required:    true,
								Validators: []validator.String{
									stringvalidator.RegexMatches(
										regexp.MustCompile(`(?i)^/subscriptions/[^/]+/resourceGroups/[^/]+/providers/Microsoft\.Purview/accounts/[^/]+$`),
										"must be a Microsoft.Purview account resource ID",
									),
								},
							},
						},
					},
					"repo_configuration": schema.SingleNestedAttribute{
						Description: "Git repo information of the factory.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
						Attributes: map[string]schema.Attribute{
							"account_name": schema.StringAttribute{
								Description: "Account name.",
								Required:    true,
							},
							"collaboration_branch": schema.StringAttribute{
								Description: "Collaboration branch.",
								Required:    true,
							},
							"disable_publish": schema.BoolAttribute{
								Description: "Disable manual publish operation in ADF studio to favor automated publish.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.Bool{
									boolplanmodifier.UseStateForUnknown(),
								},
							},
							"last_commit_id": schema.StringAttribute{
								Description: "Last commit id.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"repository_name": schema.StringAttribute{
								Description: "Repository name.",
								Required:    true,
							},
							"root_folder": schema.StringAttribute{
								Description: "Root folder.",
								Required:    true,
							},
							"factory_git_hub_configuration": schema.SingleNestedAttribute{
								Description: "Variant \\\"FactoryGitHubConfiguration\\\" of the discriminated type.",
								Optional:    true,
								Computed:    true,
								Attributes: map[string]schema.Attribute{
									"client_id": schema.StringAttribute{
										Description: "GitHub bring your own app client id.",
										Optional:    true,
										Computed:    true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
										},
									},
									"client_secret": schema.SingleNestedAttribute{
										Description: "GitHub bring your own app client secret information.",
										Optional:    true,
										Computed:    true,
										PlanModifiers: []planmodifier.Object{
											objectplanmodifier.UseStateForUnknown(),
										},
										Attributes: map[string]schema.Attribute{
											"byoa_secret_akv_url": schema.StringAttribute{
												Description: "Bring your own app client secret AKV URL.",
												Optional:    true,
												Computed:    true,
												Sensitive:   true,
												PlanModifiers: []planmodifier.String{
													stringplanmodifier.UseStateForUnknown(),
												},
											},
											"byoa_secret_name": schema.StringAttribute{
												Description: "Bring your own app client secret name in AKV.",
												Optional:    true,
												Computed:    true,
												Sensitive:   true,
												PlanModifiers: []planmodifier.String{
													stringplanmodifier.UseStateForUnknown(),
												},
											},
										},
									},
									"host_name": schema.StringAttribute{
										Description: "GitHub Enterprise host name. For example: `https://github.mydomain.com`",
										Optional:    true,
										Computed:    true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
										},
									},
								},
							},
							"factory_vsts_configuration": schema.SingleNestedAttribute{
								Description: "Variant \\\"FactoryVSTSConfiguration\\\" of the discriminated type.",
								Optional:    true,
								Computed:    true,
								Attributes: map[string]schema.Attribute{
									"project_name": schema.StringAttribute{
										Description: "VSTS project name.",
										Required:    true,
									},
									"tenant_id": schema.StringAttribute{
										Description: "VSTS tenant id.",
										Optional:    true,
										Computed:    true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
										},
									},
								},
							},
						},
					},
					"version": schema.StringAttribute{
						Description: "Version of the factory.",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
				},
			},
			"system_data": schema.SingleNestedAttribute{
				Description: "Azure Resource Manager metadata containing createdBy and modifiedBy information.",
				Computed:    true,
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.UseStateForUnknown(),
				},
				Attributes: map[string]schema.Attribute{
					"created_at": schema.StringAttribute{
						Description: "The timestamp of resource creation (UTC).",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"created_by": schema.StringAttribute{
						Description: "The identity that created the resource.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"created_by_type": schema.StringAttribute{
						Description: "The type of identity that created the resource.",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"User",
								"Application",
								"ManagedIdentity",
								"Key",
							),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"last_modified_at": schema.StringAttribute{
						Description: "The timestamp of resource last modification (UTC)",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"last_modified_by": schema.StringAttribute{
						Description: "The identity that last modified the resource.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"last_modified_by_type": schema.StringAttribute{
						Description: "The type of identity that last modified the resource.",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"User",
								"Application",
								"ManagedIdentity",
								"Key",
							),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
				},
			},
			"identity": nativeschema.ManagedServiceIdentity(true, ""),
			"tags": schema.MapAttribute{
				Description: "The resource tags.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.Map{
					mapplanmodifier.UseStateForUnknown(),
				},
				ElementType: types.StringType,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				MarkdownDescription: "The ID of the Azure resource.",
			},
		},
	}
}

// DataFactory describes azapi_data_factory for registration and config builders.
var DataFactory = services.Descriptor{
	Name:           "azapi_data_factory",
	ARMType:        "Microsoft.DataFactory/factories",
	APIVersion:     "2018-06-01",
	Schema:         AzapiDataFactorySchema,
	WritableScopes: 8,
	ParentAttr:     "resource_group_id",
	Relational: []services.RelationalConstraint{
		{Kind: services.RequiredWith, Paths: [][]string{{"properties", "encryption", "key_name"}, {"properties", "encryption", "identity", "user_assigned_identity"}}, Message: "customer-managed-key encryption requires a user-assigned identity (properties.encryption.identity.userAssignedIdentity)"},
		{Kind: services.AtMostOneOf, Paths: [][]string{{"properties", "repo_configuration", "factory_git_hub_configuration"}, {"properties", "repo_configuration", "factory_vsts_configuration"}}, Message: "at most one variant of the discriminated block may be set"},
	},
	Timeouts: services.Timeouts{
		Create: 30 * time.Minute,
		Read:   5 * time.Minute,
		Update: 30 * time.Minute,
		Delete: 30 * time.Minute,
	},
}

func init() { services.Register(DataFactory) }
