// Code generated by azapin; DO NOT EDIT.
package web

import (
	"regexp"

	nativeschema "github.com/Azure/terraform-provider-azapi/internal/native/schema"
	"github.com/Azure/terraform-provider-azapi/internal/native/services"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/mapplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// AzapiWebServerFarmSchema returns the Terraform resource schema for Microsoft.Web/serverfarms@2025-03-01.
func AzapiWebServerFarmSchema() schema.Schema {
	return schema.Schema{
		Description: "Manages a Microsoft.Web/serverfarms resource. [azapin:Microsoft.Web/serverfarms@2025-03-01]",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 60),
					stringvalidator.RegexMatches(
						regexp.MustCompile(`^[0-9A-Za-z-_]+$`),
						"App Service plan name may only contain alphanumeric characters, dashes, and underscores, up to 60 characters",
					),
				},
				MarkdownDescription: "Specifies the name of the Azure resource.",
			},
			"resource_group_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Validators: []validator.String{
					stringvalidator.RegexMatches(
						regexp.MustCompile(`(?i)^/subscriptions/[^/]+/resourceGroups/[^/]+$`),
						"resource_group_id must be a resource group ID (/subscriptions/{id}/resourceGroups/{name})",
					),
				},
				MarkdownDescription: "The ID of the parent resource that contains this resource.",
			},
			"location": schema.StringAttribute{
				Description: "Resource Location.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					nativeschema.UseStateForEquivalentLocation(),
					stringplanmodifier.RequiresReplace(),
				},
			},
			"sku": schema.SingleNestedAttribute{
				Description: "Description of a SKU for a scalable resource.",
				Required:    true,
				Attributes: map[string]schema.Attribute{
					"capabilities": schema.ListNestedAttribute{
						Description: "Capabilities of the SKU, e.g., is traffic manager enabled?",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.List{
							listplanmodifier.UseStateForUnknown(),
						},
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"name": schema.StringAttribute{
									Description: "Name of the SKU capability.",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"reason": schema.StringAttribute{
									Description: "Reason of the SKU capability.",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"value": schema.StringAttribute{
									Description: "Value of the SKU capability.",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
							},
						},
					},
					"capacity": schema.Int64Attribute{
						Description: "Current number of instances assigned to the resource.",
						Optional:    true,
						Computed:    true,
						Validators: []validator.Int64{
							int64validator.AtLeast(1),
						},
						PlanModifiers: []planmodifier.Int64{
							int64planmodifier.UseStateForUnknown(),
						},
					},
					"family": schema.StringAttribute{
						Description: "Family code of the resource SKU.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"locations": schema.ListAttribute{
						Description: "Locations of the SKU.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.List{
							listplanmodifier.UseStateForUnknown(),
						},
						ElementType: types.StringType,
					},
					"name": schema.StringAttribute{
						Description: "Name of the resource SKU.",
						Required:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"B1",
								"B2",
								"B3",
								"S1",
								"S2",
								"S3",
								"Y1",
								"EP1",
								"EP2",
								"EP3",
								"FC1",
								"F1",
								"I1",
								"I2",
								"I3",
								"I1v2",
								"I2v2",
								"I3v2",
								"I4v2",
								"I5v2",
								"I6v2",
								"I1mv2",
								"I2mv2",
								"I3mv2",
								"I4mv2",
								"I5mv2",
								"P1v2",
								"P2v2",
								"P3v2",
								"P0v3",
								"P1v3",
								"P2v3",
								"P3v3",
								"P1mv3",
								"P2mv3",
								"P3mv3",
								"P4mv3",
								"P5mv3",
								"P0v4",
								"P1v4",
								"P2v4",
								"P3v4",
								"P1mv4",
								"P2mv4",
								"P3mv4",
								"P4mv4",
								"P5mv4",
								"D1",
								"SHARED",
								"WS1",
								"WS2",
								"WS3",
							),
						},
					},
					"size": schema.StringAttribute{
						Description: "Size specifier of the resource SKU.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"sku_capacity": schema.SingleNestedAttribute{
						Description: "Min, max, and default scale values of the SKU.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
						Attributes: map[string]schema.Attribute{
							"default": schema.Int64Attribute{
								Description: "Default number of workers for this App Service plan SKU.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.Int64{
									int64planmodifier.UseStateForUnknown(),
								},
							},
							"elastic_maximum": schema.Int64Attribute{
								Description: "Maximum number of Elastic workers for this App Service plan SKU.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.Int64{
									int64planmodifier.UseStateForUnknown(),
								},
							},
							"maximum": schema.Int64Attribute{
								Description: "Maximum number of workers for this App Service plan SKU.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.Int64{
									int64planmodifier.UseStateForUnknown(),
								},
							},
							"minimum": schema.Int64Attribute{
								Description: "Minimum number of workers for this App Service plan SKU.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.Int64{
									int64planmodifier.UseStateForUnknown(),
								},
							},
							"scale_type": schema.StringAttribute{
								Description: "Available scale configurations for an App Service plan.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
						},
					},
					"tier": schema.StringAttribute{
						Description: "Service tier of the resource SKU.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
				},
			},
			"kind": schema.StringAttribute{
				Description: "Kind of resource. If the resource is an app, you can refer to https://github.com/Azure/app-service-linux-docs/blob/master/Things_You_Should_Know/kind_property.md#app-service-resource-kind-reference fo...",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"extended_location": schema.SingleNestedAttribute{
				Description: "Extended Location.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.UseStateForUnknown(),
				},
				Attributes: map[string]schema.Attribute{
					"name": schema.StringAttribute{
						Description: "Name of extended location.",
						Required:    true,
					},
					"type": schema.StringAttribute{
						Description: "Type of extended location.",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
				},
			},
			"properties": schema.SingleNestedAttribute{
				Description: "AppServicePlan resource specific properties",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.UseStateForUnknown(),
				},
				Attributes: map[string]schema.Attribute{
					"async_scaling_enabled": schema.BoolAttribute{
						Description: "If <code>true</code>, this App Service Plan will attempt to scale asynchronously if there are insufficient workers to scale synchronously.\nIf <code>false</code>, this App Service Plan will only attemp...",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Bool{
							boolplanmodifier.UseStateForUnknown(),
						},
					},
					"elastic_scale_enabled": schema.BoolAttribute{
						Description: "ServerFarm supports ElasticScale. Apps in this plan will scale as if the ServerFarm was ElasticPremium sku",
						Optional:    true,
						Computed:    true,
						Default:     nativeschema.StaticBool(false),
					},
					"free_offer_expiration_time": schema.StringAttribute{
						Description: "The time when the server farm free offer expires.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"geo_region": schema.StringAttribute{
						Description: "Geographical location for the App Service plan.",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"hosting_environment_profile": schema.SingleNestedAttribute{
						Description: "Specification for the App Service Environment to use for the App Service plan.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
						Attributes: map[string]schema.Attribute{
							"id": schema.StringAttribute{
								Description: "Resource ID of the App Service Environment.",
								Required:    true,
								Validators: []validator.String{
									stringvalidator.RegexMatches(
										regexp.MustCompile(`(?i)^/subscriptions/[^/]+/resourceGroups/[^/]+/providers/Microsoft\.Web/hostingEnvironments/[^/]+$`),
										"must be an App Service Environment resource ID",
									),
									nativeschema.AzureResourceID(),
								},
							},
							"name": schema.StringAttribute{
								Description: "Name of the App Service Environment.",
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"type": schema.StringAttribute{
								Description: "Resource type of the App Service Environment.",
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
						},
					},
					"hyper_v": schema.BoolAttribute{
						Description: "If Hyper-V container app service plan <code>true</code>, <code>false</code> otherwise.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Bool{
							boolplanmodifier.UseStateForUnknown(),
							boolplanmodifier.RequiresReplace(),
						},
					},
					"install_scripts": schema.ListNestedAttribute{
						Description: "Install scripts associated with this App Service plan.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.List{
							listplanmodifier.UseStateForUnknown(),
						},
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"name": schema.StringAttribute{
									Description: "Name of the install script.",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"source": schema.SingleNestedAttribute{
									Description: "Source of the install script.",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.Object{
										objectplanmodifier.UseStateForUnknown(),
									},
									Attributes: map[string]schema.Attribute{
										"source_uri": schema.StringAttribute{
											Description: "Install script source URI where the install script file will be fetched from.",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
										},
										"type": schema.StringAttribute{
											Description: "Type of the install script.",
											Optional:    true,
											Computed:    true,
											Validators: []validator.String{
												stringvalidator.OneOf(
													"RemoteAzureBlob",
													"PlatformStorage",
												),
											},
											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
										},
									},
								},
							},
						},
					},
					"is_custom_mode": schema.BoolAttribute{
						Description: "Whether this server farm is in custom mode.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Bool{
							boolplanmodifier.UseStateForUnknown(),
						},
					},
					"is_spot": schema.BoolAttribute{
						Description: "If <code>true</code>, this App Service Plan owns spot instances.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Bool{
							boolplanmodifier.UseStateForUnknown(),
						},
					},
					"is_xenon": schema.BoolAttribute{
						Description: "Obsolete: If Hyper-V container app service plan <code>true</code>, <code>false</code> otherwise.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Bool{
							boolplanmodifier.UseStateForUnknown(),
						},
					},
					"kube_environment_profile": schema.SingleNestedAttribute{
						Description: "Specification for the Kubernetes Environment to use for the App Service plan.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
						Attributes: map[string]schema.Attribute{
							"id": schema.StringAttribute{
								Description: "Resource ID of the Kubernetes Environment.",
								Required:    true,
							},
							"name": schema.StringAttribute{
								Description: "Name of the Kubernetes Environment.",
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"type": schema.StringAttribute{
								Description: "Resource type of the Kubernetes Environment.",
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
						},
					},
					"maximum_elastic_worker_count": schema.Int64Attribute{
						Description: "Maximum number of total workers allowed for this ElasticScaleEnabled App Service Plan",
						Optional:    true,
						Computed:    true,
						Validators: []validator.Int64{
							int64validator.AtLeast(0),
						},
						PlanModifiers: []planmodifier.Int64{
							int64planmodifier.UseStateForUnknown(),
						},
					},
					"maximum_number_of_workers": schema.Int64Attribute{
						Description: "Maximum number of instances that can be assigned to this App Service plan.",
						Computed:    true,
						PlanModifiers: []planmodifier.Int64{
							int64planmodifier.UseStateForUnknown(),
						},
					},
					"network": schema.SingleNestedAttribute{
						Description: "All network settings for the server farm.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
						Attributes: map[string]schema.Attribute{
							"virtual_network_subnet_id": schema.StringAttribute{
								Description: "Azure Resource Manager ID of the Virtual network and subnet to be joined by Regional VNET Integration. This must be of the form /subscriptions/{subscriptionName}/resourceGroups/{resourceGroupName}/pro...",
								Required:    true,
								Validators: []validator.String{
									stringvalidator.RegexMatches(
										regexp.MustCompile(`^/subscriptions/[^/]+/resourceGroups/[^/]+/providers/`),
										"must be a valid ARM resource ID",
									),
								},
							},
						},
					},
					"number_of_sites": schema.Int64Attribute{
						Description: "Number of apps assigned to this App Service plan.",
						Computed:    true,
						PlanModifiers: []planmodifier.Int64{
							int64planmodifier.UseStateForUnknown(),
						},
					},
					"number_of_workers": schema.Int64Attribute{
						Description: "The number of instances that are assigned to this App Service plan.",
						Computed:    true,
						PlanModifiers: []planmodifier.Int64{
							int64planmodifier.UseStateForUnknown(),
						},
					},
					"per_site_scaling": schema.BoolAttribute{
						Description: "If <code>true</code>, apps assigned to this App Service plan can be scaled independently.\nIf <code>false</code>, apps assigned to this App Service plan will scale to all instances of the plan.",
						Optional:    true,
						Computed:    true,
						Default:     nativeschema.StaticBool(false),
					},
					"plan_default_identity": schema.SingleNestedAttribute{
						Description: "Identity to use by platform for various features and integrations using managed identity.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
						Attributes: map[string]schema.Attribute{
							"identity_type": schema.StringAttribute{
								Optional: true,
								Computed: true,
								Validators: []validator.String{
									stringvalidator.OneOf(
										"None",
										"SystemAssigned",
										"UserAssigned",
										"SystemAssigned, UserAssigned",
									),
								},
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"user_assigned_identity_resource_id": schema.StringAttribute{
								Optional: true,
								Computed: true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
						},
					},
					"provisioning_state": schema.StringAttribute{
						Description: "Provisioning state of the App Service Plan.",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"rdp_enabled": schema.BoolAttribute{
						Description: "If <code>true</code>, RDP access is enabled for this App Service plan. Only applicable for IsCustomMode ASPs.\nIf <code>false</code>, RDP access is disabled.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Bool{
							boolplanmodifier.UseStateForUnknown(),
						},
					},
					"registry_adapters": schema.ListNestedAttribute{
						Description: "Registry adapters associated with this App Service plan.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.List{
							listplanmodifier.UseStateForUnknown(),
						},
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"key_vault_secret_reference": schema.SingleNestedAttribute{
									Description: "Key vault reference to the value that will be placed in the registry location",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.Object{
										objectplanmodifier.UseStateForUnknown(),
									},
									Attributes: map[string]schema.Attribute{
										"reference_status": schema.StringAttribute{
											Description: "Reference status of the key vault secret.",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
										},
										"secret_uri": schema.StringAttribute{
											Description: "Key vault secret URI.",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
										},
									},
								},
								"registry_key": schema.StringAttribute{
									Description: "Registry key for the adapter.",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"type": schema.StringAttribute{
									Description: "Type of the registry adapter.",
									Optional:    true,
									Computed:    true,
									Validators: []validator.String{
										stringvalidator.OneOf(
											"Binary",
											"String",
											"Expand_String",
											"Multi_String",
											"DWord",
											"QWord",
										),
									},
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
							},
						},
					},
					"reserved": schema.BoolAttribute{
						Description: "If Linux app service plan <code>true</code>, <code>false</code> otherwise.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Bool{
							boolplanmodifier.UseStateForUnknown(),
							boolplanmodifier.RequiresReplace(),
						},
					},
					"resource_group": schema.StringAttribute{
						Description: "Resource group of the App Service plan.",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"spot_expiration_time": schema.StringAttribute{
						Description: "The time when the server farm expires. Valid only if it is a spot server farm.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"status": schema.StringAttribute{
						Description: "App Service plan status.",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"storage_mounts": schema.ListNestedAttribute{
						Description: "Storage mounts associated with this App Service plan.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.List{
							listplanmodifier.UseStateForUnknown(),
						},
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"credentials_key_vault_reference": schema.SingleNestedAttribute{
									Description: "KV reference to the credentials to connect to the share.",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.Object{
										objectplanmodifier.UseStateForUnknown(),
									},
									Attributes: map[string]schema.Attribute{
										"reference_status": schema.StringAttribute{
											Description: "Reference status of the key vault secret.",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
										},
										"secret_uri": schema.StringAttribute{
											Description: "Key vault secret URI.",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
										},
									},
								},
								"destination_path": schema.StringAttribute{
									Description: "Path on worker where storage will be mounted.",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"name": schema.StringAttribute{
									Description: "Name of the storage mount.",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"source": schema.StringAttribute{
									Description: "Source of the fileshare/storage.",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"type": schema.StringAttribute{
									Description: "Type of the storage mount.",
									Optional:    true,
									Computed:    true,
									Validators: []validator.String{
										stringvalidator.OneOf(
											"AzureFiles",
											"LocalStorage",
											"FileShare",
										),
									},
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
							},
						},
					},
					"subscription": schema.StringAttribute{
						Description: "App Service plan subscription.",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"target_worker_count": schema.Int64Attribute{
						Description: "Scaling worker count.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Int64{
							int64planmodifier.UseStateForUnknown(),
						},
					},
					"target_worker_size_id": schema.Int64Attribute{
						Description: "Scaling worker size ID.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Int64{
							int64planmodifier.UseStateForUnknown(),
						},
					},
					"worker_tier_name": schema.StringAttribute{
						Description: "Target worker tier assigned to the App Service plan.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"zone_redundant": schema.BoolAttribute{
						Description: "If <code>true</code>, this App Service Plan will perform availability zone balancing.\nIf <code>false</code>, this App Service Plan will not perform availability zone balancing.",
						Optional:    true,
						Computed:    true,
						Default:     nativeschema.StaticBool(false),
					},
				},
			},
			"identity": nativeschema.ManagedServiceIdentity(false, ""),
			"tags": schema.MapAttribute{
				Description: "Resource tags.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.Map{
					mapplanmodifier.UseStateForUnknown(),
				},
				ElementType: types.StringType,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				MarkdownDescription: "The ID of the Azure resource.",
			},
		},
	}
}

// WebServerFarm describes azapi_web_server_farm for registration and config builders.
var WebServerFarm = services.Descriptor{
	Name:           "azapi_web_server_farm",
	ARMType:        "Microsoft.Web/serverfarms",
	APIVersion:     "2025-03-01",
	Schema:         AzapiWebServerFarmSchema,
	WritableScopes: 8,
	ParentAttr:     "resource_group_id",
}

func init() { services.Register(WebServerFarm) }
