// Code generated by azapin; DO NOT EDIT.
package keyvault

import (
	"time"

	"regexp"

	"github.com/Azure/terraform-provider-azapi/internal/native/services"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/mapplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// AzapiKeyVaultKeySchema returns the Terraform resource schema for Microsoft.KeyVault/vaults/keys@2025-05-01.
func AzapiKeyVaultKeySchema() schema.Schema {
	return schema.Schema{
		Description: "Manages a Microsoft.KeyVault/vaults/keys resource. [azapin:Microsoft.KeyVault/vaults/keys@2025-05-01]",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 127),
					stringvalidator.RegexMatches(
						regexp.MustCompile(`^[0-9a-zA-Z-]+$`),
						"key vault key name must contain only alphanumeric characters and dashes, 1-127 characters",
					),
				},
				MarkdownDescription: "Specifies the name of the Azure resource.",
			},
			"key_vault_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Validators: []validator.String{
					stringvalidator.RegexMatches(
						regexp.MustCompile(`(?i)/providers/Microsoft\.KeyVault/vaults/[^/]+$`),
						"key_vault_id must be the ID of a Microsoft.KeyVault/vaults resource",
					),
				},
				MarkdownDescription: "The ID of the parent resource that contains this resource.",
			},
			"location": schema.StringAttribute{
				Description: "The supported Azure location where the managed HSM Pool should be created.",
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"properties": schema.SingleNestedAttribute{
				Description: "The properties of the key to be created.",
				Required:    true,
				Attributes: map[string]schema.Attribute{
					"attributes": schema.SingleNestedAttribute{
						Description: "The attributes of the key.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
						Attributes: map[string]schema.Attribute{
							"created": schema.Int64Attribute{
								Description: "Creation time in seconds since 1970-01-01T00:00:00Z.",
								Computed:    true,
								PlanModifiers: []planmodifier.Int64{
									int64planmodifier.UseStateForUnknown(),
								},
							},
							"enabled": schema.BoolAttribute{
								Description: "Determines whether or not the object is enabled.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.Bool{
									boolplanmodifier.UseStateForUnknown(),
									boolplanmodifier.RequiresReplace(),
								},
							},
							"exp": schema.Int64Attribute{
								Description: "Expiry date in seconds since 1970-01-01T00:00:00Z.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.Int64{
									int64planmodifier.UseStateForUnknown(),
									int64planmodifier.RequiresReplace(),
								},
							},
							"exportable": schema.BoolAttribute{
								Description: "Indicates if the private key can be exported.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.Bool{
									boolplanmodifier.UseStateForUnknown(),
									boolplanmodifier.RequiresReplace(),
								},
							},
							"nbf": schema.Int64Attribute{
								Description: "Not before date in seconds since 1970-01-01T00:00:00Z.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.Int64{
									int64planmodifier.UseStateForUnknown(),
									int64planmodifier.RequiresReplace(),
								},
							},
							"recovery_level": schema.StringAttribute{
								Description: "The deletion recovery level currently in effect for the object. If it contains 'Purgeable', then the object can be permanently deleted by a privileged user; otherwise, only the system can purge the ob...",
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"updated": schema.Int64Attribute{
								Description: "Last updated time in seconds since 1970-01-01T00:00:00Z.",
								Computed:    true,
								PlanModifiers: []planmodifier.Int64{
									int64planmodifier.UseStateForUnknown(),
								},
							},
						},
					},
					"curve_name": schema.StringAttribute{
						Description: "The elliptic curve name. For valid values, see JsonWebKeyCurveName. Default for EC and EC-HSM keys is P-256",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"P-256",
								"P-384",
								"P-521",
								"P-256K",
							),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
							stringplanmodifier.RequiresReplace(),
						},
					},
					"key_ops": schema.ListAttribute{
						Required: true,
						PlanModifiers: []planmodifier.List{
							listplanmodifier.RequiresReplace(),
						},
						Validators: []validator.List{
							listvalidator.ValueStringsAre(
								stringvalidator.OneOf(
									"decrypt",
									"encrypt",
									"import",
									"release",
									"sign",
									"unwrapKey",
									"verify",
									"wrapKey",
								),
							),
						},
						ElementType: types.StringType,
					},
					"key_size": schema.Int64Attribute{
						Description: "The key size in bits. For example: 2048, 3072, or 4096 for RSA. Default for RSA and RSA-HSM keys is 2048. Exception made for bring your own key (BYOK), key exchange keys default to 4096.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Int64{
							int64planmodifier.UseStateForUnknown(),
							int64planmodifier.RequiresReplace(),
						},
					},
					"key_uri": schema.StringAttribute{
						Description: "The URI to retrieve the current version of the key.",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"key_uri_with_version": schema.StringAttribute{
						Description: "The URI to retrieve the specific version of the key.",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"kty": schema.StringAttribute{
						Description: "The type of the key. For valid values, see JsonWebKeyType.",
						Required:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"EC",
								"EC-HSM",
								"RSA",
								"RSA-HSM",
							),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.RequiresReplace(),
						},
					},
					"release_policy": schema.SingleNestedAttribute{
						Description: "Key release policy in response. It will be used for both output and input. Omitted if empty",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
						Attributes: map[string]schema.Attribute{
							"content_type": schema.StringAttribute{
								Description: "Content type and version of key release policy",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
									stringplanmodifier.RequiresReplace(),
								},
							},
							"data": schema.StringAttribute{
								Description: "Blob encoding the policy rules under which the key can be released.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
									stringplanmodifier.RequiresReplace(),
								},
							},
						},
					},
					"rotation_policy": schema.SingleNestedAttribute{
						Description: "Key rotation policy in response. It will be used for both output and input. Omitted if empty",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
						Attributes: map[string]schema.Attribute{
							"attributes": schema.SingleNestedAttribute{
								Description: "The attributes of key rotation policy.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.Object{
									objectplanmodifier.UseStateForUnknown(),
								},
								Attributes: map[string]schema.Attribute{
									"created": schema.Int64Attribute{
										Description: "Creation time in seconds since 1970-01-01T00:00:00Z.",
										Computed:    true,
										PlanModifiers: []planmodifier.Int64{
											int64planmodifier.UseStateForUnknown(),
										},
									},
									"expiry_time": schema.StringAttribute{
										Description: "The expiration time for the new key version. It should be in ISO8601 format. Eg: 'P90D', 'P1Y'.",
										Required:    true,
										Validators: []validator.String{
											stringvalidator.RegexMatches(
												regexp.MustCompile(`^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$`),
												"must be in datetime format yyyy-MM-ddTHH:mm:ssZ",
											),
										},
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.RequiresReplace(),
										},
									},
									"updated": schema.Int64Attribute{
										Description: "Last updated time in seconds since 1970-01-01T00:00:00Z.",
										Computed:    true,
										PlanModifiers: []planmodifier.Int64{
											int64planmodifier.UseStateForUnknown(),
										},
									},
								},
							},
							"lifetime_actions": schema.ListNestedAttribute{
								Description: "The lifetimeActions for key rotation action.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.List{
									listplanmodifier.UseStateForUnknown(),
									listplanmodifier.RequiresReplace(),
								},
								NestedObject: schema.NestedAttributeObject{
									Attributes: map[string]schema.Attribute{
										"action": schema.SingleNestedAttribute{
											Description: "The action of key rotation policy lifetimeAction.",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.Object{
												objectplanmodifier.UseStateForUnknown(),
											},
											Attributes: map[string]schema.Attribute{
												"type": schema.StringAttribute{
													Description: "The type of action.",
													Required:    true,
													Validators: []validator.String{
														stringvalidator.OneOf(
															"rotate",
															"notify",
														),
													},
												},
											},
										},
										"trigger": schema.SingleNestedAttribute{
											Description: "The trigger of key rotation policy lifetimeAction.",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.Object{
												objectplanmodifier.UseStateForUnknown(),
											},
											Attributes: map[string]schema.Attribute{
												"time_after_create": schema.StringAttribute{
													Description: "The time duration after key creation to rotate the key. It only applies to rotate. It will be in ISO 8601 duration format. Eg: 'P90D', 'P1Y'.",
													Optional:    true,
													Computed:    true,
													Validators: []validator.String{
														stringvalidator.RegexMatches(
															regexp.MustCompile(`^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$`),
															"must be in datetime format yyyy-MM-ddTHH:mm:ssZ",
														),
													},
													PlanModifiers: []planmodifier.String{
														stringplanmodifier.UseStateForUnknown(),
													},
												},
												"time_before_expiry": schema.StringAttribute{
													Description: "The time duration before key expiring to rotate or notify. It will be in ISO 8601 duration format. Eg: 'P90D', 'P1Y'.",
													Optional:    true,
													Computed:    true,
													Validators: []validator.String{
														stringvalidator.RegexMatches(
															regexp.MustCompile(`^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$`),
															"must be in datetime format yyyy-MM-ddTHH:mm:ssZ",
														),
													},
													PlanModifiers: []planmodifier.String{
														stringplanmodifier.UseStateForUnknown(),
													},
												},
											},
										},
									},
								},
							},
						},
					},
				},
			},
			"system_data": schema.SingleNestedAttribute{
				Description: "Azure Resource Manager metadata containing createdBy and modifiedBy information.",
				Computed:    true,
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.UseStateForUnknown(),
				},
				Attributes: map[string]schema.Attribute{
					"created_at": schema.StringAttribute{
						Description: "The timestamp of resource creation (UTC).",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"created_by": schema.StringAttribute{
						Description: "The identity that created the resource.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"created_by_type": schema.StringAttribute{
						Description: "The type of identity that created the resource.",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"User",
								"Application",
								"ManagedIdentity",
								"Key",
							),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"last_modified_at": schema.StringAttribute{
						Description: "The timestamp of resource last modification (UTC)",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"last_modified_by": schema.StringAttribute{
						Description: "The identity that last modified the resource.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"last_modified_by_type": schema.StringAttribute{
						Description: "The type of identity that last modified the resource.",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"User",
								"Application",
								"ManagedIdentity",
								"Key",
							),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
				},
			},
			"tags": schema.MapAttribute{
				Description: "The tags that will be assigned to the key.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.Map{
					mapplanmodifier.UseStateForUnknown(),
					mapplanmodifier.RequiresReplace(),
				},
				ElementType: types.StringType,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				MarkdownDescription: "The ID of the Azure resource.",
			},
		},
	}
}

// KeyVaultKey describes azapi_key_vault_key for registration and config builders.
var KeyVaultKey = services.Descriptor{
	Name:           "azapi_key_vault_key",
	ARMType:        "Microsoft.KeyVault/vaults/keys",
	APIVersion:     "2025-05-01",
	Schema:         AzapiKeyVaultKeySchema,
	WritableScopes: 8,
	ParentAttr:     "key_vault_id",
	Timeouts: services.Timeouts{
		Create: 30 * time.Minute,
		Read:   30 * time.Minute,
		Update: 30 * time.Minute,
		Delete: 30 * time.Minute,
	},
}

func init() { services.Register(KeyVaultKey) }
