// Code generated by azapin; DO NOT EDIT.
package keyvault

import (
	"time"

	"regexp"

	nativeschema "github.com/Azure/terraform-provider-azapi/internal/native/schema"
	"github.com/Azure/terraform-provider-azapi/internal/native/services"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64default"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/mapplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// AzapiKeyVaultSchema returns the Terraform resource schema for Microsoft.KeyVault/vaults@2026-02-01.
func AzapiKeyVaultSchema() schema.Schema {
	return schema.Schema{
		Description: "Manages a Microsoft.KeyVault/vaults resource. [azapin:Microsoft.KeyVault/vaults@2026-02-01]",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Validators: []validator.String{
					stringvalidator.LengthBetween(3, 24),
					stringvalidator.RegexMatches(
						regexp.MustCompile(`^[a-zA-Z](-?[a-zA-Z0-9])*$`),
						"key vault name must be 3-24 characters, start with a letter, end with a letter or digit, and contain only alphanumeric characters or non-consecutive hyphens",
					),
				},
				MarkdownDescription: "Specifies the name of the Azure resource.",
			},
			"resource_group_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Validators: []validator.String{
					stringvalidator.RegexMatches(
						regexp.MustCompile(`(?i)^/subscriptions/[^/]+/resourceGroups/[^/]+$`),
						"resource_group_id must be a resource group ID (/subscriptions/{id}/resourceGroups/{name})",
					),
				},
				MarkdownDescription: "The ID of the parent resource that contains this resource.",
			},
			"location": schema.StringAttribute{
				Description: "The supported Azure location where the key vault should be created.",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					nativeschema.UseStateForEquivalentLocation(),
				},
			},
			"properties": schema.SingleNestedAttribute{
				Description: "Properties of the vault",
				Required:    true,
				Attributes: map[string]schema.Attribute{
					"access_policies": schema.ListNestedAttribute{
						Description: "An array of 0 to 1024 identities that have access to the key vault. All identities in the array must use the same tenant ID as the key vault's tenant ID. When `createMode` is set to `recover`, access ...",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.List{
							listplanmodifier.UseStateForUnknown(),
						},
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"application_id": schema.StringAttribute{
									Description: "Application ID of the client making request on behalf of a principal",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"object_id": schema.StringAttribute{
									Description: "The object ID of a user, service principal or security group in the Azure Active Directory tenant for the vault. The object ID must be unique for the list of access policies.",
									Required:    true,
								},
								"permissions": schema.SingleNestedAttribute{
									Description: "Permissions the identity has for keys, secrets and certificates.",
									Required:    true,
									Attributes: map[string]schema.Attribute{
										"certificates": schema.ListAttribute{
											Description: "Permissions to certificates",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.List{
												listplanmodifier.UseStateForUnknown(),
											},
											Validators: []validator.List{
												listvalidator.ValueStringsAre(
													stringvalidator.OneOfCaseInsensitive(
														"Backup",
														"Create",
														"Delete",
														"DeleteIssuers",
														"Get",
														"GetIssuers",
														"Import",
														"List",
														"ListIssuers",
														"ManageContacts",
														"ManageIssuers",
														"Purge",
														"Recover",
														"Restore",
														"SetIssuers",
														"Update",
													),
												),
											},
											ElementType: types.StringType,
										},
										"keys": schema.ListAttribute{
											Description: "Permissions to keys",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.List{
												listplanmodifier.UseStateForUnknown(),
											},
											Validators: []validator.List{
												listvalidator.ValueStringsAre(
													stringvalidator.OneOfCaseInsensitive(
														"Backup",
														"Create",
														"Decrypt",
														"Delete",
														"Encrypt",
														"Get",
														"Import",
														"List",
														"Purge",
														"Recover",
														"Restore",
														"Sign",
														"UnwrapKey",
														"Update",
														"Verify",
														"WrapKey",
														"Release",
														"Rotate",
														"GetRotationPolicy",
														"SetRotationPolicy",
													),
												),
											},
											ElementType: types.StringType,
										},
										"secrets": schema.ListAttribute{
											Description: "Permissions to secrets",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.List{
												listplanmodifier.UseStateForUnknown(),
											},
											Validators: []validator.List{
												listvalidator.ValueStringsAre(
													stringvalidator.OneOfCaseInsensitive(
														"Backup",
														"Delete",
														"Get",
														"List",
														"Purge",
														"Recover",
														"Restore",
														"Set",
													),
												),
											},
											ElementType: types.StringType,
										},
										"storage": schema.ListAttribute{
											Description: "Permissions to storage accounts",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.List{
												listplanmodifier.UseStateForUnknown(),
											},
											Validators: []validator.List{
												listvalidator.ValueStringsAre(
													stringvalidator.OneOfCaseInsensitive(
														"Backup",
														"Delete",
														"DeleteSAS",
														"Get",
														"GetSAS",
														"List",
														"ListSAS",
														"Purge",
														"Recover",
														"RegenerateKey",
														"Restore",
														"Set",
														"SetSAS",
														"Update",
													),
												),
											},
											ElementType: types.StringType,
										},
									},
								},
								"tenant_id": schema.StringAttribute{
									Description: "The Azure Active Directory tenant ID that should be used for authenticating requests to the key vault.",
									Required:    true,
								},
							},
						},
					},
					"create_mode": schema.StringAttribute{
						Description: "The vault's create mode to indicate whether the vault need to be recovered or not.",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"recover",
								"default",
							),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"enable_purge_protection": schema.BoolAttribute{
						Description: "Property specifying whether protection against purge is enabled for this vault. Setting this property to true activates protection against purge for this vault and its content - only the Key Vault ser...",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Bool{
							boolplanmodifier.UseStateForUnknown(),
						},
					},
					"enable_rbac_authorization": schema.BoolAttribute{
						Description: "Property that controls how data actions are authorized. When true, the key vault will use Role Based Access Control (RBAC) for authorization of data actions, and the access policies specified in vault...",
						Optional:    true,
						Computed:    true,
						Default:     booldefault.StaticBool(true),
					},
					"enable_soft_delete": schema.BoolAttribute{
						Description: "Property to specify whether the 'soft delete' functionality is enabled for this key vault. If it's not set to any value(true or false) when creating new key vault, it will be set to true by default. O...",
						Optional:    true,
						Computed:    true,
						Default:     booldefault.StaticBool(true),
					},
					"enabled_for_deployment": schema.BoolAttribute{
						Description: "Property to specify whether Azure Virtual Machines are permitted to retrieve certificates stored as secrets from the key vault.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Bool{
							boolplanmodifier.UseStateForUnknown(),
						},
					},
					"enabled_for_disk_encryption": schema.BoolAttribute{
						Description: "Property to specify whether Azure Disk Encryption is permitted to retrieve secrets from the vault and unwrap keys.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Bool{
							boolplanmodifier.UseStateForUnknown(),
						},
					},
					"enabled_for_template_deployment": schema.BoolAttribute{
						Description: "Property to specify whether Azure Resource Manager is permitted to retrieve secrets from the key vault.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Bool{
							boolplanmodifier.UseStateForUnknown(),
						},
					},
					"hsm_pool_resource_id": schema.StringAttribute{
						Description: "The resource id of HSM Pool.",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"network_acls": schema.SingleNestedAttribute{
						Description: "Rules governing the accessibility of the key vault from specific network locations.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Object{
							objectplanmodifier.UseStateForUnknown(),
						},
						Attributes: map[string]schema.Attribute{
							"bypass": schema.StringAttribute{
								Description: "Tells what traffic can bypass network rules. This can be 'AzureServices' or 'None'.  If not specified the default is 'AzureServices'.",
								Optional:    true,
								Computed:    true,
								Default:     stringdefault.StaticString("AzureServices"),
								Validators: []validator.String{
									stringvalidator.OneOf(
										"AzureServices",
										"None",
									),
								},
							},
							"default_action": schema.StringAttribute{
								Description: "The default action when no rule from ipRules and from virtualNetworkRules match. This is only used after the bypass property has been evaluated.",
								Optional:    true,
								Computed:    true,
								Default:     stringdefault.StaticString("Allow"),
								Validators: []validator.String{
									stringvalidator.OneOf(
										"Allow",
										"Deny",
									),
								},
							},
							"ip_rules": schema.ListNestedAttribute{
								Description: "The list of IP address rules.",
								Optional:    true,
								Computed:    true,
								Default:     listdefault.StaticValue(types.ListValueMust(types.ObjectType{AttrTypes: map[string]attr.Type{"value": types.StringType}}, nil)),
								NestedObject: schema.NestedAttributeObject{
									Attributes: map[string]schema.Attribute{
										"value": schema.StringAttribute{
											Description: "An IPv4 address range in CIDR notation, such as '124.56.78.91' (simple IP address) or '124.56.78.0/24' (all addresses that start with 124.56.78).",
											Required:    true,
										},
									},
								},
							},
							"virtual_network_rules": schema.ListNestedAttribute{
								Description: "The list of virtual network rules.",
								Optional:    true,
								Computed:    true,
								Default:     listdefault.StaticValue(types.ListValueMust(types.ObjectType{AttrTypes: map[string]attr.Type{"id": types.StringType, "ignore_missing_vnet_service_endpoint": types.BoolType}}, nil)),
								NestedObject: schema.NestedAttributeObject{
									Attributes: map[string]schema.Attribute{
										"id": schema.StringAttribute{
											Description: "Full resource id of a vnet subnet, such as '/subscriptions/subid/resourceGroups/rg1/providers/Microsoft.Network/virtualNetworks/test-vnet/subnets/subnet1'.",
											Required:    true,
										},
										"ignore_missing_vnet_service_endpoint": schema.BoolAttribute{
											Description: "Property to specify whether NRP will ignore the check if parent subnet has serviceEndpoints configured.",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.Bool{
												boolplanmodifier.UseStateForUnknown(),
											},
										},
									},
								},
							},
						},
					},
					"private_endpoint_connections": schema.ListNestedAttribute{
						Description: "List of private endpoint connections associated with the key vault.",
						Computed:    true,
						PlanModifiers: []planmodifier.List{
							listplanmodifier.UseStateForUnknown(),
						},
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"etag": schema.StringAttribute{
									Description: "Modified whenever there is a change in the state of private endpoint connection.",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"id": schema.StringAttribute{
									Description: "Id of private endpoint connection.",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"properties": schema.SingleNestedAttribute{
									Description: "Private endpoint connection properties.",
									Optional:    true,
									Computed:    true,
									PlanModifiers: []planmodifier.Object{
										objectplanmodifier.UseStateForUnknown(),
									},
									Attributes: map[string]schema.Attribute{
										"private_endpoint": schema.SingleNestedAttribute{
											Description: "Properties of the private endpoint object.",
											Computed:    true,
											PlanModifiers: []planmodifier.Object{
												objectplanmodifier.UseStateForUnknown(),
											},
											Attributes: map[string]schema.Attribute{
												"id": schema.StringAttribute{
													Description: "Full identifier of the private endpoint resource.",
													Computed:    true,
													PlanModifiers: []planmodifier.String{
														stringplanmodifier.UseStateForUnknown(),
													},
												},
											},
										},
										"private_link_service_connection_state": schema.SingleNestedAttribute{
											Description: "Approval state of the private link connection.",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.Object{
												objectplanmodifier.UseStateForUnknown(),
											},
											Attributes: map[string]schema.Attribute{
												"actions_required": schema.StringAttribute{
													Description: "A message indicating if changes on the service provider require any updates on the consumer.",
													Optional:    true,
													Computed:    true,
													Validators: []validator.String{
														stringvalidator.OneOf(
															"None",
														),
													},
													PlanModifiers: []planmodifier.String{
														stringplanmodifier.UseStateForUnknown(),
													},
												},
												"description": schema.StringAttribute{
													Description: "The reason for approval or rejection.",
													Optional:    true,
													Computed:    true,
													PlanModifiers: []planmodifier.String{
														stringplanmodifier.UseStateForUnknown(),
													},
												},
												"status": schema.StringAttribute{
													Description: "Indicates whether the connection has been approved, rejected or removed by the key vault owner.",
													Optional:    true,
													Computed:    true,
													Validators: []validator.String{
														stringvalidator.OneOf(
															"Pending",
															"Approved",
															"Rejected",
															"Disconnected",
														),
													},
													PlanModifiers: []planmodifier.String{
														stringplanmodifier.UseStateForUnknown(),
													},
												},
											},
										},
										"provisioning_state": schema.StringAttribute{
											Description: "Provisioning state of the private endpoint connection.",
											Computed:    true,
											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
										},
									},
								},
							},
						},
					},
					"provisioning_state": schema.StringAttribute{
						Description: "Provisioning state of the vault.",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"Succeeded",
								"RegisteringDns",
							),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"public_network_access": schema.StringAttribute{
						Description: "Property to specify whether the vault will accept traffic from public internet. If set to 'disabled' all traffic except private endpoint traffic and that that originates from trusted services will be ...",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"Enabled",
								"Disabled",
							),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"sku": schema.SingleNestedAttribute{
						Description: "SKU details",
						Required:    true,
						Attributes: map[string]schema.Attribute{
							"family": schema.StringAttribute{
								Description: "SKU family name",
								Required:    true,
								Validators: []validator.String{
									stringvalidator.OneOf(
										"A",
									),
								},
							},
							"name": schema.StringAttribute{
								Description: "SKU name to specify whether the key vault is a standard vault or a premium vault.",
								Required:    true,
								Validators: []validator.String{
									stringvalidator.OneOf(
										"standard",
										"premium",
									),
								},
							},
						},
					},
					"soft_delete_retention_in_days": schema.Int64Attribute{
						Description: "softDelete data retention days. It accepts >=7 and <=90.",
						Optional:    true,
						Computed:    true,
						Default:     int64default.StaticInt64(90),
						Validators: []validator.Int64{
							int64validator.Between(7, 90),
						},
					},
					"tenant_id": schema.StringAttribute{
						Description: "The Azure Active Directory tenant ID that should be used for authenticating requests to the key vault.",
						Required:    true,
						Validators: []validator.String{
							stringvalidator.RegexMatches(
								regexp.MustCompile(`(?i)^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`),
								"must be a valid UUID",
							),
						},
					},
					"vault_uri": schema.StringAttribute{
						Description: "The URI of the vault for performing operations on keys and secrets.",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
				},
			},
			"system_data": schema.SingleNestedAttribute{
				Description: "Azure Resource Manager metadata containing createdBy and modifiedBy information.",
				Computed:    true,
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.UseStateForUnknown(),
				},
				Attributes: map[string]schema.Attribute{
					"created_at": schema.StringAttribute{
						Description: "The timestamp of resource creation (UTC).",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"created_by": schema.StringAttribute{
						Description: "The identity that created the resource.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"created_by_type": schema.StringAttribute{
						Description: "The type of identity that created the resource.",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"User",
								"Application",
								"ManagedIdentity",
								"Key",
							),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"last_modified_at": schema.StringAttribute{
						Description: "The timestamp of resource last modification (UTC)",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"last_modified_by": schema.StringAttribute{
						Description: "The identity that last modified the resource.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"last_modified_by_type": schema.StringAttribute{
						Description: "The type of identity that last modified the resource.",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"User",
								"Application",
								"ManagedIdentity",
								"Key",
							),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
				},
			},
			"tags": schema.MapAttribute{
				Description: "The tags that will be assigned to the key vault.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.Map{
					mapplanmodifier.UseStateForUnknown(),
				},
				ElementType: types.StringType,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				MarkdownDescription: "The ID of the Azure resource.",
			},
			"purge_on_destroy": schema.BoolAttribute{
				Optional:            true,
				MarkdownDescription: "When `true`, permanently purges the vault's soft-deleted shadow on destroy so its name can be reused immediately, instead of leaving it recoverable until Azure's retention window expires. Ignored when purge protection is enabled (Azure blocks the purge). Defaults to `false`.",
			},
		},
	}
}

// KeyVault describes azapi_key_vault for registration and config builders.
var KeyVault = services.Descriptor{
	Name:           "azapi_key_vault",
	ARMType:        "Microsoft.KeyVault/vaults",
	APIVersion:     "2026-02-01",
	Schema:         AzapiKeyVaultSchema,
	WritableScopes: 8,
	ParentAttr:     "resource_group_id",
	Timeouts: services.Timeouts{
		Create: 30 * time.Minute,
		Read:   5 * time.Minute,
		Update: 30 * time.Minute,
		Delete: 30 * time.Minute,
	},
}

func init() { services.Register(KeyVault) }
