package generator

import (
	"fmt"
	"sort"
	"strings"

	"github.com/Azure/terraform-provider-azapi/internal/azapin/naming"
)

// EmitSchema generates Go source code for a Terraform resource schema from a ResourceDefinition.
// It returns the Go source as a string.
func EmitSchema(def *ResourceDefinition) (string, error) {
	if def.Body == nil || def.Body.Kind != KindObject {
		return "", fmt.Errorf("resource %s has no object body", def.Name)
	}

	// Extract ARM resource type (without version)
	armType := def.Name
	if at := strings.Index(armType, "@"); at >= 0 {
		armType = armType[:at]
	}
	tfName := naming.ResourceName(armType)
	structName := toExportedGoName(tfName)

	var b strings.Builder

	// Header
	b.WriteString("// Code generated by azapin; DO NOT EDIT.\n")
	b.WriteString("package generated\n\n")
	b.WriteString("import (\n")
	b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/resource/schema\"\n")
	b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator\"\n")
	b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/schema/validator\"\n")
	b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/types\"\n")
	b.WriteString(")\n\n")

	// Schema function
	b.WriteString(fmt.Sprintf("// %sSchema returns the Terraform resource schema for %s.\n", structName, def.Name))
	b.WriteString(fmt.Sprintf("func %sSchema() schema.Schema {\n", structName))
	b.WriteString("\treturn schema.Schema{\n")
	b.WriteString(fmt.Sprintf("\t\tDescription: \"Manages a %s resource.\",\n", armType))
	b.WriteString("\t\tAttributes: map[string]schema.Attribute{\n")

	// Emit attributes for the body's properties
	emitAttributes(&b, def.Body, 3)

	b.WriteString("\t\t},\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n")

	return b.String(), nil
}

// isFullyComputed returns true if an ObjectType has all leaf properties ReadOnly.
// This means the block itself should be Computed-only — the user never sets any
// part of it, the server populates everything.
func isFullyComputed(typ *Type) bool {
	if typ.Kind != KindObject {
		return false
	}
	if len(typ.Properties) == 0 {
		return false // empty objects are ambiguous, treat as not fully computed
	}
	for _, prop := range typ.Properties {
		if prop.Flags.IsSystemManaged() {
			continue
		}
		if prop.Flags.IsReadOnly() {
			continue
		}
		// This property is settable. Check if it's a nested object where
		// ALL children are still ReadOnly (the property itself may be flagged
		// as Optional but contain only computed children).
		if prop.Type.Kind == KindObject {
			if !isFullyComputed(prop.Type) {
				return false
			}
			continue
		}
		// Non-ReadOnly, non-object leaf → block is not fully computed
		return false
	}
	return true
}

// hasAnySettable returns true if an ObjectType has at least one settable
// (non-ReadOnly, non-SystemManaged) leaf property.
func hasAnySettable(typ *Type) bool {
	if typ.Kind != KindObject {
		return false
	}
	for _, prop := range typ.Properties {
		if prop.Flags.IsSystemManaged() {
			continue
		}
		if !prop.Flags.IsReadOnly() {
			if prop.Type.Kind == KindObject {
				if hasAnySettable(prop.Type) {
					return true
				}
				continue
			}
			return true
		}
	}
	return false
}

// effectiveComputed determines whether a property should be Computed.
// A property is computed if:
// (a) Its own flag says ReadOnly, OR
// (b) It's an object/array whose ALL leaf descendants are ReadOnly.
func effectiveComputed(prop *Property) bool {
	if prop.Flags.IsReadOnly() {
		return true
	}
	if prop.Type.Kind == KindObject && isFullyComputed(prop.Type) {
		return true
	}
	if prop.Type.Kind == KindArray && prop.Type.ElementType != nil &&
		prop.Type.ElementType.Kind == KindObject && isFullyComputed(prop.Type.ElementType) {
		return true
	}
	return false
}

// emitAttributes writes Terraform schema attributes for an ObjectType's properties.
func emitAttributes(b *strings.Builder, objType *Type, indent int) {
	if objType.Kind != KindObject {
		return
	}

	propNames := make([]string, 0, len(objType.Properties))
	for name := range objType.Properties {
		propNames = append(propNames, name)
	}
	sort.Strings(propNames)

	tabs := strings.Repeat("\t", indent)

	for _, armName := range propNames {
		prop := objType.Properties[armName]

		// Skip system-managed properties (id, type, apiVersion)
		if prop.Flags.IsSystemManaged() {
			continue
		}

		tfName := naming.CamelToSnake(armName)
		emitAttribute(b, tfName, prop, tabs, indent)
	}
}

func emitAttribute(b *strings.Builder, tfName string, prop *Property, tabs string, indent int) {
	typ := prop.Type
	computed := effectiveComputed(prop)

	switch {
	case typ.Kind == KindString:
		b.WriteString(fmt.Sprintf("%s%q: schema.StringAttribute{\n", tabs, tfName))
		writeAttributeFlags(b, prop, computed, tabs)
		b.WriteString(fmt.Sprintf("%s},\n", tabs))

	case typ.Kind == KindBool:
		b.WriteString(fmt.Sprintf("%s%q: schema.BoolAttribute{\n", tabs, tfName))
		writeAttributeFlags(b, prop, computed, tabs)
		b.WriteString(fmt.Sprintf("%s},\n", tabs))

	case typ.Kind == KindInt:
		b.WriteString(fmt.Sprintf("%s%q: schema.Int64Attribute{\n", tabs, tfName))
		writeAttributeFlags(b, prop, computed, tabs)
		b.WriteString(fmt.Sprintf("%s},\n", tabs))

	case typ.IsEnum():
		b.WriteString(fmt.Sprintf("%s%q: schema.StringAttribute{\n", tabs, tfName))
		writeAttributeFlags(b, prop, computed, tabs)
		// Only emit validators for settable (non-computed) fields
		if !computed {
			values := typ.EnumValues()
			if len(values) > 0 {
				b.WriteString(fmt.Sprintf("%s\tValidators: []validator.String{\n", tabs))
				b.WriteString(fmt.Sprintf("%s\t\tstringvalidator.OneOf(\n", tabs))
				for _, v := range values {
					b.WriteString(fmt.Sprintf("%s\t\t\t%q,\n", tabs, v))
				}
				b.WriteString(fmt.Sprintf("%s\t\t),\n", tabs))
				b.WriteString(fmt.Sprintf("%s\t},\n", tabs))
			}
		}
		b.WriteString(fmt.Sprintf("%s},\n", tabs))

	case typ.Kind == KindObject:
		b.WriteString(fmt.Sprintf("%s%q: schema.SingleNestedAttribute{\n", tabs, tfName))
		writeAttributeFlags(b, prop, computed, tabs)
		b.WriteString(fmt.Sprintf("%s\tAttributes: map[string]schema.Attribute{\n", tabs))
		emitAttributes(b, typ, indent+2)
		b.WriteString(fmt.Sprintf("%s\t},\n", tabs))
		b.WriteString(fmt.Sprintf("%s},\n", tabs))

	case typ.Kind == KindArray:
		if typ.ElementType != nil && typ.ElementType.Kind == KindObject {
			b.WriteString(fmt.Sprintf("%s%q: schema.ListNestedAttribute{\n", tabs, tfName))
			writeAttributeFlags(b, prop, computed, tabs)
			b.WriteString(fmt.Sprintf("%s\tNestedObject: schema.NestedAttributeObject{\n", tabs))
			b.WriteString(fmt.Sprintf("%s\t\tAttributes: map[string]schema.Attribute{\n", tabs))
			emitAttributes(b, typ.ElementType, indent+3)
			b.WriteString(fmt.Sprintf("%s\t\t},\n", tabs))
			b.WriteString(fmt.Sprintf("%s\t},\n", tabs))
			b.WriteString(fmt.Sprintf("%s},\n", tabs))
		} else {
			b.WriteString(fmt.Sprintf("%s%q: schema.ListAttribute{\n", tabs, tfName))
			writeAttributeFlags(b, prop, computed, tabs)
			b.WriteString(fmt.Sprintf("%s\tElementType: types.StringType,\n", tabs))
			b.WriteString(fmt.Sprintf("%s},\n", tabs))
		}

	case typ.Kind == KindUnion:
		// Non-enum union → treat as string for now
		b.WriteString(fmt.Sprintf("%s%q: schema.StringAttribute{\n", tabs, tfName))
		writeAttributeFlags(b, prop, computed, tabs)
		b.WriteString(fmt.Sprintf("%s},\n", tabs))

	default:
		// KindAny, unknown → dynamic attribute
		b.WriteString(fmt.Sprintf("%s%q: schema.DynamicAttribute{\n", tabs, tfName))
		writeAttributeFlags(b, prop, computed, tabs)
		b.WriteString(fmt.Sprintf("%s},\n", tabs))
	}
}

// writeAttributeFlags emits the Required/Optional/Computed flags for an attribute.
//
// Rules:
//   - Required flag set → Required: true
//   - Computed (ReadOnly or all-children-ReadOnly) → Computed: true only
//   - Otherwise → Optional: true (no Computed, since value doesn't come from server
//     unless we know a default; Computed is added only when the property also appears
//     in GET responses with server-populated data)
func writeAttributeFlags(b *strings.Builder, prop *Property, computed bool, tabs string) {
	if prop.Description != "" {
		desc := strings.ReplaceAll(prop.Description, `"`, `\"`)
		if len(desc) > 200 {
			desc = desc[:200] + "..."
		}
		b.WriteString(fmt.Sprintf("%s\tDescription: %q,\n", tabs, desc))
	}
	if prop.Flags.IsRequired() {
		b.WriteString(fmt.Sprintf("%s\tRequired: true,\n", tabs))
	} else if computed {
		b.WriteString(fmt.Sprintf("%s\tComputed: true,\n", tabs))
	} else {
		b.WriteString(fmt.Sprintf("%s\tOptional: true,\n", tabs))
	}
	if prop.Flags.IsWriteOnly() {
		b.WriteString(fmt.Sprintf("%s\tSensitive: true,\n", tabs))
	}
}

// toExportedGoName converts "azapi_storage_account" to "AzapiStorageAccount"
func toExportedGoName(tfName string) string {
	parts := strings.Split(tfName, "_")
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return b.String()
}
