package generator

import (
	"fmt"
	"sort"
	"strings"

	"github.com/Azure/terraform-provider-azapi/internal/azapin/naming"
)

// EmitSchema generates Go source code for a Terraform resource schema from a ResourceDefinition.
// It returns the Go source as a string.
func EmitSchema(def *ResourceDefinition) (string, error) {
	if def.Body == nil || def.Body.Kind != KindObject {
		return "", fmt.Errorf("resource %s has no object body", def.Name)
	}

	// Extract ARM resource type (without version)
	armType := def.Name
	if at := strings.Index(armType, "@"); at >= 0 {
		armType = armType[:at]
	}
	tfName := naming.ResourceName(armType)
	structName := toExportedGoName(tfName)

	// Pre-scan to determine which imports are needed
	needs := scanImportNeeds(def.Body)

	var b strings.Builder

	// Header
	b.WriteString("// Code generated by azapin; DO NOT EDIT.\n")
	b.WriteString("package generated\n\n")
	b.WriteString("import (\n")
	if needs.regexp {
		b.WriteString("\t\"regexp\"\n\n")
	}
	b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/resource/schema\"\n")
	if needs.int64Validator {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework-validators/int64validator\"\n")
	}
	if needs.stringValidator {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator\"\n")
	}
	if needs.planmodifier {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier\"\n")
	}
	if needs.pmString {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier\"\n")
	}
	if needs.pmBool {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier\"\n")
	}
	if needs.pmInt64 {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier\"\n")
	}
	if needs.pmObject {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier\"\n")
	}
	if needs.pmList {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier\"\n")
	}
	if needs.stringValidator || needs.int64Validator {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/schema/validator\"\n")
	}
	if needs.types {
		b.WriteString("\t\"github.com/hashicorp/terraform-plugin-framework/types\"\n")
	}
	if needs.defaults {
		b.WriteString("\tazapinschema \"github.com/Azure/terraform-provider-azapi/internal/azapin/schema\"\n")
	}
	b.WriteString(")\n\n")

	// Schema function
	b.WriteString(fmt.Sprintf("// %sSchema returns the Terraform resource schema for %s.\n", structName, def.Name))
	b.WriteString(fmt.Sprintf("func %sSchema() schema.Schema {\n", structName))
	b.WriteString("\treturn schema.Schema{\n")
	b.WriteString(fmt.Sprintf("\t\tDescription: \"Manages a %s resource. [azapin:%s]\",\n", armType, def.Name))
	b.WriteString("\t\tAttributes: map[string]schema.Attribute{\n")

	// Emit attributes for the body's properties
	emitAttributes(&b, def.Body, 3)

	b.WriteString("\t\t},\n")
	b.WriteString("\t}\n")
	b.WriteString("}\n\n")

	// Registration
	b.WriteString(fmt.Sprintf("func init() {\n"))
	b.WriteString(fmt.Sprintf("\tRegister(%q, %sSchema)\n", tfName, structName))
	b.WriteString("}\n")

	return b.String(), nil
}

type importNeeds struct {
	regexp          bool
	int64Validator  bool
	stringValidator bool
	types           bool // for types.StringType in ListAttribute
	defaults        bool // for azapinschema.Static*
	planmodifier    bool // for planmodifier.X plan-modifier slices
	pmString        bool // stringplanmodifier
	pmBool          bool // boolplanmodifier
	pmInt64         bool // int64planmodifier
	pmObject        bool // objectplanmodifier
	pmList          bool // listplanmodifier
}

func scanImportNeeds(typ *Type) importNeeds {
	var needs importNeeds
	scanImportNeedsRecurse(typ, &needs)
	return needs
}

func scanImportNeedsRecurse(typ *Type, needs *importNeeds) {
	if typ == nil || typ.Kind != KindObject {
		return
	}
	for _, prop := range typ.Properties {
		if prop.Flags.IsSystemManaged() {
			continue
		}
		computed := effectiveComputed(prop)
		if prop.DefaultValue != "" {
			needs.defaults = true
		}
		for _, v := range prop.Validators {
			switch v.Kind {
			case ValidatorArmResourceID, ValidatorRegex:
				needs.regexp = true
				needs.stringValidator = true
			case ValidatorStringOneOf, ValidatorStringLength:
				needs.stringValidator = true
			case ValidatorIntRange:
				needs.int64Validator = true
			}
		}
		if prop.Type.IsEnum() && !computed {
			needs.stringValidator = true
		}
		if prop.Type.Kind == KindArray && (prop.Type.ElementType == nil || prop.Type.ElementType.Kind != KindObject) {
			needs.types = true
		}
		// ForceNew plan modifiers
		if prop.ForceNew && !computed {
			if pkg, _ := forceNewModifier(prop); pkg != "" {
				needs.planmodifier = true
				switch pkg {
				case "stringplanmodifier":
					needs.pmString = true
				case "boolplanmodifier":
					needs.pmBool = true
				case "int64planmodifier":
					needs.pmInt64 = true
				case "objectplanmodifier":
					needs.pmObject = true
				case "listplanmodifier":
					needs.pmList = true
				}
			}
		}
		if prop.Type.Kind == KindObject {
			scanImportNeedsRecurse(prop.Type, needs)
		}
		if prop.Type.Kind == KindArray && prop.Type.ElementType != nil && prop.Type.ElementType.Kind == KindObject {
			scanImportNeedsRecurse(prop.Type.ElementType, needs)
		}
	}
}

// isFullyComputed returns true if an ObjectType has all leaf properties ReadOnly.
// This means the block itself should be Computed-only — the user never sets any
// part of it, the server populates everything.
func isFullyComputed(typ *Type) bool {
	if typ.Kind != KindObject {
		return false
	}
	if len(typ.Properties) == 0 {
		return false // empty objects are ambiguous, treat as not fully computed
	}
	for _, prop := range typ.Properties {
		if prop.Flags.IsSystemManaged() {
			continue
		}
		if prop.Flags.IsReadOnly() {
			continue
		}
		// This property is settable. Check if it's a nested object where
		// ALL children are still ReadOnly (the property itself may be flagged
		// as Optional but contain only computed children).
		if prop.Type.Kind == KindObject {
			if !isFullyComputed(prop.Type) {
				return false
			}
			continue
		}
		// Non-ReadOnly, non-object leaf → block is not fully computed
		return false
	}
	return true
}

// effectiveComputed determines whether a property should be Computed.
// A property is computed if:
// (a) Its own flag says ReadOnly, OR
// (b) It's an object/array whose ALL leaf descendants are ReadOnly.
func effectiveComputed(prop *Property) bool {
	if prop.ForceComputed {
		return true // azwise: explicitly read-only in AzureRM
	}
	if prop.Flags.IsReadOnly() {
		return true
	}
	if prop.Type.Kind == KindObject && isFullyComputed(prop.Type) {
		return true
	}
	if prop.Type.Kind == KindArray && prop.Type.ElementType != nil &&
		prop.Type.ElementType.Kind == KindObject && isFullyComputed(prop.Type.ElementType) {
		return true
	}
	return false
}

// emitAttributes writes Terraform schema attributes for an ObjectType's properties.
func emitAttributes(b *strings.Builder, objType *Type, indent int) {
	if objType.Kind != KindObject {
		return
	}

	propNames := make([]string, 0, len(objType.Properties))
	for name := range objType.Properties {
		propNames = append(propNames, name)
	}
	sort.Strings(propNames)

	tabs := strings.Repeat("\t", indent)

	for _, armName := range propNames {
		prop := objType.Properties[armName]

		// Skip system-managed properties (id, type, apiVersion)
		if prop.Flags.IsSystemManaged() {
			continue
		}

		tfName := naming.CamelToSnake(armName)
		emitAttribute(b, tfName, prop, tabs, indent)
	}
}

func emitAttribute(b *strings.Builder, tfName string, prop *Property, tabs string, indent int) {
	typ := prop.Type
	computed := effectiveComputed(prop)

	switch {
	case typ.Kind == KindString:
		b.WriteString(fmt.Sprintf("%s%q: schema.StringAttribute{\n", tabs, tfName))
		writeAttributeFlags(b, prop, computed, tabs)
		if !computed {
			emitDescriptionStringValidators(b, prop, tabs)
		}
		emitForceNew(b, prop, computed, tabs)
		b.WriteString(fmt.Sprintf("%s},\n", tabs))

	case typ.Kind == KindBool:
		b.WriteString(fmt.Sprintf("%s%q: schema.BoolAttribute{\n", tabs, tfName))
		writeAttributeFlags(b, prop, computed, tabs)
		emitForceNew(b, prop, computed, tabs)
		b.WriteString(fmt.Sprintf("%s},\n", tabs))

	case typ.Kind == KindInt:
		b.WriteString(fmt.Sprintf("%s%q: schema.Int64Attribute{\n", tabs, tfName))
		writeAttributeFlags(b, prop, computed, tabs)
		if !computed {
			emitDescriptionInt64Validators(b, prop, tabs)
		}
		emitForceNew(b, prop, computed, tabs)
		b.WriteString(fmt.Sprintf("%s},\n", tabs))

	case typ.IsEnum():
		b.WriteString(fmt.Sprintf("%s%q: schema.StringAttribute{\n", tabs, tfName))
		writeAttributeFlags(b, prop, computed, tabs)
		// Only emit validators for settable (non-computed) fields
		if !computed {
			values := typ.EnumValues()
			if len(values) > 0 {
				b.WriteString(fmt.Sprintf("%s\tValidators: []validator.String{\n", tabs))
				b.WriteString(fmt.Sprintf("%s\t\tstringvalidator.OneOf(\n", tabs))
				for _, v := range values {
					b.WriteString(fmt.Sprintf("%s\t\t\t%q,\n", tabs, v))
				}
				b.WriteString(fmt.Sprintf("%s\t\t),\n", tabs))
				b.WriteString(fmt.Sprintf("%s\t},\n", tabs))
			}
		}
		emitForceNew(b, prop, computed, tabs)
		b.WriteString(fmt.Sprintf("%s},\n", tabs))

	case typ.Kind == KindObject:
		b.WriteString(fmt.Sprintf("%s%q: schema.SingleNestedAttribute{\n", tabs, tfName))
		writeAttributeFlags(b, prop, computed, tabs)
		emitForceNew(b, prop, computed, tabs)
		b.WriteString(fmt.Sprintf("%s\tAttributes: map[string]schema.Attribute{\n", tabs))
		emitAttributes(b, typ, indent+2)
		b.WriteString(fmt.Sprintf("%s\t},\n", tabs))
		b.WriteString(fmt.Sprintf("%s},\n", tabs))

	case typ.Kind == KindArray:
		if typ.ElementType != nil && typ.ElementType.Kind == KindObject {
			b.WriteString(fmt.Sprintf("%s%q: schema.ListNestedAttribute{\n", tabs, tfName))
			writeAttributeFlags(b, prop, computed, tabs)
			emitForceNew(b, prop, computed, tabs)
			b.WriteString(fmt.Sprintf("%s\tNestedObject: schema.NestedAttributeObject{\n", tabs))
			b.WriteString(fmt.Sprintf("%s\t\tAttributes: map[string]schema.Attribute{\n", tabs))
			emitAttributes(b, typ.ElementType, indent+3)
			b.WriteString(fmt.Sprintf("%s\t\t},\n", tabs))
			b.WriteString(fmt.Sprintf("%s\t},\n", tabs))
			b.WriteString(fmt.Sprintf("%s},\n", tabs))
		} else {
			b.WriteString(fmt.Sprintf("%s%q: schema.ListAttribute{\n", tabs, tfName))
			writeAttributeFlags(b, prop, computed, tabs)
			emitForceNew(b, prop, computed, tabs)
			b.WriteString(fmt.Sprintf("%s\tElementType: %s,\n", tabs, listElementType(typ.ElementType)))
			b.WriteString(fmt.Sprintf("%s},\n", tabs))
		}

	case typ.Kind == KindUnion:
		// Non-enum union → treat as string for now
		b.WriteString(fmt.Sprintf("%s%q: schema.StringAttribute{\n", tabs, tfName))
		writeAttributeFlags(b, prop, computed, tabs)
		emitForceNew(b, prop, computed, tabs)
		b.WriteString(fmt.Sprintf("%s},\n", tabs))

	default:
		// KindAny, unknown → dynamic attribute (no RequiresReplace modifier available)
		b.WriteString(fmt.Sprintf("%s%q: schema.DynamicAttribute{\n", tabs, tfName))
		writeAttributeFlags(b, prop, computed, tabs)
		b.WriteString(fmt.Sprintf("%s},\n", tabs))
	}
}

// emitForceNew writes a type-appropriate RequiresReplace plan modifier when the
// property is azwise-flagged ForceNew and settable. Computed-only attributes get
// no modifier (the user can't change them).
func emitForceNew(b *strings.Builder, prop *Property, computed bool, tabs string) {
	if !prop.ForceNew || computed {
		return
	}
	pkg, typ := forceNewModifier(prop)
	if pkg == "" {
		return
	}
	b.WriteString(fmt.Sprintf("%s\tPlanModifiers: []planmodifier.%s{\n", tabs, typ))
	b.WriteString(fmt.Sprintf("%s\t\t%s.RequiresReplace(),\n", tabs, pkg))
	b.WriteString(fmt.Sprintf("%s\t},\n", tabs))
}

// forceNewModifier returns the plan-modifier package and framework type for a
// property's effective attribute kind. Empty package = no modifier available.
func forceNewModifier(prop *Property) (pkg, typ string) {
	switch {
	case prop.Type.Kind == KindString, prop.Type.IsEnum(), prop.Type.Kind == KindUnion:
		return "stringplanmodifier", "String"
	case prop.Type.Kind == KindBool:
		return "boolplanmodifier", "Bool"
	case prop.Type.Kind == KindInt:
		return "int64planmodifier", "Int64"
	case prop.Type.Kind == KindObject:
		return "objectplanmodifier", "Object"
	case prop.Type.Kind == KindArray:
		return "listplanmodifier", "List"
	}
	return "", ""
}

// writeAttributeFlags emits the Required/Optional/Computed flags for an attribute.
//
// Rules:
//   - Required flag set → Required: true
//   - Computed (ReadOnly or all-children-ReadOnly) → Computed: true only
//   - Has default value → Optional: true + Default (not Computed)
//   - Default → Optional: true, Computed: true (safe default)
func writeAttributeFlags(b *strings.Builder, prop *Property, computed bool, tabs string) {
	if prop.Description != "" {
		desc := strings.ReplaceAll(prop.Description, `"`, `\"`)
		if len(desc) > 200 {
			desc = desc[:200] + "..."
		}
		b.WriteString(fmt.Sprintf("%s\tDescription: %q,\n", tabs, desc))
	}
	if prop.Flags.IsRequired() {
		b.WriteString(fmt.Sprintf("%s\tRequired: true,\n", tabs))
	} else if computed {
		b.WriteString(fmt.Sprintf("%s\tComputed: true,\n", tabs))
	} else if prop.DefaultValue != "" {
		// Known default → Optional with Default, no Computed needed
		b.WriteString(fmt.Sprintf("%s\tOptional: true,\n", tabs))
		emitDefault(b, prop, tabs)
	} else {
		b.WriteString(fmt.Sprintf("%s\tOptional: true,\n", tabs))
		b.WriteString(fmt.Sprintf("%s\tComputed: true,\n", tabs))
	}
	if prop.Flags.IsWriteOnly() || prop.Sensitive {
		b.WriteString(fmt.Sprintf("%s\tSensitive: true,\n", tabs))
	}
}

// listElementType returns the Terraform element type expression for a non-object
// array element. Defaults to types.StringType for unknown/union element kinds.
func listElementType(elem *Type) string {
	if elem != nil {
		switch elem.Kind {
		case KindBool:
			return "types.BoolType"
		case KindInt:
			return "types.Int64Type"
		}
	}
	return "types.StringType"
}

// emitDefault writes a Default plan modifier for the property's type.
func emitDefault(b *strings.Builder, prop *Property, tabs string) {
	switch prop.Type.Kind {
	case KindBool:
		b.WriteString(fmt.Sprintf("%s\tDefault: azapinschema.StaticBool(%s),\n", tabs, prop.DefaultValue))
	case KindString:
		b.WriteString(fmt.Sprintf("%s\tDefault: azapinschema.StaticString(%q),\n", tabs, prop.DefaultValue))
	case KindInt:
		b.WriteString(fmt.Sprintf("%s\tDefault: azapinschema.StaticInt64(%s),\n", tabs, prop.DefaultValue))
	default:
		if prop.Type.IsEnum() {
			b.WriteString(fmt.Sprintf("%s\tDefault: azapinschema.StaticString(%q),\n", tabs, prop.DefaultValue))
		} else {
			// Unknown type with default — fall back to Computed
			b.WriteString(fmt.Sprintf("%s\tComputed: true,\n", tabs))
		}
	}
}

// emitDescriptionStringValidators emits validators extracted from property descriptions.
func emitDescriptionStringValidators(b *strings.Builder, prop *Property, tabs string) {
	if len(prop.Validators) == 0 {
		return
	}

	var items []string
	for _, v := range prop.Validators {
		switch v.Kind {
		case ValidatorArmResourceID:
			items = append(items, fmt.Sprintf(
				"%s\t\tstringvalidator.RegexMatches(\n%s\t\t\tregexp.MustCompile(`^/subscriptions/[^/]+/resourceGroups/[^/]+/providers/`),\n%s\t\t\t%q,\n%s\t\t)",
				tabs, tabs, tabs, v.Message, tabs))
		case ValidatorRegex:
			if v.Pattern != "" {
				items = append(items, fmt.Sprintf(
					"%s\t\tstringvalidator.RegexMatches(\n%s\t\t\tregexp.MustCompile(`%s`),\n%s\t\t\t%q,\n%s\t\t)",
					tabs, tabs, v.Pattern, tabs, v.Message, tabs))
			}
		case ValidatorStringOneOf:
			if len(v.Allowed) > 0 {
				var sb strings.Builder
				sb.WriteString(fmt.Sprintf("%s\t\tstringvalidator.OneOf(\n", tabs))
				for _, av := range v.Allowed {
					sb.WriteString(fmt.Sprintf("%s\t\t\t%q,\n", tabs, av))
				}
				sb.WriteString(fmt.Sprintf("%s\t\t)", tabs))
				items = append(items, sb.String())
			}
		case ValidatorStringLength:
			switch {
			case v.Min != nil && v.Max != nil:
				items = append(items, fmt.Sprintf("%s\t\tstringvalidator.LengthBetween(%d, %d)", tabs, *v.Min, *v.Max))
			case v.Min != nil:
				items = append(items, fmt.Sprintf("%s\t\tstringvalidator.LengthAtLeast(%d)", tabs, *v.Min))
			case v.Max != nil:
				items = append(items, fmt.Sprintf("%s\t\tstringvalidator.LengthAtMost(%d)", tabs, *v.Max))
			}
		}
	}

	if len(items) > 0 {
		b.WriteString(fmt.Sprintf("%s\tValidators: []validator.String{\n", tabs))
		for _, item := range items {
			b.WriteString(item + ",\n")
		}
		b.WriteString(fmt.Sprintf("%s\t},\n", tabs))
	}
}

// emitDescriptionInt64Validators emits int64 validators extracted from descriptions.
func emitDescriptionInt64Validators(b *strings.Builder, prop *Property, tabs string) {
	if len(prop.Validators) == 0 {
		return
	}

	var items []string
	for _, v := range prop.Validators {
		if v.Kind != ValidatorIntRange {
			continue
		}
		if v.Min != nil && v.Max != nil {
			items = append(items, fmt.Sprintf(
				"%s\t\tint64validator.Between(%d, %d)", tabs, *v.Min, *v.Max))
		} else if v.Min != nil {
			items = append(items, fmt.Sprintf(
				"%s\t\tint64validator.AtLeast(%d)", tabs, *v.Min))
		} else if v.Max != nil {
			items = append(items, fmt.Sprintf(
				"%s\t\tint64validator.AtMost(%d)", tabs, *v.Max))
		}
	}

	if len(items) > 0 {
		b.WriteString(fmt.Sprintf("%s\tValidators: []validator.Int64{\n", tabs))
		for _, item := range items {
			b.WriteString(item + ",\n")
		}
		b.WriteString(fmt.Sprintf("%s\t},\n", tabs))
	}
}

// toExportedGoName converts "azapi_storage_account" to "AzapiStorageAccount"
func toExportedGoName(tfName string) string {
	parts := strings.Split(tfName, "_")
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return b.String()
}
