// Code generated by azapin; DO NOT EDIT.
package resources

import (
	"time"

	"regexp"

	nativeschema "github.com/Azure/terraform-provider-azapi/internal/native/schema"
	"github.com/Azure/terraform-provider-azapi/internal/native/services"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/mapplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// AzapiResourcesDeploymentScriptSchema returns the Terraform resource schema for Microsoft.Resources/deploymentScripts@2023-08-01.
func AzapiResourcesDeploymentScriptSchema() schema.Schema {
	return schema.Schema{
		Description: "Manages a Microsoft.Resources/deploymentScripts resource. [azapin:Microsoft.Resources/deploymentScripts@2023-08-01]",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 260),
					stringvalidator.RegexMatches(
						regexp.MustCompile(`^[a-zA-Z0-9_().-]{0,259}[a-zA-Z0-9_()-]$`),
						"deployment script name must be 1-260 characters of alphanumerics, underscore, parentheses, hyphen, and period, and cannot end with a period",
					),
				},
				MarkdownDescription: "Specifies the name of the Azure resource.",
			},
			"resource_group_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Validators: []validator.String{
					stringvalidator.RegexMatches(
						regexp.MustCompile(`(?i)^/subscriptions/[^/]+/resourceGroups/[^/]+$`),
						"resource_group_id must be a resource group ID (/subscriptions/{id}/resourceGroups/{name})",
					),
				},
				MarkdownDescription: "The ID of the parent resource that contains this resource.",
			},
			"identity": schema.SingleNestedAttribute{
				Description: "Optional property. Managed identity to be used for this deployment script. Currently, only user-assigned MSI is supported.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.UseStateForUnknown(),
					objectplanmodifier.RequiresReplace(),
				},
				Attributes: map[string]schema.Attribute{
					"tenant_id": schema.StringAttribute{
						Description: "The tenant id of the managed identity.",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"type": schema.StringAttribute{
						Description: "Type of the managed identity.",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"UserAssigned",
							),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"user_assigned_identities": schema.MapNestedAttribute{
						Description: "The list of user-assigned managed identities associated with the resource. Key is the Azure resource Id of the managed identity.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.Map{
							mapplanmodifier.UseStateForUnknown(),
						},
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"client_id": schema.StringAttribute{
									Description: "Client App Id associated with this identity.",
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
								"principal_id": schema.StringAttribute{
									Description: "Azure Active Directory principal ID associated with this identity.",
									Computed:    true,
									PlanModifiers: []planmodifier.String{
										stringplanmodifier.UseStateForUnknown(),
									},
								},
							},
						},
					},
				},
			},
			"location": schema.StringAttribute{
				Description: "The geo-location where the resource lives",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					nativeschema.UseStateForEquivalentLocation(),
					stringplanmodifier.RequiresReplace(),
				},
			},
			"system_data": schema.SingleNestedAttribute{
				Description: "Azure Resource Manager metadata containing createdBy and modifiedBy information.",
				Computed:    true,
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.UseStateForUnknown(),
				},
				Attributes: map[string]schema.Attribute{
					"created_at": schema.StringAttribute{
						Description: "The timestamp of resource creation (UTC).",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"created_by": schema.StringAttribute{
						Description: "The identity that created the resource.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"created_by_type": schema.StringAttribute{
						Description: "The type of identity that created the resource.",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"User",
								"Application",
								"ManagedIdentity",
								"Key",
							),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"last_modified_at": schema.StringAttribute{
						Description: "The timestamp of resource last modification (UTC)",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"last_modified_by": schema.StringAttribute{
						Description: "The identity that last modified the resource.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"last_modified_by_type": schema.StringAttribute{
						Description: "The type of identity that last modified the resource.",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"User",
								"Application",
								"ManagedIdentity",
								"Key",
							),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
				},
			},
			"tags": schema.MapAttribute{
				Description: "Resource tags.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.Map{
					mapplanmodifier.UseStateForUnknown(),
				},
				ElementType: types.StringType,
			},
			"azure_cli": schema.SingleNestedAttribute{
				Description: "Variant \\\"AzureCLI\\\" of the discriminated type.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.Object{
					nativeschema.DiscriminatedVariant("azure_power_shell"),
				},
				Attributes: map[string]schema.Attribute{
					"properties": schema.SingleNestedAttribute{
						Description: "Properties of the Azure CLI script object.",
						Required:    true,
						Attributes: map[string]schema.Attribute{
							"arguments": schema.StringAttribute{
								Description: "Command line arguments to pass to the script. Arguments are separated by spaces. ex: -Name blue* -Location 'West US 2'",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
									stringplanmodifier.RequiresReplace(),
								},
							},
							"az_cli_version": schema.StringAttribute{
								Description: "Azure CLI module version to be used.",
								Required:    true,
								Validators: []validator.String{
									stringvalidator.RegexMatches(
										regexp.MustCompile(`^\d+\.\d+\.\d+$`),
										"az_cli_version should be in the format X.Y.Z (e.g. 2.30.0)",
									),
								},
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.RequiresReplace(),
								},
							},
							"cleanup_preference": schema.StringAttribute{
								Description: "The clean up preference when the script execution gets in a terminal state. Default setting is 'Always'.",
								Optional:    true,
								Computed:    true,
								Default:     stringdefault.StaticString("Always"),
								Validators: []validator.String{
									stringvalidator.OneOf(
										"Always",
										"OnSuccess",
										"OnExpiration",
									),
								},
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.RequiresReplace(),
								},
							},
							"container_settings": schema.SingleNestedAttribute{
								Description: "Container settings.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.Object{
									objectplanmodifier.UseStateForUnknown(),
									objectplanmodifier.RequiresReplace(),
								},
								Attributes: map[string]schema.Attribute{
									"container_group_name": schema.StringAttribute{
										Description: "Container group name, if not specified then the name will get auto-generated. Not specifying a 'containerGroupName' indicates the system to generate a unique name which might end up flagging an Azure ...",
										Optional:    true,
										Computed:    true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
										},
									},
									"subnet_ids": schema.ListNestedAttribute{
										Description: "The subnet resource IDs for a container group.",
										Optional:    true,
										Computed:    true,
										PlanModifiers: []planmodifier.List{
											listplanmodifier.UseStateForUnknown(),
										},
										NestedObject: schema.NestedAttributeObject{
											Attributes: map[string]schema.Attribute{
												"id": schema.StringAttribute{
													Description: "Resource ID of subnet.",
													Required:    true,
												},
												"name": schema.StringAttribute{
													Description: "Friendly name for the subnet.",
													Optional:    true,
													Computed:    true,
													PlanModifiers: []planmodifier.String{
														stringplanmodifier.UseStateForUnknown(),
													},
												},
											},
										},
									},
								},
							},
							"environment_variables": schema.ListNestedAttribute{
								Description: "The environment variables to pass over to the script.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.List{
									listplanmodifier.UseStateForUnknown(),
									listplanmodifier.RequiresReplace(),
								},
								NestedObject: schema.NestedAttributeObject{
									Attributes: map[string]schema.Attribute{
										"name": schema.StringAttribute{
											Description: "The name of the environment variable.",
											Required:    true,
										},
										"secure_value": schema.StringAttribute{
											Description: "The value of the secure environment variable.",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
										},
										"value": schema.StringAttribute{
											Description: "The value of the environment variable.",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
										},
									},
								},
							},
							"force_update_tag": schema.StringAttribute{
								Description: "Gets or sets how the deployment script should be forced to execute even if the script resource has not changed. Can be current time stamp or a GUID.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
									stringplanmodifier.RequiresReplace(),
								},
							},
							"outputs": schema.MapAttribute{
								Description: "List of script outputs.",
								Computed:    true,
								PlanModifiers: []planmodifier.Map{
									mapplanmodifier.UseStateForUnknown(),
								},
								ElementType: types.StringType,
							},
							"primary_script_uri": schema.StringAttribute{
								Description: "Uri for the script. This is the entry point for the external script.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
									stringplanmodifier.RequiresReplace(),
								},
							},
							"provisioning_state": schema.StringAttribute{
								Description: "State of the script execution. This only appears in the response.",
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"retention_interval": schema.StringAttribute{
								Description: "Interval for which the service retains the script resource after it reaches a terminal state. Resource will be deleted when this duration expires. Duration is based on ISO 8601 pattern (for example P1...",
								Required:    true,
								Validators: []validator.String{
									stringvalidator.RegexMatches(
										regexp.MustCompile(`^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$`),
										"must be in datetime format yyyy-MM-ddTHH:mm:ssZ",
									),
								},
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.RequiresReplace(),
								},
							},
							"script_content": schema.StringAttribute{
								Description: "Script body.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
									stringplanmodifier.RequiresReplace(),
								},
							},
							"status": schema.SingleNestedAttribute{
								Description: "Contains the results of script execution.",
								Computed:    true,
								PlanModifiers: []planmodifier.Object{
									objectplanmodifier.UseStateForUnknown(),
								},
								Attributes: map[string]schema.Attribute{
									"container_instance_id": schema.StringAttribute{
										Description: "ACI resource Id.",
										Computed:    true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
										},
									},
									"end_time": schema.StringAttribute{
										Description: "End time of the script execution.",
										Computed:    true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
										},
									},
									"error": schema.SingleNestedAttribute{
										Description: "Error that is relayed from the script execution.",
										Required:    true,
										Attributes: map[string]schema.Attribute{
											"additional_info": schema.ListNestedAttribute{
												Description: "The error additional info.",
												Computed:    true,
												PlanModifiers: []planmodifier.List{
													listplanmodifier.UseStateForUnknown(),
												},
												NestedObject: schema.NestedAttributeObject{
													Attributes: map[string]schema.Attribute{
														"info": schema.StringAttribute{
															Description: "The additional info.",
															Computed:    true,
														},
														"type": schema.StringAttribute{
															Description: "The additional info type.",
															Computed:    true,
															PlanModifiers: []planmodifier.String{
																stringplanmodifier.UseStateForUnknown(),
															},
														},
													},
												},
											},
											"code": schema.StringAttribute{
												Description: "The error code.",
												Computed:    true,
												PlanModifiers: []planmodifier.String{
													stringplanmodifier.UseStateForUnknown(),
												},
											},
											"details": schema.ListAttribute{
												Description: "The error details.",
												Computed:    true,
												PlanModifiers: []planmodifier.List{
													listplanmodifier.UseStateForUnknown(),
												},
												ElementType: types.StringType,
											},
											"message": schema.StringAttribute{
												Description: "The error message.",
												Computed:    true,
												PlanModifiers: []planmodifier.String{
													stringplanmodifier.UseStateForUnknown(),
												},
											},
											"target": schema.StringAttribute{
												Description: "The error target.",
												Computed:    true,
												PlanModifiers: []planmodifier.String{
													stringplanmodifier.UseStateForUnknown(),
												},
											},
										},
									},
									"expiration_time": schema.StringAttribute{
										Description: "Time the deployment script resource will expire.",
										Computed:    true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
										},
									},
									"start_time": schema.StringAttribute{
										Description: "Start time of the script execution.",
										Computed:    true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
										},
									},
									"storage_account_id": schema.StringAttribute{
										Description: "Storage account resource Id.",
										Computed:    true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
										},
									},
								},
							},
							"storage_account_settings": schema.SingleNestedAttribute{
								Description: "Storage Account settings.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.Object{
									objectplanmodifier.UseStateForUnknown(),
									objectplanmodifier.RequiresReplace(),
								},
								Attributes: map[string]schema.Attribute{
									"storage_account_key": schema.StringAttribute{
										Description: "The storage account access key.",
										Optional:    true,
										Computed:    true,
										Sensitive:   true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
										},
									},
									"storage_account_name": schema.StringAttribute{
										Description: "The storage account name.",
										Optional:    true,
										Computed:    true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
										},
									},
								},
							},
							"supporting_script_uris": schema.ListAttribute{
								Description: "Supporting files for the external script.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.List{
									listplanmodifier.UseStateForUnknown(),
									listplanmodifier.RequiresReplace(),
								},
								ElementType: types.StringType,
							},
							"timeout": schema.StringAttribute{
								Description: "Maximum allowed script execution time specified in ISO 8601 format. Default value is P1D",
								Optional:    true,
								Computed:    true,
								Default:     stringdefault.StaticString("P1D"),
								Validators: []validator.String{
									stringvalidator.RegexMatches(
										regexp.MustCompile(`^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$`),
										"must be in datetime format yyyy-MM-ddTHH:mm:ssZ",
									),
								},
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.RequiresReplace(),
								},
							},
						},
					},
				},
			},
			"azure_power_shell": schema.SingleNestedAttribute{
				Description: "Variant \\\"AzurePowerShell\\\" of the discriminated type.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.Object{
					nativeschema.DiscriminatedVariant("azure_cli"),
				},
				Attributes: map[string]schema.Attribute{
					"properties": schema.SingleNestedAttribute{
						Description: "Properties of the Azure PowerShell script object.",
						Required:    true,
						Attributes: map[string]schema.Attribute{
							"arguments": schema.StringAttribute{
								Description: "Command line arguments to pass to the script. Arguments are separated by spaces. ex: -Name blue* -Location 'West US 2'",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
									stringplanmodifier.RequiresReplace(),
								},
							},
							"az_power_shell_version": schema.StringAttribute{
								Description: "Azure PowerShell module version to be used.",
								Required:    true,
								Validators: []validator.String{
									stringvalidator.RegexMatches(
										regexp.MustCompile(`^\d+\.\d+$`),
										"az_power_shell_version should be in the format X.Y (e.g. 9.7)",
									),
								},
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.RequiresReplace(),
								},
							},
							"cleanup_preference": schema.StringAttribute{
								Description: "The clean up preference when the script execution gets in a terminal state. Default setting is 'Always'.",
								Optional:    true,
								Computed:    true,
								Default:     stringdefault.StaticString("Always"),
								Validators: []validator.String{
									stringvalidator.OneOf(
										"Always",
										"OnSuccess",
										"OnExpiration",
									),
								},
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.RequiresReplace(),
								},
							},
							"container_settings": schema.SingleNestedAttribute{
								Description: "Container settings.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.Object{
									objectplanmodifier.UseStateForUnknown(),
									objectplanmodifier.RequiresReplace(),
								},
								Attributes: map[string]schema.Attribute{
									"container_group_name": schema.StringAttribute{
										Description: "Container group name, if not specified then the name will get auto-generated. Not specifying a 'containerGroupName' indicates the system to generate a unique name which might end up flagging an Azure ...",
										Optional:    true,
										Computed:    true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
										},
									},
									"subnet_ids": schema.ListNestedAttribute{
										Description: "The subnet resource IDs for a container group.",
										Optional:    true,
										Computed:    true,
										PlanModifiers: []planmodifier.List{
											listplanmodifier.UseStateForUnknown(),
										},
										NestedObject: schema.NestedAttributeObject{
											Attributes: map[string]schema.Attribute{
												"id": schema.StringAttribute{
													Description: "Resource ID of subnet.",
													Required:    true,
												},
												"name": schema.StringAttribute{
													Description: "Friendly name for the subnet.",
													Optional:    true,
													Computed:    true,
													PlanModifiers: []planmodifier.String{
														stringplanmodifier.UseStateForUnknown(),
													},
												},
											},
										},
									},
								},
							},
							"environment_variables": schema.ListNestedAttribute{
								Description: "The environment variables to pass over to the script.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.List{
									listplanmodifier.UseStateForUnknown(),
									listplanmodifier.RequiresReplace(),
								},
								NestedObject: schema.NestedAttributeObject{
									Attributes: map[string]schema.Attribute{
										"name": schema.StringAttribute{
											Description: "The name of the environment variable.",
											Required:    true,
										},
										"secure_value": schema.StringAttribute{
											Description: "The value of the secure environment variable.",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
										},
										"value": schema.StringAttribute{
											Description: "The value of the environment variable.",
											Optional:    true,
											Computed:    true,
											PlanModifiers: []planmodifier.String{
												stringplanmodifier.UseStateForUnknown(),
											},
										},
									},
								},
							},
							"force_update_tag": schema.StringAttribute{
								Description: "Gets or sets how the deployment script should be forced to execute even if the script resource has not changed. Can be current time stamp or a GUID.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
									stringplanmodifier.RequiresReplace(),
								},
							},
							"outputs": schema.MapAttribute{
								Description: "List of script outputs.",
								Computed:    true,
								PlanModifiers: []planmodifier.Map{
									mapplanmodifier.UseStateForUnknown(),
								},
								ElementType: types.StringType,
							},
							"primary_script_uri": schema.StringAttribute{
								Description: "Uri for the script. This is the entry point for the external script.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
									stringplanmodifier.RequiresReplace(),
								},
							},
							"provisioning_state": schema.StringAttribute{
								Description: "State of the script execution. This only appears in the response.",
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"retention_interval": schema.StringAttribute{
								Description: "Interval for which the service retains the script resource after it reaches a terminal state. Resource will be deleted when this duration expires. Duration is based on ISO 8601 pattern (for example P1...",
								Required:    true,
								Validators: []validator.String{
									stringvalidator.RegexMatches(
										regexp.MustCompile(`^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$`),
										"must be in datetime format yyyy-MM-ddTHH:mm:ssZ",
									),
								},
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.RequiresReplace(),
								},
							},
							"script_content": schema.StringAttribute{
								Description: "Script body.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
									stringplanmodifier.RequiresReplace(),
								},
							},
							"status": schema.SingleNestedAttribute{
								Description: "Contains the results of script execution.",
								Computed:    true,
								PlanModifiers: []planmodifier.Object{
									objectplanmodifier.UseStateForUnknown(),
								},
								Attributes: map[string]schema.Attribute{
									"container_instance_id": schema.StringAttribute{
										Description: "ACI resource Id.",
										Computed:    true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
										},
									},
									"end_time": schema.StringAttribute{
										Description: "End time of the script execution.",
										Computed:    true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
										},
									},
									"error": schema.SingleNestedAttribute{
										Description: "Error that is relayed from the script execution.",
										Required:    true,
										Attributes: map[string]schema.Attribute{
											"additional_info": schema.ListNestedAttribute{
												Description: "The error additional info.",
												Computed:    true,
												PlanModifiers: []planmodifier.List{
													listplanmodifier.UseStateForUnknown(),
												},
												NestedObject: schema.NestedAttributeObject{
													Attributes: map[string]schema.Attribute{
														"info": schema.StringAttribute{
															Description: "The additional info.",
															Computed:    true,
														},
														"type": schema.StringAttribute{
															Description: "The additional info type.",
															Computed:    true,
															PlanModifiers: []planmodifier.String{
																stringplanmodifier.UseStateForUnknown(),
															},
														},
													},
												},
											},
											"code": schema.StringAttribute{
												Description: "The error code.",
												Computed:    true,
												PlanModifiers: []planmodifier.String{
													stringplanmodifier.UseStateForUnknown(),
												},
											},
											"details": schema.ListAttribute{
												Description: "The error details.",
												Computed:    true,
												PlanModifiers: []planmodifier.List{
													listplanmodifier.UseStateForUnknown(),
												},
												ElementType: types.StringType,
											},
											"message": schema.StringAttribute{
												Description: "The error message.",
												Computed:    true,
												PlanModifiers: []planmodifier.String{
													stringplanmodifier.UseStateForUnknown(),
												},
											},
											"target": schema.StringAttribute{
												Description: "The error target.",
												Computed:    true,
												PlanModifiers: []planmodifier.String{
													stringplanmodifier.UseStateForUnknown(),
												},
											},
										},
									},
									"expiration_time": schema.StringAttribute{
										Description: "Time the deployment script resource will expire.",
										Computed:    true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
										},
									},
									"start_time": schema.StringAttribute{
										Description: "Start time of the script execution.",
										Computed:    true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
										},
									},
									"storage_account_id": schema.StringAttribute{
										Description: "Storage account resource Id.",
										Computed:    true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
										},
									},
								},
							},
							"storage_account_settings": schema.SingleNestedAttribute{
								Description: "Storage Account settings.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.Object{
									objectplanmodifier.UseStateForUnknown(),
									objectplanmodifier.RequiresReplace(),
								},
								Attributes: map[string]schema.Attribute{
									"storage_account_key": schema.StringAttribute{
										Description: "The storage account access key.",
										Optional:    true,
										Computed:    true,
										Sensitive:   true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
										},
									},
									"storage_account_name": schema.StringAttribute{
										Description: "The storage account name.",
										Optional:    true,
										Computed:    true,
										PlanModifiers: []planmodifier.String{
											stringplanmodifier.UseStateForUnknown(),
										},
									},
								},
							},
							"supporting_script_uris": schema.ListAttribute{
								Description: "Supporting files for the external script.",
								Optional:    true,
								Computed:    true,
								PlanModifiers: []planmodifier.List{
									listplanmodifier.UseStateForUnknown(),
									listplanmodifier.RequiresReplace(),
								},
								ElementType: types.StringType,
							},
							"timeout": schema.StringAttribute{
								Description: "Maximum allowed script execution time specified in ISO 8601 format. Default value is P1D",
								Optional:    true,
								Computed:    true,
								Default:     stringdefault.StaticString("P1D"),
								Validators: []validator.String{
									stringvalidator.RegexMatches(
										regexp.MustCompile(`^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z$`),
										"must be in datetime format yyyy-MM-ddTHH:mm:ssZ",
									),
								},
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.RequiresReplace(),
								},
							},
						},
					},
				},
			},
			"id": schema.StringAttribute{
				Computed:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				MarkdownDescription: "The ID of the Azure resource.",
			},
		},
	}
}

// ResourcesDeploymentScript describes azapi_resources_deployment_script for registration and config builders.
var ResourcesDeploymentScript = services.Descriptor{
	Name:           "azapi_resources_deployment_script",
	ARMType:        "Microsoft.Resources/deploymentScripts",
	APIVersion:     "2023-08-01",
	Schema:         AzapiResourcesDeploymentScriptSchema,
	WritableScopes: 8,
	ParentAttr:     "resource_group_id",
	Timeouts: services.Timeouts{
		Create: 30 * time.Minute,
		Read:   5 * time.Minute,
		Update: 30 * time.Minute,
		Delete: 30 * time.Minute,
	},
}

func init() { services.Register(ResourcesDeploymentScript) }
