// Code generated by azapin; DO NOT EDIT.
package resources

import (
	"time"

	"regexp"

	"github.com/Azure/terraform-provider-azapi/internal/native/schema/planmodifiers"
	"github.com/Azure/terraform-provider-azapi/internal/native/services"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/mapplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/objectplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// AzapiResourceGroupSchema returns the Terraform resource schema for Microsoft.Resources/resourceGroups@2025-04-01.
func AzapiResourceGroupSchema() schema.Schema {
	return schema.Schema{
		Description: "Manages a Microsoft.Resources/resourceGroups resource. [azapin:Microsoft.Resources/resourceGroups@2025-04-01]",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 90),
					stringvalidator.RegexMatches(
						regexp.MustCompile(`^[-\w._()]*[-\w_()]$`),
						"resource group name may contain only alphanumerics, dashes, underscores, parentheses and periods, and may not end with a period",
					),
				},
				MarkdownDescription: "Specifies the name of the Azure resource.",
			},
			"subscription_id": schema.StringAttribute{
				Required:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.RequiresReplace()},
				Validators: []validator.String{
					stringvalidator.RegexMatches(
						regexp.MustCompile(`(?i)^/subscriptions/[^/]+$`),
						"subscription_id must be a subscription ID (/subscriptions/{id})",
					),
				},
				MarkdownDescription: "The ID of the parent resource that contains this resource.",
			},
			"location": schema.StringAttribute{
				Description: "The geo-location where the resource lives",
				Required:    true,
				PlanModifiers: []planmodifier.String{
					planmodifiers.UseStateForEquivalentLocation(),
					stringplanmodifier.RequiresReplace(),
				},
			},
			"managed_by": schema.StringAttribute{
				Description: "The ID of the resource that manages this resource group.",
				Optional:    true,
				Computed:    true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"properties": schema.SingleNestedAttribute{
				Description: "The resource group properties.",
				Computed:    true,
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.UseStateForUnknown(),
				},
				Attributes: map[string]schema.Attribute{
					"provisioning_state": schema.StringAttribute{
						Description: "The provisioning state.",
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
				},
			},
			"system_data": schema.SingleNestedAttribute{
				Description: "Azure Resource Manager metadata containing createdBy and modifiedBy information.",
				Computed:    true,
				PlanModifiers: []planmodifier.Object{
					objectplanmodifier.UseStateForUnknown(),
				},
				Attributes: map[string]schema.Attribute{
					"created_at": schema.StringAttribute{
						Description: "The timestamp of resource creation (UTC).",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"created_by": schema.StringAttribute{
						Description: "The identity that created the resource.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"created_by_type": schema.StringAttribute{
						Description: "The type of identity that created the resource.",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"User",
								"Application",
								"ManagedIdentity",
								"Key",
							),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"last_modified_at": schema.StringAttribute{
						Description: "The timestamp of resource last modification (UTC)",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"last_modified_by": schema.StringAttribute{
						Description: "The identity that last modified the resource.",
						Optional:    true,
						Computed:    true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
					"last_modified_by_type": schema.StringAttribute{
						Description: "The type of identity that last modified the resource.",
						Optional:    true,
						Computed:    true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"User",
								"Application",
								"ManagedIdentity",
								"Key",
							),
						},
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
				},
			},
			"tags": schema.MapAttribute{
				Description: "Resource tags.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.Map{
					mapplanmodifier.UseStateForUnknown(),
				},
				ElementType: types.StringType,
			},
			"id": schema.StringAttribute{
				Computed:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				MarkdownDescription: "The ID of the Azure resource.",
			},
		},
	}
}

// ResourceGroup describes azapi_resource_group for registration and config builders.
var ResourceGroup = services.Descriptor{
	Name:           "azapi_resource_group",
	ARMType:        "Microsoft.Resources/resourceGroups",
	APIVersion:     "2025-04-01",
	Schema:         AzapiResourceGroupSchema,
	WritableScopes: 4,
	ParentAttr:     "subscription_id",
	Timeouts: services.Timeouts{
		Create: 90 * time.Minute,
		Read:   5 * time.Minute,
		Update: 90 * time.Minute,
		Delete: 90 * time.Minute,
	},
}

func init() { services.Register(ResourceGroup) }
